// Code generated by ent, DO NOT EDIT.

package call

import (
	"cameo/internal/ent/entity"
	call2 "cameo/internal/ent/schema_types/call"
	"database/sql/driver"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the call type in the database.
	Label = "call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTranscriptStatus holds the string denoting the transcript_status field in the database.
	FieldTranscriptStatus = "transcript_status"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldRecordingKey holds the string denoting the recording_key field in the database.
	FieldRecordingKey = "recording_key"
	// FieldFavoritedBy holds the string denoting the favorited_by field in the database.
	FieldFavoritedBy = "favorited_by"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldTranscript holds the string denoting the transcript field in the database.
	FieldTranscript = "transcript"
	// FieldCoupleID holds the string denoting the couple_id field in the database.
	FieldCoupleID = "couple_id"
	// FieldCallerID holds the string denoting the caller_id field in the database.
	FieldCallerID = "caller_id"
	// FieldCalleeID holds the string denoting the callee_id field in the database.
	FieldCalleeID = "callee_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeHighlights holds the string denoting the highlights edge name in mutations.
	EdgeHighlights = "highlights"
	// EdgePhotos holds the string denoting the photos edge name in mutations.
	EdgePhotos = "photos"
	// EdgeCouple holds the string denoting the couple edge name in mutations.
	EdgeCouple = "couple"
	// EdgeCaller holds the string denoting the caller edge name in mutations.
	EdgeCaller = "caller"
	// EdgeCallee holds the string denoting the callee edge name in mutations.
	EdgeCallee = "callee"
	// Table holds the table name of the call in the database.
	Table = "calls"
	// HighlightsTable is the table that holds the highlights relation/edge.
	HighlightsTable = "call_highlights"
	// HighlightsInverseTable is the table name for the CallHighlight entity.
	// It exists in this package in order to avoid circular dependency with the "callhighlight" package.
	HighlightsInverseTable = "call_highlights"
	// HighlightsColumn is the table column denoting the highlights relation/edge.
	HighlightsColumn = "call_id"
	// PhotosTable is the table that holds the photos relation/edge.
	PhotosTable = "photos"
	// PhotosInverseTable is the table name for the Photo entity.
	// It exists in this package in order to avoid circular dependency with the "photo" package.
	PhotosInverseTable = "photos"
	// PhotosColumn is the table column denoting the photos relation/edge.
	PhotosColumn = "call_id"
	// CoupleTable is the table that holds the couple relation/edge.
	CoupleTable = "calls"
	// CoupleInverseTable is the table name for the Couple entity.
	// It exists in this package in order to avoid circular dependency with the "couple" package.
	CoupleInverseTable = "couples"
	// CoupleColumn is the table column denoting the couple relation/edge.
	CoupleColumn = "couple_id"
	// CallerTable is the table that holds the caller relation/edge.
	CallerTable = "calls"
	// CallerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CallerInverseTable = "users"
	// CallerColumn is the table column denoting the caller relation/edge.
	CallerColumn = "caller_id"
	// CalleeTable is the table that holds the callee relation/edge.
	CalleeTable = "calls"
	// CalleeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CalleeInverseTable = "users"
	// CalleeColumn is the table column denoting the callee relation/edge.
	CalleeColumn = "callee_id"
)

var (
	ID               = ent.OrderedColumn[entity.Call, uuid.UUID]{Table: Table, Name: FieldID}
	Status           = ent.OrderedColumn[entity.Call, call2.Status]{Table: Table, Name: FieldStatus, Valuer: func(value call2.Status) (driver.Value, error) { return int8(value), nil }}
	TranscriptStatus = ent.OrderedColumn[entity.Call, call2.TranscriptStatus]{Table: Table, Name: FieldTranscriptStatus, Valuer: func(value call2.TranscriptStatus) (driver.Value, error) { return int8(value), nil }}
	Title            = ent.StringColumn[entity.Call, string]{Table: Table, Name: FieldTitle}
	Summary          = ent.StringColumn[entity.Call, string]{Table: Table, Name: FieldSummary}
	RecordingKey     = ent.StringColumn[entity.Call, string]{Table: Table, Name: FieldRecordingKey}
	FavoritedBy      = ent.ArrayColumn[entity.Call, uuid.UUID]{Table: Table, Name: FieldFavoritedBy}
	StartedAt        = ent.OrderedColumn[entity.Call, time2.Time]{Table: Table, Name: FieldStartedAt}
	EndedAt          = ent.OrderedColumn[entity.Call, time2.Time]{Table: Table, Name: FieldEndedAt}
	Transcript       = ent.JSONColumn[entity.Call, []call2.Segment]{Table: Table, Name: FieldTranscript}
	CoupleID         = ent.OrderedColumn[entity.Call, uuid.UUID]{Table: Table, Name: FieldCoupleID}
	CallerID         = ent.OrderedColumn[entity.Call, uuid.UUID]{Table: Table, Name: FieldCallerID}
	CalleeID         = ent.OrderedColumn[entity.Call, uuid.UUID]{Table: Table, Name: FieldCalleeID}
	CreatedAt        = ent.OrderedColumn[entity.Call, time2.Time]{Table: Table, Name: FieldCreatedAt}
	UpdatedAt        = ent.OrderedColumn[entity.Call, time2.Time]{Table: Table, Name: FieldUpdatedAt}
	Highlights       = ent.NewRelation[entity.Call, entity.CallHighlight, uuid.UUID](EdgeHighlights, newHighlightsStep)
	Photos           = ent.NewRelation[entity.Call, entity.Photo, uuid.UUID](EdgePhotos, newPhotosStep)
	Couple           = ent.NewUniqueRelation[entity.Call, entity.Couple, uuid.UUID](EdgeCouple, newCoupleStep)
	Caller           = ent.NewUniqueRelation[entity.Call, entity.User, uuid.UUID](EdgeCaller, newCallerStep)
	Callee           = ent.NewUniqueRelation[entity.Call, entity.User, uuid.UUID](EdgeCallee, newCalleeStep)
)

// Alias returns the columns of the calls table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:       name,
		ID:               ent.OrderedColumn[entity.Call, uuid.UUID]{Table: name, Name: FieldID},
		Status:           ent.OrderedColumn[entity.Call, call2.Status]{Table: name, Name: FieldStatus, Valuer: func(value call2.Status) (driver.Value, error) { return int8(value), nil }},
		TranscriptStatus: ent.OrderedColumn[entity.Call, call2.TranscriptStatus]{Table: name, Name: FieldTranscriptStatus, Valuer: func(value call2.TranscriptStatus) (driver.Value, error) { return int8(value), nil }},
		Title:            ent.StringColumn[entity.Call, string]{Table: name, Name: FieldTitle},
		Summary:          ent.StringColumn[entity.Call, string]{Table: name, Name: FieldSummary},
		RecordingKey:     ent.StringColumn[entity.Call, string]{Table: name, Name: FieldRecordingKey},
		FavoritedBy:      ent.ArrayColumn[entity.Call, uuid.UUID]{Table: name, Name: FieldFavoritedBy},
		StartedAt:        ent.OrderedColumn[entity.Call, time2.Time]{Table: name, Name: FieldStartedAt},
		EndedAt:          ent.OrderedColumn[entity.Call, time2.Time]{Table: name, Name: FieldEndedAt},
		Transcript:       ent.JSONColumn[entity.Call, []call2.Segment]{Table: name, Name: FieldTranscript},
		CoupleID:         ent.OrderedColumn[entity.Call, uuid.UUID]{Table: name, Name: FieldCoupleID},
		CallerID:         ent.OrderedColumn[entity.Call, uuid.UUID]{Table: name, Name: FieldCallerID},
		CalleeID:         ent.OrderedColumn[entity.Call, uuid.UUID]{Table: name, Name: FieldCalleeID},
		CreatedAt:        ent.OrderedColumn[entity.Call, time2.Time]{Table: name, Name: FieldCreatedAt},
		UpdatedAt:        ent.OrderedColumn[entity.Call, time2.Time]{Table: name, Name: FieldUpdatedAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias       string
	ID               ent.OrderedColumn[entity.Call, uuid.UUID]
	Status           ent.OrderedColumn[entity.Call, call2.Status]
	TranscriptStatus ent.OrderedColumn[entity.Call, call2.TranscriptStatus]
	Title            ent.StringColumn[entity.Call, string]
	Summary          ent.StringColumn[entity.Call, string]
	RecordingKey     ent.StringColumn[entity.Call, string]
	FavoritedBy      ent.ArrayColumn[entity.Call, uuid.UUID]
	StartedAt        ent.OrderedColumn[entity.Call, time2.Time]
	EndedAt          ent.OrderedColumn[entity.Call, time2.Time]
	Transcript       ent.JSONColumn[entity.Call, []call2.Segment]
	CoupleID         ent.OrderedColumn[entity.Call, uuid.UUID]
	CallerID         ent.OrderedColumn[entity.Call, uuid.UUID]
	CalleeID         ent.OrderedColumn[entity.Call, uuid.UUID]
	CreatedAt        ent.OrderedColumn[entity.Call, time2.Time]
	UpdatedAt        ent.OrderedColumn[entity.Call, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Call]) ent.Predicate[entity.Call] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Call]) ent.Predicate[entity.Call] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Call]) ent.Predicate[entity.Call] { return ent.Not(predicate) }

// Columns holds all SQL columns for call fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldTranscriptStatus,
	FieldTitle,
	FieldSummary,
	FieldRecordingKey,
	FieldFavoritedBy,
	FieldStartedAt,
	FieldEndedAt,
	FieldTranscript,
	FieldCoupleID,
	FieldCallerID,
	FieldCalleeID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus func() call2.Status
	// DefaultTranscriptStatus holds the default value on creation for the "transcript_status" field.
	DefaultTranscriptStatus func() call2.TranscriptStatus
	// DefaultFavoritedBy holds the default value on creation for the "favorited_by" field.
	DefaultFavoritedBy []uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time2.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time2.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

func newHighlightsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HighlightsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HighlightsTable, HighlightsColumn),
	)
}
func newPhotosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhotosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PhotosTable, PhotosColumn),
	)
}
func newCoupleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CoupleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CoupleTable, CoupleColumn),
	)
}
func newCallerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CallerTable, CallerColumn),
	)
}
func newCalleeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CalleeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CalleeTable, CalleeColumn),
	)
}
