// Code generated by ent, DO NOT EDIT.

package session

import (
	"cameo/internal/ent/entity"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeDevices holds the string denoting the devices edge name in mutations.
	EdgeDevices = "devices"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the session in the database.
	Table = "sessions"
	// DevicesTable is the table that holds the devices relation/edge.
	DevicesTable = "devices"
	// DevicesInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DevicesInverseTable = "devices"
	// DevicesColumn is the table column denoting the devices relation/edge.
	DevicesColumn = "session_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "sessions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

var (
	ID        = ent.OrderedColumn[entity.Session, uuid.UUID]{Table: Table, Name: FieldID}
	UserID    = ent.OrderedColumn[entity.Session, uuid.UUID]{Table: Table, Name: FieldUserID}
	CreatedAt = ent.OrderedColumn[entity.Session, time2.Time]{Table: Table, Name: FieldCreatedAt}
	UpdatedAt = ent.OrderedColumn[entity.Session, time2.Time]{Table: Table, Name: FieldUpdatedAt}
	ExpiresAt = ent.OrderedColumn[entity.Session, time2.Time]{Table: Table, Name: FieldExpiresAt}
	Devices   = ent.NewRelation[entity.Session, entity.Device, uuid.UUID](EdgeDevices, newDevicesStep)
	User      = ent.NewUniqueRelation[entity.Session, entity.User, uuid.UUID](EdgeUser, newUserStep)
)

// Alias returns the columns of the sessions table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Session, uuid.UUID]{Table: name, Name: FieldID},
		UserID:     ent.OrderedColumn[entity.Session, uuid.UUID]{Table: name, Name: FieldUserID},
		CreatedAt:  ent.OrderedColumn[entity.Session, time2.Time]{Table: name, Name: FieldCreatedAt},
		UpdatedAt:  ent.OrderedColumn[entity.Session, time2.Time]{Table: name, Name: FieldUpdatedAt},
		ExpiresAt:  ent.OrderedColumn[entity.Session, time2.Time]{Table: name, Name: FieldExpiresAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Session, uuid.UUID]
	UserID     ent.OrderedColumn[entity.Session, uuid.UUID]
	CreatedAt  ent.OrderedColumn[entity.Session, time2.Time]
	UpdatedAt  ent.OrderedColumn[entity.Session, time2.Time]
	ExpiresAt  ent.OrderedColumn[entity.Session, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Session]) ent.Predicate[entity.Session] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Session]) ent.Predicate[entity.Session] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Session]) ent.Predicate[entity.Session] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time2.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time2.Time
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time2.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

func newDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
