// Code generated by ent, DO NOT EDIT.

package photo

import (
	"cameo/internal/ent/entity"
	photo2 "cameo/internal/ent/schema_types/photo"
	"database/sql/driver"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the photo type in the database.
	Label = "photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldObjectKey holds the string denoting the object_key field in the database.
	FieldObjectKey = "object_key"
	// FieldThumbnailKey holds the string denoting the thumbnail_key field in the database.
	FieldThumbnailKey = "thumbnail_key"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldThumbnailSizeBytes holds the string denoting the thumbnail_size_bytes field in the database.
	FieldThumbnailSizeBytes = "thumbnail_size_bytes"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldTakenAt holds the string denoting the taken_at field in the database.
	FieldTakenAt = "taken_at"
	// FieldFavoritedBy holds the string denoting the favorited_by field in the database.
	FieldFavoritedBy = "favorited_by"
	// FieldCoupleID holds the string denoting the couple_id field in the database.
	FieldCoupleID = "couple_id"
	// FieldUploaderID holds the string denoting the uploader_id field in the database.
	FieldUploaderID = "uploader_id"
	// FieldCallID holds the string denoting the call_id field in the database.
	FieldCallID = "call_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCouple holds the string denoting the couple edge name in mutations.
	EdgeCouple = "couple"
	// EdgeUploader holds the string denoting the uploader edge name in mutations.
	EdgeUploader = "uploader"
	// EdgeCall holds the string denoting the call edge name in mutations.
	EdgeCall = "call"
	// Table holds the table name of the photo in the database.
	Table = "photos"
	// CoupleTable is the table that holds the couple relation/edge.
	CoupleTable = "photos"
	// CoupleInverseTable is the table name for the Couple entity.
	// It exists in this package in order to avoid circular dependency with the "couple" package.
	CoupleInverseTable = "couples"
	// CoupleColumn is the table column denoting the couple relation/edge.
	CoupleColumn = "couple_id"
	// UploaderTable is the table that holds the uploader relation/edge.
	UploaderTable = "photos"
	// UploaderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UploaderInverseTable = "users"
	// UploaderColumn is the table column denoting the uploader relation/edge.
	UploaderColumn = "uploader_id"
	// CallTable is the table that holds the call relation/edge.
	CallTable = "photos"
	// CallInverseTable is the table name for the Call entity.
	// It exists in this package in order to avoid circular dependency with the "call" package.
	CallInverseTable = "calls"
	// CallColumn is the table column denoting the call relation/edge.
	CallColumn = "call_id"
)

var (
	ID                 = ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: Table, Name: FieldID}
	Status             = ent.OrderedColumn[entity.Photo, photo2.Status]{Table: Table, Name: FieldStatus, Valuer: func(value photo2.Status) (driver.Value, error) { return int8(value), nil }}
	ContentType        = ent.StringColumn[entity.Photo, string]{Table: Table, Name: FieldContentType}
	ObjectKey          = ent.StringColumn[entity.Photo, string]{Table: Table, Name: FieldObjectKey}
	ThumbnailKey       = ent.StringColumn[entity.Photo, string]{Table: Table, Name: FieldThumbnailKey}
	SizeBytes          = ent.OrderedColumn[entity.Photo, int64]{Table: Table, Name: FieldSizeBytes}
	ThumbnailSizeBytes = ent.OrderedColumn[entity.Photo, int64]{Table: Table, Name: FieldThumbnailSizeBytes}
	Width              = ent.OrderedColumn[entity.Photo, int]{Table: Table, Name: FieldWidth}
	Height             = ent.OrderedColumn[entity.Photo, int]{Table: Table, Name: FieldHeight}
	TakenAt            = ent.OrderedColumn[entity.Photo, time2.Time]{Table: Table, Name: FieldTakenAt}
	FavoritedBy        = ent.ArrayColumn[entity.Photo, uuid.UUID]{Table: Table, Name: FieldFavoritedBy}
	CoupleID           = ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: Table, Name: FieldCoupleID}
	UploaderID         = ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: Table, Name: FieldUploaderID}
	CallID             = ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: Table, Name: FieldCallID}
	CreatedAt          = ent.OrderedColumn[entity.Photo, time2.Time]{Table: Table, Name: FieldCreatedAt}
	UpdatedAt          = ent.OrderedColumn[entity.Photo, time2.Time]{Table: Table, Name: FieldUpdatedAt}
	Couple             = ent.NewUniqueRelation[entity.Photo, entity.Couple, uuid.UUID](EdgeCouple, newCoupleStep)
	Uploader           = ent.NewUniqueRelation[entity.Photo, entity.User, uuid.UUID](EdgeUploader, newUploaderStep)
	Call               = ent.NewUniqueRelation[entity.Photo, entity.Call, uuid.UUID](EdgeCall, newCallStep)
)

// Alias returns the columns of the photos table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:         name,
		ID:                 ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: name, Name: FieldID},
		Status:             ent.OrderedColumn[entity.Photo, photo2.Status]{Table: name, Name: FieldStatus, Valuer: func(value photo2.Status) (driver.Value, error) { return int8(value), nil }},
		ContentType:        ent.StringColumn[entity.Photo, string]{Table: name, Name: FieldContentType},
		ObjectKey:          ent.StringColumn[entity.Photo, string]{Table: name, Name: FieldObjectKey},
		ThumbnailKey:       ent.StringColumn[entity.Photo, string]{Table: name, Name: FieldThumbnailKey},
		SizeBytes:          ent.OrderedColumn[entity.Photo, int64]{Table: name, Name: FieldSizeBytes},
		ThumbnailSizeBytes: ent.OrderedColumn[entity.Photo, int64]{Table: name, Name: FieldThumbnailSizeBytes},
		Width:              ent.OrderedColumn[entity.Photo, int]{Table: name, Name: FieldWidth},
		Height:             ent.OrderedColumn[entity.Photo, int]{Table: name, Name: FieldHeight},
		TakenAt:            ent.OrderedColumn[entity.Photo, time2.Time]{Table: name, Name: FieldTakenAt},
		FavoritedBy:        ent.ArrayColumn[entity.Photo, uuid.UUID]{Table: name, Name: FieldFavoritedBy},
		CoupleID:           ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: name, Name: FieldCoupleID},
		UploaderID:         ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: name, Name: FieldUploaderID},
		CallID:             ent.OrderedColumn[entity.Photo, uuid.UUID]{Table: name, Name: FieldCallID},
		CreatedAt:          ent.OrderedColumn[entity.Photo, time2.Time]{Table: name, Name: FieldCreatedAt},
		UpdatedAt:          ent.OrderedColumn[entity.Photo, time2.Time]{Table: name, Name: FieldUpdatedAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias         string
	ID                 ent.OrderedColumn[entity.Photo, uuid.UUID]
	Status             ent.OrderedColumn[entity.Photo, photo2.Status]
	ContentType        ent.StringColumn[entity.Photo, string]
	ObjectKey          ent.StringColumn[entity.Photo, string]
	ThumbnailKey       ent.StringColumn[entity.Photo, string]
	SizeBytes          ent.OrderedColumn[entity.Photo, int64]
	ThumbnailSizeBytes ent.OrderedColumn[entity.Photo, int64]
	Width              ent.OrderedColumn[entity.Photo, int]
	Height             ent.OrderedColumn[entity.Photo, int]
	TakenAt            ent.OrderedColumn[entity.Photo, time2.Time]
	FavoritedBy        ent.ArrayColumn[entity.Photo, uuid.UUID]
	CoupleID           ent.OrderedColumn[entity.Photo, uuid.UUID]
	UploaderID         ent.OrderedColumn[entity.Photo, uuid.UUID]
	CallID             ent.OrderedColumn[entity.Photo, uuid.UUID]
	CreatedAt          ent.OrderedColumn[entity.Photo, time2.Time]
	UpdatedAt          ent.OrderedColumn[entity.Photo, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Photo]) ent.Predicate[entity.Photo] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Photo]) ent.Predicate[entity.Photo] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Photo]) ent.Predicate[entity.Photo] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for photo fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldContentType,
	FieldObjectKey,
	FieldThumbnailKey,
	FieldSizeBytes,
	FieldThumbnailSizeBytes,
	FieldWidth,
	FieldHeight,
	FieldTakenAt,
	FieldFavoritedBy,
	FieldCoupleID,
	FieldUploaderID,
	FieldCallID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus func() photo2.Status
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	ObjectKeyValidator func(string) error
	// ThumbnailKeyValidator is a validator for the "thumbnail_key" field. It is called by the builders before save.
	ThumbnailKeyValidator func(string) error
	// DefaultThumbnailSizeBytes holds the default value on creation for the "thumbnail_size_bytes" field.
	DefaultThumbnailSizeBytes int64
	// DefaultFavoritedBy holds the default value on creation for the "favorited_by" field.
	DefaultFavoritedBy []uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time2.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time2.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

func newCoupleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CoupleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CoupleTable, CoupleColumn),
	)
}
func newUploaderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploaderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UploaderTable, UploaderColumn),
	)
}
func newCallStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CallTable, CallColumn),
	)
}
