// Code generated by ent, DO NOT EDIT.

package callhighlight

import (
	"cameo/internal/ent/entity"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the callhighlight type in the database.
	Label = "call_highlight"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOffsetSeconds holds the string denoting the offset_seconds field in the database.
	FieldOffsetSeconds = "offset_seconds"
	// FieldCallID holds the string denoting the call_id field in the database.
	FieldCallID = "call_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCall holds the string denoting the call edge name in mutations.
	EdgeCall = "call"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the callhighlight in the database.
	Table = "call_highlights"
	// CallTable is the table that holds the call relation/edge.
	CallTable = "call_highlights"
	// CallInverseTable is the table name for the Call entity.
	// It exists in this package in order to avoid circular dependency with the "call" package.
	CallInverseTable = "calls"
	// CallColumn is the table column denoting the call relation/edge.
	CallColumn = "call_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "call_highlights"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

var (
	ID            = ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: Table, Name: FieldID}
	OffsetSeconds = ent.OrderedColumn[entity.CallHighlight, float64]{Table: Table, Name: FieldOffsetSeconds}
	CallID        = ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: Table, Name: FieldCallID}
	UserID        = ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: Table, Name: FieldUserID}
	CreatedAt     = ent.OrderedColumn[entity.CallHighlight, time2.Time]{Table: Table, Name: FieldCreatedAt}
	Call          = ent.NewUniqueRelation[entity.CallHighlight, entity.Call, uuid.UUID](EdgeCall, newCallStep)
	User          = ent.NewUniqueRelation[entity.CallHighlight, entity.User, uuid.UUID](EdgeUser, newUserStep)
)

// Alias returns the columns of the call_highlights table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:    name,
		ID:            ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: name, Name: FieldID},
		OffsetSeconds: ent.OrderedColumn[entity.CallHighlight, float64]{Table: name, Name: FieldOffsetSeconds},
		CallID:        ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: name, Name: FieldCallID},
		UserID:        ent.OrderedColumn[entity.CallHighlight, uuid.UUID]{Table: name, Name: FieldUserID},
		CreatedAt:     ent.OrderedColumn[entity.CallHighlight, time2.Time]{Table: name, Name: FieldCreatedAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias    string
	ID            ent.OrderedColumn[entity.CallHighlight, uuid.UUID]
	OffsetSeconds ent.OrderedColumn[entity.CallHighlight, float64]
	CallID        ent.OrderedColumn[entity.CallHighlight, uuid.UUID]
	UserID        ent.OrderedColumn[entity.CallHighlight, uuid.UUID]
	CreatedAt     ent.OrderedColumn[entity.CallHighlight, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.CallHighlight]) ent.Predicate[entity.CallHighlight] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.CallHighlight]) ent.Predicate[entity.CallHighlight] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.CallHighlight]) ent.Predicate[entity.CallHighlight] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for callhighlight fields.
var Columns = []string{
	FieldID,
	FieldOffsetSeconds,
	FieldCallID,
	FieldUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OffsetSecondsValidator is a validator for the "offset_seconds" field. It is called by the builders before save.
	OffsetSecondsValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

func newCallStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CallTable, CallColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
