// Code generated by ent, DO NOT EDIT.

package couple

import (
	"cameo/internal/ent/entity"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the couple type in the database.
	Label = "couple"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserIDs holds the string denoting the user_ids field in the database.
	FieldUserIDs = "user_ids"
	// FieldDisconnectedAt holds the string denoting the disconnected_at field in the database.
	FieldDisconnectedAt = "disconnected_at"
	// FieldRestoredAt holds the string denoting the restored_at field in the database.
	FieldRestoredAt = "restored_at"
	// FieldRestoreTransactionID holds the string denoting the restore_transaction_id field in the database.
	FieldRestoreTransactionID = "restore_transaction_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeCalls holds the string denoting the calls edge name in mutations.
	EdgeCalls = "calls"
	// EdgePhotos holds the string denoting the photos edge name in mutations.
	EdgePhotos = "photos"
	// Table holds the table name of the couple in the database.
	Table = "couples"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "users"
	// MembersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	MembersInverseTable = "users"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "couple_id"
	// CallsTable is the table that holds the calls relation/edge.
	CallsTable = "calls"
	// CallsInverseTable is the table name for the Call entity.
	// It exists in this package in order to avoid circular dependency with the "call" package.
	CallsInverseTable = "calls"
	// CallsColumn is the table column denoting the calls relation/edge.
	CallsColumn = "couple_id"
	// PhotosTable is the table that holds the photos relation/edge.
	PhotosTable = "photos"
	// PhotosInverseTable is the table name for the Photo entity.
	// It exists in this package in order to avoid circular dependency with the "photo" package.
	PhotosInverseTable = "photos"
	// PhotosColumn is the table column denoting the photos relation/edge.
	PhotosColumn = "couple_id"
)

var (
	ID                   = ent.OrderedColumn[entity.Couple, uuid.UUID]{Table: Table, Name: FieldID}
	UserIDs              = ent.ArrayColumn[entity.Couple, uuid.UUID]{Table: Table, Name: FieldUserIDs}
	DisconnectedAt       = ent.OrderedColumn[entity.Couple, time2.Time]{Table: Table, Name: FieldDisconnectedAt}
	RestoredAt           = ent.OrderedColumn[entity.Couple, time2.Time]{Table: Table, Name: FieldRestoredAt}
	RestoreTransactionID = ent.StringColumn[entity.Couple, string]{Table: Table, Name: FieldRestoreTransactionID}
	CreatedAt            = ent.OrderedColumn[entity.Couple, time2.Time]{Table: Table, Name: FieldCreatedAt}
	Members              = ent.NewRelation[entity.Couple, entity.User, uuid.UUID](EdgeMembers, newMembersStep)
	Calls                = ent.NewRelation[entity.Couple, entity.Call, uuid.UUID](EdgeCalls, newCallsStep)
	Photos               = ent.NewRelation[entity.Couple, entity.Photo, uuid.UUID](EdgePhotos, newPhotosStep)
)

// Alias returns the columns of the couples table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:           name,
		ID:                   ent.OrderedColumn[entity.Couple, uuid.UUID]{Table: name, Name: FieldID},
		UserIDs:              ent.ArrayColumn[entity.Couple, uuid.UUID]{Table: name, Name: FieldUserIDs},
		DisconnectedAt:       ent.OrderedColumn[entity.Couple, time2.Time]{Table: name, Name: FieldDisconnectedAt},
		RestoredAt:           ent.OrderedColumn[entity.Couple, time2.Time]{Table: name, Name: FieldRestoredAt},
		RestoreTransactionID: ent.StringColumn[entity.Couple, string]{Table: name, Name: FieldRestoreTransactionID},
		CreatedAt:            ent.OrderedColumn[entity.Couple, time2.Time]{Table: name, Name: FieldCreatedAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias           string
	ID                   ent.OrderedColumn[entity.Couple, uuid.UUID]
	UserIDs              ent.ArrayColumn[entity.Couple, uuid.UUID]
	DisconnectedAt       ent.OrderedColumn[entity.Couple, time2.Time]
	RestoredAt           ent.OrderedColumn[entity.Couple, time2.Time]
	RestoreTransactionID ent.StringColumn[entity.Couple, string]
	CreatedAt            ent.OrderedColumn[entity.Couple, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Couple]) ent.Predicate[entity.Couple] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Couple]) ent.Predicate[entity.Couple] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Couple]) ent.Predicate[entity.Couple] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for couple fields.
var Columns = []string{
	FieldID,
	FieldUserIDs,
	FieldDisconnectedAt,
	FieldRestoredAt,
	FieldRestoreTransactionID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserIDs holds the default value on creation for the "user_ids" field.
	DefaultUserIDs []uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newCallsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CallsTable, CallsColumn),
	)
}
func newPhotosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhotosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PhotosTable, PhotosColumn),
	)
}
