// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	call2 "cameo/internal/ent/schema_types/call"
	"fmt"
	"slices"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// CallInsert is the write representation of a Call creation.
type CallInsert struct {
	ID               ent.Option[uuid.UUID]              `json:"id,omitzero"`
	Status           ent.Option[call2.Status]           `json:"status,omitzero"`
	TranscriptStatus ent.Option[call2.TranscriptStatus] `json:"transcript_status,omitzero"`
	Title            ent.Option[string]                 `json:"title,omitzero"`
	Summary          ent.Option[string]                 `json:"summary,omitzero"`
	RecordingKey     ent.Option[string]                 `json:"recording_key,omitzero"`
	FavoritedBy      ent.Option[[]uuid.UUID]            `json:"favorited_by,omitzero"`
	StartedAt        ent.Option[time2.Time]             `json:"started_at,omitzero"`
	EndedAt          ent.Option[time2.Time]             `json:"ended_at,omitzero"`
	Transcript       ent.Option[[]call2.Segment]        `json:"transcript,omitzero"`
	CoupleID         uuid.UUID                          `json:"couple_id"`
	CallerID         uuid.UUID                          `json:"caller_id"`
	CalleeID         uuid.UUID                          `json:"callee_id"`
	CreatedAt        ent.Option[time2.Time]             `json:"created_at,omitzero"`
	UpdatedAt        ent.Option[time2.Time]             `json:"updated_at,omitzero"`
	HighlightIDs     []uuid.UUID                        `json:"highlight_ids,omitzero"`
	PhotoIDs         []uuid.UUID                        `json:"photo_ids,omitzero"`
	expressions      map[string]func(*sql.Builder)
}

// CallPatch is the write representation of a Call update.
type CallPatch struct {
	Status              ent.Option[call2.Status]           `json:"status,omitzero"`
	StatusAdd           ent.Option[call2.Status]           `json:"status_add,omitzero"`
	TranscriptStatus    ent.Option[call2.TranscriptStatus] `json:"transcript_status,omitzero"`
	TranscriptStatusAdd ent.Option[call2.TranscriptStatus] `json:"transcript_status_add,omitzero"`
	Title               ent.Option[string]                 `json:"title,omitzero"`
	Summary             ent.Option[string]                 `json:"summary,omitzero"`
	RecordingKey        ent.Option[string]                 `json:"recording_key,omitzero"`
	FavoritedBy         ent.Option[[]uuid.UUID]            `json:"favorited_by,omitzero"`
	StartedAt           ent.Option[time2.Time]             `json:"started_at,omitzero"`
	EndedAt             ent.Option[time2.Time]             `json:"ended_at,omitzero"`
	Transcript          ent.Option[[]call2.Segment]        `json:"transcript,omitzero"`
	TranscriptAppend    []call2.Segment                    `json:"transcript_append,omitzero"`
	UpdatedAt           ent.Option[time2.Time]             `json:"updated_at,omitzero"`
	Highlights          ent.RelationPatch[uuid.UUID]       `json:"highlights,omitzero"`
	Photos              ent.RelationPatch[uuid.UUID]       `json:"photos,omitzero"`
	expressions         map[string]func(*sql.Builder)
	clearedEdges        map[string]bool
}

func (i *CallInsert) set(column string, value any) error {
	switch column {

	case call.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldStatus:
		v, ok := value.(call2.Status)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Status = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldTranscriptStatus:
		v, ok := value.(call2.TranscriptStatus)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.TranscriptStatus = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Title = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Summary = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldRecordingKey:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.RecordingKey = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldFavoritedBy:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.FavoritedBy = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldStartedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.StartedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldEndedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.EndedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldTranscript:
		v, ok := value.([]call2.Segment)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Transcript = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldCoupleID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.CoupleID = v

		delete(i.expressions, column)
		return nil

	case call.FieldCallerID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.CallerID = v

		delete(i.expressions, column)
		return nil

	case call.FieldCalleeID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.CalleeID = v

		delete(i.expressions, column)
		return nil

	case call.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call is not settable", column)}
}

func (i *CallInsert) setNull(column string) error {
	switch column {

	case call.FieldTitle:
		i.Title = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldSummary:
		i.Summary = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldRecordingKey:
		i.RecordingKey = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldStartedAt:
		i.StartedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case call.FieldEndedAt:
		i.EndedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case call.FieldTranscript:
		i.Transcript = ent.Null[[]call2.Segment]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call is not nullable", column)}
}

func (i *CallInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CallInsert) setEdge(edge string, id any) error {
	switch edge {

	case call.EdgeCouple:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
		}
		return i.set(call.FieldCoupleID, value)

	case call.EdgeCaller:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
		}
		return i.set(call.FieldCallerID, value)

	case call.EdgeCallee:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
		}
		return i.set(call.FieldCalleeID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call is not settable", edge)}
}

func (i *CallInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	case call.EdgeHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
			}
			i.HighlightIDs = append(i.HighlightIDs, value)
		}
		return nil

	case call.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
			}
			i.PhotoIDs = append(i.PhotoIDs, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call does not accept IDs", edge)}
}

func (i *CallInsert) highlightsIDs() []uuid.UUID {
	return i.HighlightIDs
}

func (i *CallInsert) photosIDs() []uuid.UUID {
	return i.PhotoIDs
}

func (i *CallInsert) coupleIDs() []uuid.UUID {

	return []uuid.UUID{i.CoupleID}

}

func (i *CallInsert) callerIDs() []uuid.UUID {

	return []uuid.UUID{i.CallerID}

}

func (i *CallInsert) calleeIDs() []uuid.UUID {

	return []uuid.UUID{i.CalleeID}

}

func (i *CallPatch) set(column string, value any) error {
	switch column {

	case call.FieldStatus:
		v, ok := value.(call2.Status)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Status = ent.Some(v)

		i.StatusAdd = ent.Unset[call2.Status]()

		delete(i.expressions, column)
		return nil

	case call.FieldTranscriptStatus:
		v, ok := value.(call2.TranscriptStatus)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.TranscriptStatus = ent.Some(v)

		i.TranscriptStatusAdd = ent.Unset[call2.TranscriptStatus]()

		delete(i.expressions, column)
		return nil

	case call.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Title = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Summary = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldRecordingKey:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.RecordingKey = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldFavoritedBy:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.FavoritedBy = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldStartedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.StartedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldEndedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.EndedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case call.FieldTranscript:
		v, ok := value.([]call2.Segment)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.Transcript = ent.Some(v)

		i.TranscriptAppend = nil

		delete(i.expressions, column)
		return nil

	case call.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Call", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call is not settable", column)}
}

func (i *CallPatch) setNull(column string) error {
	switch column {

	case call.FieldTitle:
		i.Title = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldSummary:
		i.Summary = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldRecordingKey:
		i.RecordingKey = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case call.FieldStartedAt:
		i.StartedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case call.FieldEndedAt:
		i.EndedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case call.FieldTranscript:
		i.Transcript = ent.Null[[]call2.Segment]()

		i.TranscriptAppend = nil

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call is not nullable", column)}
}

func (i *CallPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CallPatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call is not settable", edge)}
}

func (i *CallPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	case call.EdgeHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
			}
			i.Highlights.Add = append(i.Highlights.Add, value)
		}
		return nil

	case call.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Call", id, edge)}
			}
			i.Photos.Add = append(i.Photos.Add, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call does not accept IDs", edge)}
}

func (i *CallPatch) highlightsIDs() []uuid.UUID {
	return i.Highlights.Add

}

func (i *CallPatch) photosIDs() []uuid.UUID {
	return i.Photos.Add

}

func (p *CallPatch) add(column string, value any) error {
	switch column {

	case call.FieldStatus:
		delta, ok := value.(call2.Status)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.StatusAdd.Get(); exists {
			delta += current
		}
		p.StatusAdd = ent.Some(delta)
		return nil

	case call.FieldTranscriptStatus:
		delta, ok := value.(call2.TranscriptStatus)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.TranscriptStatusAdd.Get(); exists {
			delta += current
		}
		p.TranscriptStatusAdd = ent.Some(delta)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call does not support addition", column)}
}

func (p *CallPatch) appendValues(column string, value any) error {
	switch column {

	case call.FieldTranscript:
		values, ok := value.([]call2.Segment)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected append type %T for field %q", value, column)}
		}
		p.TranscriptAppend = append(p.TranscriptAppend, values...)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Call does not support append", column)}
}

func (p *CallPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	case call.EdgeHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Highlights.Remove = append(p.Highlights.Remove, value)
			p.Highlights.Add = slices.DeleteFunc(p.Highlights.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case call.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Photos.Remove = append(p.Photos.Remove, value)
			p.Photos.Add = slices.DeleteFunc(p.Photos.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call does not support removal", edge)}
}

func (p *CallPatch) clearEdge(edge string) error {
	switch edge {

	case call.EdgeHighlights:
		p.Highlights.Clear = true
		return nil

	case call.EdgePhotos:
		p.Photos.Clear = true
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Call cannot be cleared", edge)}
}

func (p *CallPatch) apply(other CallPatch) {

	if other.Status.IsSet() {
		p.Status = other.Status
		delete(p.expressions, call.FieldStatus)
	}

	if value, ok := other.StatusAdd.Get(); ok {
		if current, exists := p.StatusAdd.Get(); exists {
			value += current
		}
		p.StatusAdd = ent.Some(value)
	}

	if other.TranscriptStatus.IsSet() {
		p.TranscriptStatus = other.TranscriptStatus
		delete(p.expressions, call.FieldTranscriptStatus)
	}

	if value, ok := other.TranscriptStatusAdd.Get(); ok {
		if current, exists := p.TranscriptStatusAdd.Get(); exists {
			value += current
		}
		p.TranscriptStatusAdd = ent.Some(value)
	}

	if other.Title.IsSet() {
		p.Title = other.Title
		delete(p.expressions, call.FieldTitle)
	}

	if other.Summary.IsSet() {
		p.Summary = other.Summary
		delete(p.expressions, call.FieldSummary)
	}

	if other.RecordingKey.IsSet() {
		p.RecordingKey = other.RecordingKey
		delete(p.expressions, call.FieldRecordingKey)
	}

	if other.FavoritedBy.IsSet() {
		p.FavoritedBy = other.FavoritedBy
		delete(p.expressions, call.FieldFavoritedBy)
	}

	if other.StartedAt.IsSet() {
		p.StartedAt = other.StartedAt
		delete(p.expressions, call.FieldStartedAt)
	}

	if other.EndedAt.IsSet() {
		p.EndedAt = other.EndedAt
		delete(p.expressions, call.FieldEndedAt)
	}

	if other.Transcript.IsSet() {
		p.Transcript = other.Transcript
		delete(p.expressions, call.FieldTranscript)
	}

	p.TranscriptAppend = append(p.TranscriptAppend, other.TranscriptAppend...)

	if other.UpdatedAt.IsSet() {
		p.UpdatedAt = other.UpdatedAt
		delete(p.expressions, call.FieldUpdatedAt)
	}

	p.Highlights.Add = append(p.Highlights.Add, other.Highlights.Add...)
	p.Highlights.Remove = append(p.Highlights.Remove, other.Highlights.Remove...)
	p.Highlights.Clear = p.Highlights.Clear || other.Highlights.Clear

	p.Photos.Add = append(p.Photos.Add, other.Photos.Add...)
	p.Photos.Remove = append(p.Photos.Remove, other.Photos.Remove...)
	p.Photos.Clear = p.Photos.Clear || other.Photos.Clear

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
