// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/callhighlight"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

// CallHighlightQuery is the builder for querying CallHighlight entities.
type CallHighlightQuery struct {
	config
	ctx        *QueryContext
	order      []ent.OrderOption[entity.CallHighlight]
	joins      []func(*sql.Selector)
	withCounts []ent.EdgeCount

	predicates []ent.Predicate[entity.CallHighlight]
	withCall   *CallQuery
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)

	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CallHighlightQuery builder.
func (_q *CallHighlightQuery) Where(predicates ...ent.Predicate[entity.CallHighlight]) *CallHighlightQuery {
	_q.predicates = append(_q.predicates, predicates...)
	return _q
}

func (_q *CallHighlightQuery) WhereP(predicates ...func(*sql.Selector)) *CallHighlightQuery {
	for _, predicate := range predicates {
		_q.predicates = append(_q.predicates, predicate)
	}
	return _q
}

func (_q *CallHighlightQuery) Join(table string, on ...func(*sql.Selector)) *CallHighlightQuery {
	return _q.JoinAs(table, "", on...)
}

func (_q *CallHighlightQuery) JoinAs(table, alias string, on ...func(*sql.Selector)) *CallHighlightQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.Join(joined).OnP(condition.P())
	})
	return _q
}

func (_q *CallHighlightQuery) LeftJoin(table string, on ...func(*sql.Selector)) *CallHighlightQuery {
	return _q.LeftJoinAs(table, "", on...)
}

func (_q *CallHighlightQuery) LeftJoinAs(table, alias string, on ...func(*sql.Selector)) *CallHighlightQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.LeftJoin(joined).OnP(condition.P())
	})
	return _q
}

// WithCount loads the number of neighbors of a non-unique edge into each returned
// CallHighlight, readable with Edges.Count. Only neighbors matching all predicates are
// counted, and a parent with no matching neighbor reports a present count of zero.
// At most one count is kept per edge: a later call for the same edge is ignored.
func (_q *CallHighlightQuery) WithCount[N, K any](edge ent.Relation[entity.CallHighlight, N, K], predicates ...ent.Predicate[N]) *CallHighlightQuery {
	for _, requested := range _q.withCounts {
		if requested.Name == edge.Ref().Name {
			return _q
		}
	}
	_q.withCounts = append(_q.withCounts, ent.CountEdge(edge, predicates...))
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CallHighlightQuery) Limit(limit int) *CallHighlightQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CallHighlightQuery) Offset(offset int) *CallHighlightQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CallHighlightQuery) Unique(unique bool) *CallHighlightQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CallHighlightQuery) Order(o ...ent.OrderOption[entity.CallHighlight]) *CallHighlightQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// Columns narrows the entity columns loaded by this query, including when it is used
// as an eager-loading query. The ID and any columns required to bind loaded edges are
// always included.
func (_q *CallHighlightQuery) Columns(columns ...ent.EntityColumn[entity.CallHighlight]) *CallHighlightQuery {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	for _, column := range columns {
		_q.ctx.AppendFieldOnce(column.Ref().Name)
	}
	return _q
}

// QueryCall chains the current query on the "call" edge.
func (_q *CallHighlightQuery) QueryCall() *CallQuery {
	query := (&CallClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(callhighlight.Table, callhighlight.FieldID, selector),
			sqlgraph.To(call.Table, call.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, callhighlight.CallTable, callhighlight.CallColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *CallHighlightQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(callhighlight.Table, callhighlight.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, callhighlight.UserTable, callhighlight.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CallHighlight entity from the query.
// Returns a *NotFoundError when no CallHighlight was found.
func (_q *CallHighlightQuery) First(ctx context.Context) (*CallHighlight, error) {
	nodes, err := _q.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{callhighlight.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CallHighlightQuery) FirstX(ctx context.Context) *CallHighlight {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CallHighlight ID from the query.
// Returns a *NotFoundError when no CallHighlight ID was found.
func (_q *CallHighlightQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{callhighlight.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CallHighlightQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CallHighlight entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CallHighlight entity is found.
// Returns a *NotFoundError when no CallHighlight entities are found.
func (_q *CallHighlightQuery) Only(ctx context.Context) (*CallHighlight, error) {
	nodes, err := _q.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{callhighlight.Label}
	default:
		return nil, &NotSingularError{callhighlight.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CallHighlightQuery) OnlyX(ctx context.Context) *CallHighlight {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CallHighlight ID in the query.
// Returns a *NotSingularError when more than one CallHighlight ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CallHighlightQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{callhighlight.Label}
	default:
		err = &NotSingularError{callhighlight.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CallHighlightQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CallHighlights.
func (_q *CallHighlightQuery) All(ctx context.Context) ([]*CallHighlight, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return _q.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (_q *CallHighlightQuery) AllX(ctx context.Context) []*CallHighlight {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CallHighlight IDs.
func (_q *CallHighlightQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	if ids, err = ent.Values(ctx, _q.Select(callhighlight.ID), callhighlight.ID); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CallHighlightQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CallHighlightQuery) Count(ctx context.Context) (int, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return _q.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CallHighlightQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CallHighlightQuery) Exist(ctx context.Context) (bool, error) {
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CallHighlightQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CallHighlightQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CallHighlightQuery) Clone() *CallHighlightQuery {
	if _q == nil {
		return nil
	}
	cloned := &CallHighlightQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]ent.OrderOption[entity.CallHighlight]{}, _q.order...),
		predicates: append([]ent.Predicate[entity.CallHighlight]{}, _q.predicates...),
		joins:      append([]func(*sql.Selector){}, _q.joins...),
		withCounts: append([]ent.EdgeCount{}, _q.withCounts...),

		withCall: _q.withCall.Clone(),
		withUser: _q.withUser.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}

	return cloned
}

// WithCall tells the query-builder to eager-load the nodes that are connected to
// the "call" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallHighlightQuery) WithCall(opts ...func(*CallQuery)) *CallHighlightQuery {
	query := (&CallClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCall = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallHighlightQuery) WithUser(opts ...func(*UserQuery)) *CallHighlightQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It can be combined with typed aggregate selections.
//
// Example:
//
//	var v []struct {
//		OffsetSeconds float64 `json:"offset_seconds,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CallHighlight.Query().
//		GroupBy(callhighlight.OffsetSeconds).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CallHighlightQuery) GroupBy(columns ...ent.EntityColumn[entity.CallHighlight]) *CallHighlightGroupBy {
	if len(columns) == 0 {
		panic("ent: GroupBy requires at least one column")
	}
	return &CallHighlightGroupBy{query: _q, columns: append([]ent.EntityColumn[entity.CallHighlight](nil), columns...)}
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OffsetSeconds float64 `json:"offset_seconds,omitempty"`
//	}
//
//	client.CallHighlight.Query().
//		Select(callhighlight.OffsetSeconds).
//		Scan(ctx, &v)
func (_q *CallHighlightQuery) Select(selections ...ent.Selection) *CallHighlightSelect {
	return &CallHighlightSelect{query: _q, selections: append([]ent.Selection(nil), selections...)}
}

// Aggregate returns a CallHighlightSelect configured with the given aggregations.
func (_q *CallHighlightQuery) Aggregate(selections ...ent.Selection) *CallHighlightSelect {
	return _q.Select(selections...)
}

func (_q *CallHighlightQuery) prepareQuery(ctx context.Context) error {
	for _, f := range _q.ctx.Fields {
		if !callhighlight.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CallHighlightQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CallHighlight, error) {
	var (
		nodes       = []*CallHighlight{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCall != nil,
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CallHighlight).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CallHighlight{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCall; query != nil {
		if err := _q.loadCall(ctx, query, nodes, nil,
			func(n *CallHighlight, e *Call) { n.Edges.Call = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CallHighlight, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}

	if len(_q.withCounts) > 0 {
		ids := make([]any, len(nodes))
		parents := make(map[uuid.UUID][]*CallHighlight, len(nodes))
		for index, node := range nodes {
			ids[index] = node.ID
			parents[node.ID] = append(parents[node.ID], node)
			if node.Edges.counts == nil {
				node.Edges.counts = make(map[string]int)
			}
			for _, edge := range _q.withCounts {
				node.Edges.counts[edge.Name] = 0
			}
		}
		selector := sql.Dialect(_q.driver.Dialect()).Select()

		for _, edge := range _q.withCounts {
			rows, err := sqlgraph.QuerySelector(ctx, _q.driver, edge.CountQuery(selector, ids...))
			if err != nil {
				return nil, err
			}
			for rows.Next() {
				values, err := (*CallHighlight)(nil).scanValues([]string{callhighlight.FieldID})
				if err != nil {
					rows.Close()
					return nil, err
				}
				var count int
				if err := rows.Scan(values[0], &count); err != nil {
					rows.Close()
					return nil, err
				}
				decoded := &CallHighlight{}
				if err := decoded.assignValues([]string{callhighlight.FieldID}, values); err != nil {
					rows.Close()
					return nil, err
				}
				for _, parent := range parents[decoded.ID] {
					parent.Edges.counts[edge.Name] = count
				}
			}
			if err := rows.Err(); err != nil {
				rows.Close()
				return nil, err
			}
			if err := rows.Close(); err != nil {
				return nil, err
			}
		}
	}

	return nodes, nil
}

func (_q *CallHighlightQuery) loadCall(ctx context.Context, query *CallQuery, nodes []*CallHighlight, init func(*CallHighlight), assign func(*CallHighlight, *Call)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CallHighlight)
	for i := range nodes {
		fk := nodes[i].CallID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(call.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CallHighlightQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CallHighlight, init func(*CallHighlight), assign func(*CallHighlight, *User)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CallHighlight)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CallHighlightQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CallHighlightQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(callhighlight.Table, callhighlight.Columns, sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, callhighlight.FieldID)
		for i := range fields {
			if fields[i] != callhighlight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCall != nil {
			_spec.Node.AddColumnOnce(callhighlight.FieldCallID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(callhighlight.FieldUserID)
		}
	}
	if predicates := _q.predicates; len(predicates) > 0 || len(_q.joins) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for _, join := range _q.joins {
				join(selector)
			}
			for i := range predicates {
				predicates[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CallHighlightQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(callhighlight.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = callhighlight.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, join := range _q.joins {
		join(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	for _, modifier := range _q.modifiers {
		modifier(selector)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CallHighlightQuery) ForUpdate(opts ...sql.LockOption) *CallHighlightQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CallHighlightQuery) ForShare(opts ...sql.LockOption) *CallHighlightQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries. It can be
// chained with the entity terminals (All, Count, ...) or with Select(...) for projections.
func (_q *CallHighlightQuery) Modify(modifiers ...func(s *sql.Selector)) *CallHighlightQuery {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q
}

// LimitedCount counts matching rows, stopping at limit.
func (_q *CallHighlightQuery) LimitedCount(ctx context.Context, limit int) (int, error) {
	if limit <= 0 {
		return 0, nil
	}
	clone := _q.Clone()
	clone.ctx.Limit = nil
	selector := clone.sqlQuery(ctx).SelectExpr(sql.Raw("1")).Limit(limit)
	query, args := selector.New().Select(sql.Count("*")).FromExpr(sql.ExprFunc(func(builder *sql.Builder) {
		builder.Wrap(func(builder *sql.Builder) {
			builder.Join(selector)
		}).WriteString(" AS ").Ident("limited_count")
	})).Query()
	rows, err := _q.driver.Query(dialect.WithStatement(ctx, &dialect.Statement{
		Kind:   dialect.StatementRead,
		Tables: []string{callhighlight.Table},
	}), query, args)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var count int
	if rows.Next() {
		if err := rows.Scan(&count); err != nil {
			return 0, err
		}
	}
	return count, rows.Err()
}

// CallHighlightGroupBy is the group-by builder for CallHighlight entities.
type CallHighlightGroupBy struct {
	query      *CallHighlightQuery
	columns    []ent.EntityColumn[entity.CallHighlight]
	aggregates []ent.Selection
}

func (_g *CallHighlightGroupBy) Aggregate(selections ...ent.Selection) *CallHighlightGroupBy {
	_g.aggregates = append(_g.aggregates, selections...)
	return _g
}

func (_g *CallHighlightGroupBy) Scan(ctx context.Context, v any) error {
	return _g.selectQuery().Scan(ctx, v)
}

func (_g *CallHighlightGroupBy) Rows(ctx context.Context) ([]*ent.Row, error) {
	return _g.selectQuery().Rows(ctx)
}

func (_g *CallHighlightGroupBy) selectQuery() *CallHighlightSelect {
	selections := make([]ent.Selection, 0, len(_g.columns)+len(_g.aggregates))
	for _, column := range _g.columns {
		selections = append(selections, column)
	}
	selected := _g.query.Select(append(selections, _g.aggregates...)...)
	selected.groups = _g.columns
	return selected
}

// CallHighlightSelect is the builder for selecting fields of CallHighlight entities.
type CallHighlightSelect struct {
	query      *CallHighlightQuery
	selections []ent.Selection
	groups     []ent.EntityColumn[entity.CallHighlight]
}

func (_s *CallHighlightSelect) Aggregate(selections ...ent.Selection) *CallHighlightSelect {
	_s.selections = append(_s.selections, selections...)
	return _s
}

func (_s *CallHighlightSelect) Row(ctx context.Context) (*ent.Row, error) {
	rows, err := _s.Rows(ctx)
	if err != nil {
		return nil, err
	}
	switch len(rows) {
	case 0:
		return nil, &NotFoundError{callhighlight.Label}
	case 1:
		return rows[0], nil
	default:
		return nil, &NotSingularError{callhighlight.Label}
	}
}

func (_s *CallHighlightSelect) sqlQuery(ctx context.Context) (*sql.Selector, error) {
	root := _s.query.Clone()
	root.ctx.Fields = nil
	for _, selection := range _s.selections {
		if column := selection.Ref(); column.Name != "" && (column.Table == "" || column.Table == callhighlight.Table) {
			root.ctx.AppendFieldOnce(column.Name)
		}
	}
	if err := root.prepareQuery(ctx); err != nil {
		return nil, err
	}
	root.modifiers = nil
	selector := root.sqlQuery(ctx)
	if len(_s.selections) > 0 {
		ent.SelectColumns(selector, _s.selections...)
	}
	for _, column := range _s.groups {
		reference := column.Ref()
		if reference.Table == "" || reference.Table == selector.TableName() {
			selector.GroupBy(selector.C(reference.Name))
		} else {
			selector.GroupBy(sql.Dialect(selector.Dialect()).Table(reference.Table).C(reference.Name))
		}
	}
	for _, modifier := range _s.query.modifiers {
		modifier(selector)
	}
	return selector, selector.Err()
}

func (_s *CallHighlightSelect) Scan(ctx context.Context, value any) error {
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, value)
}

func (_s *CallHighlightSelect) Rows(ctx context.Context) ([]*ent.Row, error) {
	if len(_s.selections) == 0 {
		return nil, errors.New("ent: Rows requires explicit selections")
	}
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	columns, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	if len(columns) != len(_s.selections) {
		return nil, fmt.Errorf("ent: projection column count %d differs from selection count %d", len(columns), len(_s.selections))
	}
	result := make([]*ent.Row, 0)
	for rows.Next() {
		row, destinations := ent.NewRow(_s.selections)
		if err := rows.Scan(destinations...); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return result, nil
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CallHighlightSelect) Modify(modifiers ...func(s *sql.Selector)) *CallHighlightSelect {
	_s.query.modifiers = append(_s.query.modifiers, modifiers...)
	return _s
}
