// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/callhighlight"
	"cameo/internal/ent/entity"
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type CallHighlightUpdate struct {
	config
	mutation  *CallHighlightMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CallHighlightUpdate) Set[T any](column ent.ColumnOf[entity.CallHighlight, T], value T) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CallHighlightUpdate) SetOptional[T any](column ent.ColumnOf[entity.CallHighlight, T], value ent.Option[T]) *CallHighlightUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CallHighlightUpdate) SetExpr[T any](column ent.ColumnOf[entity.CallHighlight, T], value ent.Expr[T]) *CallHighlightUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case callhighlight.FieldOffsetSeconds:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of CallHighlight is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CallHighlightUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.CallHighlight, N, K], id K) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CallHighlightUpdate) AddIDs[N, K any](edge ent.Relation[entity.CallHighlight, N, K], ids ...K) *CallHighlightUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallHighlightUpdate) Mutation() *CallHighlightMutation { return b.mutation }

func (b *CallHighlightUpdate) Patch() *CallHighlightPatch { return b.mutation.patch }
func (b *CallHighlightUpdate) Apply(p CallHighlightPatch) *CallHighlightUpdate {
	b.mutation.patch.apply(p)
	return b
}
func (b *CallHighlightUpdate) Add[T ent.Number](column ent.ColumnOf[entity.CallHighlight, T], delta T) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CallHighlightUpdate) Append[T any](column ent.ColumnOf[entity.CallHighlight, T], values T) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CallHighlightUpdate) Clear[T any](column ent.ColumnOf[entity.CallHighlight, T]) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CallHighlightUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.CallHighlight, N, K], ids ...K) *CallHighlightUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallHighlightUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.CallHighlight, N, K]) *CallHighlightUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CallHighlightUpdate) Where(predicates ...ent.Predicate[entity.CallHighlight]) *CallHighlightUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *CallHighlightUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *CallHighlightUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CallHighlightUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallHighlightUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CallHighlightUpdate) Returning(ctx context.Context) ([]*CallHighlight, error) {
	nodes := make([]*CallHighlight, 0)
	b.returning = &sqlgraph.Returning{Columns: callhighlight.Columns, Scan: func(rows dialect.Rows) error {
		_node := &CallHighlight{config: b.config}
		values, err := _node.scanValues(callhighlight.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(callhighlight.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *CallHighlightUpdate) defaults() error {

	return nil
}

func (b *CallHighlightUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.OffsetSeconds.IsNull() {
		return &ValidationError{Name: "offset_seconds", err: errors.New(`ent: field "CallHighlight.offset_seconds" is not nullable`)}
	}

	if v, ok := b.mutation.patch.OffsetSeconds.Get(); ok && b.mutation.patch.expressions[callhighlight.FieldOffsetSeconds] == nil {

		if err := callhighlight.OffsetSecondsValidator(v); err != nil {
			return &ValidationError{Name: "offset_seconds", err: fmt.Errorf(`ent: validator failed for field "CallHighlight.offset_seconds": %w`, err)}
		}

	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CallHighlightUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CallHighlightUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CallHighlightUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(callhighlight.Table, callhighlight.Columns, sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.OffsetSeconds.Get(); ok {
		_spec.SetField(callhighlight.FieldOffsetSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.OffsetSecondsAdd.Get(); ok {
		_spec.AddField(callhighlight.FieldOffsetSeconds, field.TypeFloat64, value)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{callhighlight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type CallHighlightUpdateOne struct {
	config
	mutation *CallHighlightMutation
	err      error

	fields []string
	old    *CallHighlight

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CallHighlightUpdateOne) Set[T any](column ent.ColumnOf[entity.CallHighlight, T], value T) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CallHighlightUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.CallHighlight, T], value ent.Option[T]) *CallHighlightUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CallHighlightUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.CallHighlight, T], value ent.Expr[T]) *CallHighlightUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case callhighlight.FieldOffsetSeconds:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of CallHighlight is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CallHighlightUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.CallHighlight, N, K], id K) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CallHighlightUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.CallHighlight, N, K], ids ...K) *CallHighlightUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallHighlightUpdateOne) Mutation() *CallHighlightMutation { return b.mutation }

func (b *CallHighlightUpdateOne) Patch() *CallHighlightPatch { return b.mutation.patch }
func (b *CallHighlightUpdateOne) Apply(p CallHighlightPatch) *CallHighlightUpdateOne {
	b.mutation.patch.apply(p)
	return b
}
func (b *CallHighlightUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.CallHighlight, T], delta T) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CallHighlightUpdateOne) Append[T any](column ent.ColumnOf[entity.CallHighlight, T], values T) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CallHighlightUpdateOne) Clear[T any](column ent.ColumnOf[entity.CallHighlight, T]) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CallHighlightUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.CallHighlight, N, K], ids ...K) *CallHighlightUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallHighlightUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.CallHighlight, N, K]) *CallHighlightUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CallHighlightUpdateOne) Where(predicates ...ent.Predicate[entity.CallHighlight]) *CallHighlightUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *CallHighlightUpdateOne) Save(ctx context.Context) (*CallHighlight, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CallHighlightUpdateOne) SaveX(ctx context.Context) *CallHighlight {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CallHighlightUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallHighlightUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// Columns narrows the entity columns returned by the update. The ID is always included.
func (b *CallHighlightUpdateOne) Columns(columns ...ent.EntityColumn[entity.CallHighlight]) *CallHighlightUpdateOne {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *CallHighlightUpdateOne) SaveOld(ctx context.Context) (old *CallHighlight, updated *CallHighlight, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &CallHighlight{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *CallHighlightUpdateOne) defaults() error {

	return nil
}

func (b *CallHighlightUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.OffsetSeconds.IsNull() {
		return &ValidationError{Name: "offset_seconds", err: errors.New(`ent: field "CallHighlight.offset_seconds" is not nullable`)}
	}

	if v, ok := b.mutation.patch.OffsetSeconds.Get(); ok && b.mutation.patch.expressions[callhighlight.FieldOffsetSeconds] == nil {

		if err := callhighlight.OffsetSecondsValidator(v); err != nil {
			return &ValidationError{Name: "offset_seconds", err: fmt.Errorf(`ent: validator failed for field "CallHighlight.offset_seconds": %w`, err)}
		}

	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CallHighlightUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CallHighlightUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CallHighlightUpdateOne) sqlSave(ctx context.Context) (_node *CallHighlight, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(callhighlight.Table, callhighlight.Columns, sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CallHighlight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, callhighlight.FieldID)
		for _, f := range fields {
			if !callhighlight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != callhighlight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.OffsetSeconds.Get(); ok {
		_spec.SetField(callhighlight.FieldOffsetSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.OffsetSecondsAdd.Get(); ok {
		_spec.AddField(callhighlight.FieldOffsetSeconds, field.TypeFloat64, value)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &CallHighlight{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{callhighlight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
