// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/callhighlight"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/dialect/sql/sqljson"
	"github.com/neko-sc/ent/schema/field"
)

type CallUpdate struct {
	config
	mutation  *CallMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CallUpdate) Set[T any](column ent.ColumnOf[entity.Call, T], value T) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CallUpdate) SetOptional[T any](column ent.ColumnOf[entity.Call, T], value ent.Option[T]) *CallUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CallUpdate) SetExpr[T any](column ent.ColumnOf[entity.Call, T], value ent.Expr[T]) *CallUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case call.FieldStatus:

	case call.FieldTranscriptStatus:

	case call.FieldTitle:

	case call.FieldSummary:

	case call.FieldRecordingKey:

	case call.FieldRecordingBytes:

	case call.FieldFavoritedBy:

	case call.FieldStartedAt:

	case call.FieldEndedAt:

	case call.FieldTranscript:

	case call.FieldCoupleID:

	case call.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CallUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Call, N, K], id K) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CallUpdate) AddIDs[N, K any](edge ent.Relation[entity.Call, N, K], ids ...K) *CallUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallUpdate) Mutation() *CallMutation { return b.mutation }

func (b *CallUpdate) Patch() *CallPatch             { return b.mutation.patch }
func (b *CallUpdate) Apply(p CallPatch) *CallUpdate { b.mutation.patch.apply(p); return b }
func (b *CallUpdate) Add[T ent.Number](column ent.ColumnOf[entity.Call, T], delta T) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CallUpdate) Append[T any](column ent.ColumnOf[entity.Call, T], values T) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CallUpdate) Clear[T any](column ent.ColumnOf[entity.Call, T]) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CallUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.Call, N, K], ids ...K) *CallUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.Call, N, K]) *CallUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CallUpdate) Where(predicates ...ent.Predicate[entity.Call]) *CallUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *CallUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *CallUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CallUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CallUpdate) Returning(ctx context.Context) ([]*Call, error) {
	nodes := make([]*Call, 0)
	b.returning = &sqlgraph.Returning{Columns: call.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Call{config: b.config}
		values, err := _node.scanValues(call.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(call.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *CallUpdate) defaults() error {

	if b.mutation.patch.UpdatedAt.IsUnset() && b.mutation.patch.expressions[call.FieldUpdatedAt] == nil {
		if call.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized call.UpdateDefaultUpdatedAt")
		}
		b.mutation.patch.UpdatedAt = ent.Some(call.UpdateDefaultUpdatedAt())
	}

	return nil
}

func (b *CallUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Call.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[call.FieldStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Call.status": %w`, err)}
		}

	}

	if b.mutation.patch.TranscriptStatus.IsNull() {
		return &ValidationError{Name: "transcript_status", err: errors.New(`ent: field "Call.transcript_status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.TranscriptStatus.Get(); ok && b.mutation.patch.expressions[call.FieldTranscriptStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "transcript_status", err: fmt.Errorf(`ent: validator failed for field "Call.transcript_status": %w`, err)}
		}

	}

	if b.mutation.patch.RecordingBytes.IsNull() {
		return &ValidationError{Name: "recording_bytes", err: errors.New(`ent: field "Call.recording_bytes" is not nullable`)}
	}

	if b.mutation.patch.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Call.favorited_by" is not nullable`)}
	}

	if b.mutation.patch.CoupleID.IsNull() {
		return &ValidationError{Name: "couple_id", err: errors.New(`ent: field "Call.couple_id" is not nullable`)}
	}

	if b.mutation.patch.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Call.updated_at" is not nullable`)}
	}

	if b.mutation.patch.CoupleID.IsNull() {
		return &ValidationError{Name: "couple", err: errors.New(`ent: clearing required edge "Call.couple"`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CallUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CallUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CallUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(call.Table, call.Columns, sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(call.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.StatusAdd.Get(); ok {
		_spec.AddField(call.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.TranscriptStatus.Get(); ok {
		_spec.SetField(call.FieldTranscriptStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.TranscriptStatusAdd.Get(); ok {
		_spec.AddField(call.FieldTranscriptStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.Title.Get(); ok {
		_spec.SetField(call.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.patch.Title.IsNull() {
		_spec.ClearField(call.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.patch.Summary.Get(); ok {
		_spec.SetField(call.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.patch.Summary.IsNull() {
		_spec.ClearField(call.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.patch.RecordingKey.Get(); ok {
		_spec.SetField(call.FieldRecordingKey, field.TypeString, value)
	}
	if _u.mutation.patch.RecordingKey.IsNull() {
		_spec.ClearField(call.FieldRecordingKey, field.TypeString)
	}
	if value, ok := _u.mutation.patch.RecordingBytes.Get(); ok {
		_spec.SetField(call.FieldRecordingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.RecordingBytesAdd.Get(); ok {
		_spec.AddField(call.FieldRecordingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.FavoritedBy.Get(); ok {
		_spec.SetField(call.FieldFavoritedBy, field.TypeArray, value)
	}
	if value, ok := _u.mutation.patch.StartedAt.Get(); ok {
		_spec.SetField(call.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.StartedAt.IsNull() {
		_spec.ClearField(call.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.EndedAt.Get(); ok {
		_spec.SetField(call.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.EndedAt.IsNull() {
		_spec.ClearField(call.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.Transcript.Get(); ok {
		_spec.SetField(call.FieldTranscript, field.TypeJSON, value)
	}
	if value := _u.mutation.patch.TranscriptAppend; len(value) > 0 {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, call.FieldTranscript, value)
		})
	}
	if _u.mutation.patch.Transcript.IsNull() {
		_spec.ClearField(call.FieldTranscript, field.TypeJSON)
	}
	if value, ok := _u.mutation.patch.UpdatedAt.Get(); ok {
		_spec.SetField(call.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.Highlights.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Highlights.Remove; len(nodes) > 0 && !_u.mutation.patch.Highlights.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.highlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Photos.Remove; len(nodes) > 0 && !_u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.photosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.CoupleID.IsNull() || _u.mutation.patch.clearedEdges[call.EdgeCouple] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CoupleTable,
			Columns: []string{call.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.coupleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CoupleTable,
			Columns: []string{call.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type CallUpdateOne struct {
	config
	mutation *CallMutation
	err      error

	fields []string
	old    *Call

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CallUpdateOne) Set[T any](column ent.ColumnOf[entity.Call, T], value T) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CallUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.Call, T], value ent.Option[T]) *CallUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CallUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.Call, T], value ent.Expr[T]) *CallUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case call.FieldStatus:

	case call.FieldTranscriptStatus:

	case call.FieldTitle:

	case call.FieldSummary:

	case call.FieldRecordingKey:

	case call.FieldRecordingBytes:

	case call.FieldFavoritedBy:

	case call.FieldStartedAt:

	case call.FieldEndedAt:

	case call.FieldTranscript:

	case call.FieldCoupleID:

	case call.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CallUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.Call, N, K], id K) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CallUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.Call, N, K], ids ...K) *CallUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallUpdateOne) Mutation() *CallMutation { return b.mutation }

func (b *CallUpdateOne) Patch() *CallPatch                { return b.mutation.patch }
func (b *CallUpdateOne) Apply(p CallPatch) *CallUpdateOne { b.mutation.patch.apply(p); return b }
func (b *CallUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.Call, T], delta T) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CallUpdateOne) Append[T any](column ent.ColumnOf[entity.Call, T], values T) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CallUpdateOne) Clear[T any](column ent.ColumnOf[entity.Call, T]) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CallUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.Call, N, K], ids ...K) *CallUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.Call, N, K]) *CallUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CallUpdateOne) Where(predicates ...ent.Predicate[entity.Call]) *CallUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *CallUpdateOne) Save(ctx context.Context) (*Call, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CallUpdateOne) SaveX(ctx context.Context) *Call {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CallUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// Columns narrows the entity columns returned by the update. The ID is always included.
func (b *CallUpdateOne) Columns(columns ...ent.EntityColumn[entity.Call]) *CallUpdateOne {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *CallUpdateOne) SaveOld(ctx context.Context) (old *Call, updated *Call, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &Call{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *CallUpdateOne) defaults() error {

	if b.mutation.patch.UpdatedAt.IsUnset() && b.mutation.patch.expressions[call.FieldUpdatedAt] == nil {
		if call.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized call.UpdateDefaultUpdatedAt")
		}
		b.mutation.patch.UpdatedAt = ent.Some(call.UpdateDefaultUpdatedAt())
	}

	return nil
}

func (b *CallUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Call.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[call.FieldStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Call.status": %w`, err)}
		}

	}

	if b.mutation.patch.TranscriptStatus.IsNull() {
		return &ValidationError{Name: "transcript_status", err: errors.New(`ent: field "Call.transcript_status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.TranscriptStatus.Get(); ok && b.mutation.patch.expressions[call.FieldTranscriptStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "transcript_status", err: fmt.Errorf(`ent: validator failed for field "Call.transcript_status": %w`, err)}
		}

	}

	if b.mutation.patch.RecordingBytes.IsNull() {
		return &ValidationError{Name: "recording_bytes", err: errors.New(`ent: field "Call.recording_bytes" is not nullable`)}
	}

	if b.mutation.patch.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Call.favorited_by" is not nullable`)}
	}

	if b.mutation.patch.CoupleID.IsNull() {
		return &ValidationError{Name: "couple_id", err: errors.New(`ent: field "Call.couple_id" is not nullable`)}
	}

	if b.mutation.patch.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Call.updated_at" is not nullable`)}
	}

	if b.mutation.patch.CoupleID.IsNull() {
		return &ValidationError{Name: "couple", err: errors.New(`ent: clearing required edge "Call.couple"`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CallUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CallUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CallUpdateOne) sqlSave(ctx context.Context) (_node *Call, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(call.Table, call.Columns, sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Call.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, call.FieldID)
		for _, f := range fields {
			if !call.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != call.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(call.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.StatusAdd.Get(); ok {
		_spec.AddField(call.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.TranscriptStatus.Get(); ok {
		_spec.SetField(call.FieldTranscriptStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.TranscriptStatusAdd.Get(); ok {
		_spec.AddField(call.FieldTranscriptStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.Title.Get(); ok {
		_spec.SetField(call.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.patch.Title.IsNull() {
		_spec.ClearField(call.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.patch.Summary.Get(); ok {
		_spec.SetField(call.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.patch.Summary.IsNull() {
		_spec.ClearField(call.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.patch.RecordingKey.Get(); ok {
		_spec.SetField(call.FieldRecordingKey, field.TypeString, value)
	}
	if _u.mutation.patch.RecordingKey.IsNull() {
		_spec.ClearField(call.FieldRecordingKey, field.TypeString)
	}
	if value, ok := _u.mutation.patch.RecordingBytes.Get(); ok {
		_spec.SetField(call.FieldRecordingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.RecordingBytesAdd.Get(); ok {
		_spec.AddField(call.FieldRecordingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.FavoritedBy.Get(); ok {
		_spec.SetField(call.FieldFavoritedBy, field.TypeArray, value)
	}
	if value, ok := _u.mutation.patch.StartedAt.Get(); ok {
		_spec.SetField(call.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.StartedAt.IsNull() {
		_spec.ClearField(call.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.EndedAt.Get(); ok {
		_spec.SetField(call.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.EndedAt.IsNull() {
		_spec.ClearField(call.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.Transcript.Get(); ok {
		_spec.SetField(call.FieldTranscript, field.TypeJSON, value)
	}
	if value := _u.mutation.patch.TranscriptAppend; len(value) > 0 {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, call.FieldTranscript, value)
		})
	}
	if _u.mutation.patch.Transcript.IsNull() {
		_spec.ClearField(call.FieldTranscript, field.TypeJSON)
	}
	if value, ok := _u.mutation.patch.UpdatedAt.Get(); ok {
		_spec.SetField(call.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.Highlights.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Highlights.Remove; len(nodes) > 0 && !_u.mutation.patch.Highlights.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.highlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Photos.Remove; len(nodes) > 0 && !_u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.photosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.CoupleID.IsNull() || _u.mutation.patch.clearedEdges[call.EdgeCouple] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CoupleTable,
			Columns: []string{call.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.coupleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CoupleTable,
			Columns: []string{call.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &Call{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
