// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/callhighlight"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"cameo/internal/ent/user"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

// CallQuery is the builder for querying Call entities.
type CallQuery struct {
	config
	ctx        *QueryContext
	order      []ent.OrderOption[entity.Call]
	joins      []func(*sql.Selector)
	withCounts []ent.EdgeCount

	predicates     []ent.Predicate[entity.Call]
	withHighlights *CallHighlightQuery
	withPhotos     *PhotoQuery
	withCouple     *CoupleQuery
	withCaller     *UserQuery
	withCallee     *UserQuery
	modifiers      []func(*sql.Selector)

	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CallQuery builder.
func (_q *CallQuery) Where(predicates ...ent.Predicate[entity.Call]) *CallQuery {
	_q.predicates = append(_q.predicates, predicates...)
	return _q
}

func (_q *CallQuery) WhereP(predicates ...func(*sql.Selector)) *CallQuery {
	for _, predicate := range predicates {
		_q.predicates = append(_q.predicates, predicate)
	}
	return _q
}

func (_q *CallQuery) Join(table string, on ...func(*sql.Selector)) *CallQuery {
	return _q.JoinAs(table, "", on...)
}

func (_q *CallQuery) JoinAs(table, alias string, on ...func(*sql.Selector)) *CallQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.Join(joined).OnP(condition.P())
	})
	return _q
}

func (_q *CallQuery) LeftJoin(table string, on ...func(*sql.Selector)) *CallQuery {
	return _q.LeftJoinAs(table, "", on...)
}

func (_q *CallQuery) LeftJoinAs(table, alias string, on ...func(*sql.Selector)) *CallQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.LeftJoin(joined).OnP(condition.P())
	})
	return _q
}

// WithCount loads the number of neighbors of a non-unique edge into each returned
// Call, readable with Edges.Count. Only neighbors matching all predicates are
// counted, and a parent with no matching neighbor reports a present count of zero.
// At most one count is kept per edge: a later call for the same edge is ignored.
func (_q *CallQuery) WithCount[N, K any](edge ent.Relation[entity.Call, N, K], predicates ...ent.Predicate[N]) *CallQuery {
	for _, requested := range _q.withCounts {
		if requested.Name == edge.Ref().Name {
			return _q
		}
	}
	_q.withCounts = append(_q.withCounts, ent.CountEdge(edge, predicates...))
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CallQuery) Limit(limit int) *CallQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CallQuery) Offset(offset int) *CallQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CallQuery) Unique(unique bool) *CallQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CallQuery) Order(o ...ent.OrderOption[entity.Call]) *CallQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// Columns narrows the entity columns loaded by this query, including when it is used
// as an eager-loading query. The ID and any columns required to bind loaded edges are
// always included.
func (_q *CallQuery) Columns(columns ...ent.EntityColumn[entity.Call]) *CallQuery {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	for _, column := range columns {
		_q.ctx.AppendFieldOnce(column.Ref().Name)
	}
	return _q
}

// QueryHighlights chains the current query on the "highlights" edge.
func (_q *CallQuery) QueryHighlights() *CallHighlightQuery {
	query := (&CallHighlightClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(call.Table, call.FieldID, selector),
			sqlgraph.To(callhighlight.Table, callhighlight.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, call.HighlightsTable, call.HighlightsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPhotos chains the current query on the "photos" edge.
func (_q *CallQuery) QueryPhotos() *PhotoQuery {
	query := (&PhotoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(call.Table, call.FieldID, selector),
			sqlgraph.To(photo.Table, photo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, call.PhotosTable, call.PhotosColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCouple chains the current query on the "couple" edge.
func (_q *CallQuery) QueryCouple() *CoupleQuery {
	query := (&CoupleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(call.Table, call.FieldID, selector),
			sqlgraph.To(couple.Table, couple.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, call.CoupleTable, call.CoupleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCaller chains the current query on the "caller" edge.
func (_q *CallQuery) QueryCaller() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(call.Table, call.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, call.CallerTable, call.CallerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCallee chains the current query on the "callee" edge.
func (_q *CallQuery) QueryCallee() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(call.Table, call.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, call.CalleeTable, call.CalleeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Call entity from the query.
// Returns a *NotFoundError when no Call was found.
func (_q *CallQuery) First(ctx context.Context) (*Call, error) {
	nodes, err := _q.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{call.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CallQuery) FirstX(ctx context.Context) *Call {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Call ID from the query.
// Returns a *NotFoundError when no Call ID was found.
func (_q *CallQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{call.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CallQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Call entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Call entity is found.
// Returns a *NotFoundError when no Call entities are found.
func (_q *CallQuery) Only(ctx context.Context) (*Call, error) {
	nodes, err := _q.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{call.Label}
	default:
		return nil, &NotSingularError{call.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CallQuery) OnlyX(ctx context.Context) *Call {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Call ID in the query.
// Returns a *NotSingularError when more than one Call ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CallQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{call.Label}
	default:
		err = &NotSingularError{call.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CallQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Calls.
func (_q *CallQuery) All(ctx context.Context) ([]*Call, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return _q.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (_q *CallQuery) AllX(ctx context.Context) []*Call {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Call IDs.
func (_q *CallQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	if ids, err = ent.Values(ctx, _q.Select(call.ID), call.ID); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CallQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CallQuery) Count(ctx context.Context) (int, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return _q.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CallQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CallQuery) Exist(ctx context.Context) (bool, error) {
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CallQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CallQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CallQuery) Clone() *CallQuery {
	if _q == nil {
		return nil
	}
	cloned := &CallQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]ent.OrderOption[entity.Call]{}, _q.order...),
		predicates: append([]ent.Predicate[entity.Call]{}, _q.predicates...),
		joins:      append([]func(*sql.Selector){}, _q.joins...),
		withCounts: append([]ent.EdgeCount{}, _q.withCounts...),

		withHighlights: _q.withHighlights.Clone(),
		withPhotos:     _q.withPhotos.Clone(),
		withCouple:     _q.withCouple.Clone(),
		withCaller:     _q.withCaller.Clone(),
		withCallee:     _q.withCallee.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}

	return cloned
}

// WithHighlights tells the query-builder to eager-load the nodes that are connected to
// the "highlights" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallQuery) WithHighlights(opts ...func(*CallHighlightQuery)) *CallQuery {
	query := (&CallHighlightClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHighlights = query
	return _q
}

// WithPhotos tells the query-builder to eager-load the nodes that are connected to
// the "photos" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallQuery) WithPhotos(opts ...func(*PhotoQuery)) *CallQuery {
	query := (&PhotoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPhotos = query
	return _q
}

// WithCouple tells the query-builder to eager-load the nodes that are connected to
// the "couple" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallQuery) WithCouple(opts ...func(*CoupleQuery)) *CallQuery {
	query := (&CoupleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCouple = query
	return _q
}

// WithCaller tells the query-builder to eager-load the nodes that are connected to
// the "caller" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallQuery) WithCaller(opts ...func(*UserQuery)) *CallQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCaller = query
	return _q
}

// WithCallee tells the query-builder to eager-load the nodes that are connected to
// the "callee" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallQuery) WithCallee(opts ...func(*UserQuery)) *CallQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCallee = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It can be combined with typed aggregate selections.
//
// Example:
//
//	var v []struct {
//		Status call2.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Call.Query().
//		GroupBy(call.Status).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CallQuery) GroupBy(columns ...ent.EntityColumn[entity.Call]) *CallGroupBy {
	if len(columns) == 0 {
		panic("ent: GroupBy requires at least one column")
	}
	return &CallGroupBy{query: _q, columns: append([]ent.EntityColumn[entity.Call](nil), columns...)}
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status call2.Status `json:"status,omitempty"`
//	}
//
//	client.Call.Query().
//		Select(call.Status).
//		Scan(ctx, &v)
func (_q *CallQuery) Select(selections ...ent.Selection) *CallSelect {
	return &CallSelect{query: _q, selections: append([]ent.Selection(nil), selections...)}
}

// Aggregate returns a CallSelect configured with the given aggregations.
func (_q *CallQuery) Aggregate(selections ...ent.Selection) *CallSelect {
	return _q.Select(selections...)
}

func (_q *CallQuery) prepareQuery(ctx context.Context) error {
	for _, f := range _q.ctx.Fields {
		if !call.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CallQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Call, error) {
	var (
		nodes       = []*Call{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withHighlights != nil,
			_q.withPhotos != nil,
			_q.withCouple != nil,
			_q.withCaller != nil,
			_q.withCallee != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Call).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Call{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHighlights; query != nil {
		if err := _q.loadHighlights(ctx, query, nodes,
			func(n *Call) { n.Edges.Highlights = []*CallHighlight{} },
			func(n *Call, e *CallHighlight) { n.Edges.Highlights = append(n.Edges.Highlights, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPhotos; query != nil {
		if err := _q.loadPhotos(ctx, query, nodes,
			func(n *Call) { n.Edges.Photos = []*Photo{} },
			func(n *Call, e *Photo) { n.Edges.Photos = append(n.Edges.Photos, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCouple; query != nil {
		if err := _q.loadCouple(ctx, query, nodes, nil,
			func(n *Call, e *Couple) { n.Edges.Couple = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCaller; query != nil {
		if err := _q.loadCaller(ctx, query, nodes, nil,
			func(n *Call, e *User) { n.Edges.Caller = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCallee; query != nil {
		if err := _q.loadCallee(ctx, query, nodes, nil,
			func(n *Call, e *User) { n.Edges.Callee = e }); err != nil {
			return nil, err
		}
	}

	if len(_q.withCounts) > 0 {
		ids := make([]any, len(nodes))
		parents := make(map[uuid.UUID][]*Call, len(nodes))
		for index, node := range nodes {
			ids[index] = node.ID
			parents[node.ID] = append(parents[node.ID], node)
			if node.Edges.counts == nil {
				node.Edges.counts = make(map[string]int)
			}
			for _, edge := range _q.withCounts {
				node.Edges.counts[edge.Name] = 0
			}
		}
		selector := sql.Dialect(_q.driver.Dialect()).Select()

		for _, edge := range _q.withCounts {
			rows, err := sqlgraph.QuerySelector(ctx, _q.driver, edge.CountQuery(selector, ids...))
			if err != nil {
				return nil, err
			}
			for rows.Next() {
				values, err := (*Call)(nil).scanValues([]string{call.FieldID})
				if err != nil {
					rows.Close()
					return nil, err
				}
				var count int
				if err := rows.Scan(values[0], &count); err != nil {
					rows.Close()
					return nil, err
				}
				decoded := &Call{}
				if err := decoded.assignValues([]string{call.FieldID}, values); err != nil {
					rows.Close()
					return nil, err
				}
				for _, parent := range parents[decoded.ID] {
					parent.Edges.counts[edge.Name] = count
				}
			}
			if err := rows.Err(); err != nil {
				rows.Close()
				return nil, err
			}
			if err := rows.Close(); err != nil {
				return nil, err
			}
		}
	}

	return nodes, nil
}

func (_q *CallQuery) loadHighlights(ctx context.Context, query *CallHighlightQuery, nodes []*Call, init func(*Call), assign func(*Call, *CallHighlight)) error {
	query = query.Clone()

	if query.ctx.Limit != nil || query.ctx.Offset != nil {
		limit, offset := -1, 0
		if query.ctx.Limit != nil {
			limit = *query.ctx.Limit
		}
		if query.ctx.Offset != nil {
			offset = *query.ctx.Offset
		}
		query.ctx.Limit, query.ctx.Offset = nil, nil
		query.modifiers = append(query.modifiers, func(selector *sql.Selector) {

			partition := selector.C(call.HighlightsColumn)

			(&sqlgraph.NeighborsLimit{RowNumber: "ent_row_number", DefaultOrderField: callhighlight.FieldID, Offset: offset}).Modifier(partition, limit)(selector)
		})
	}

	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Call)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(callhighlight.FieldCallID)
	}
	query.Where(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(call.HighlightsColumn), fks...))
	})
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CallID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "call_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CallQuery) loadPhotos(ctx context.Context, query *PhotoQuery, nodes []*Call, init func(*Call), assign func(*Call, *Photo)) error {
	query = query.Clone()

	if query.ctx.Limit != nil || query.ctx.Offset != nil {
		limit, offset := -1, 0
		if query.ctx.Limit != nil {
			limit = *query.ctx.Limit
		}
		if query.ctx.Offset != nil {
			offset = *query.ctx.Offset
		}
		query.ctx.Limit, query.ctx.Offset = nil, nil
		query.modifiers = append(query.modifiers, func(selector *sql.Selector) {

			partition := selector.C(call.PhotosColumn)

			(&sqlgraph.NeighborsLimit{RowNumber: "ent_row_number", DefaultOrderField: photo.FieldID, Offset: offset}).Modifier(partition, limit)(selector)
		})
	}

	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Call)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(photo.FieldCallID)
	}
	query.Where(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(call.PhotosColumn), fks...))
	})
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CallID
		if fk == nil {
			return fmt.Errorf(`foreign-key "call_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "call_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CallQuery) loadCouple(ctx context.Context, query *CoupleQuery, nodes []*Call, init func(*Call), assign func(*Call, *Couple)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Call)
	for i := range nodes {
		fk := nodes[i].CoupleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(couple.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "couple_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CallQuery) loadCaller(ctx context.Context, query *UserQuery, nodes []*Call, init func(*Call), assign func(*Call, *User)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Call)
	for i := range nodes {
		fk := nodes[i].CallerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "caller_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CallQuery) loadCallee(ctx context.Context, query *UserQuery, nodes []*Call, init func(*Call), assign func(*Call, *User)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Call)
	for i := range nodes {
		fk := nodes[i].CalleeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "callee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CallQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CallQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(call.Table, call.Columns, sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, call.FieldID)
		for i := range fields {
			if fields[i] != call.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCouple != nil {
			_spec.Node.AddColumnOnce(call.FieldCoupleID)
		}
		if _q.withCaller != nil {
			_spec.Node.AddColumnOnce(call.FieldCallerID)
		}
		if _q.withCallee != nil {
			_spec.Node.AddColumnOnce(call.FieldCalleeID)
		}
	}
	if predicates := _q.predicates; len(predicates) > 0 || len(_q.joins) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for _, join := range _q.joins {
				join(selector)
			}
			for i := range predicates {
				predicates[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CallQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(call.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = call.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, join := range _q.joins {
		join(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	for _, modifier := range _q.modifiers {
		modifier(selector)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CallQuery) ForUpdate(opts ...sql.LockOption) *CallQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CallQuery) ForShare(opts ...sql.LockOption) *CallQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries. It can be
// chained with the entity terminals (All, Count, ...) or with Select(...) for projections.
func (_q *CallQuery) Modify(modifiers ...func(s *sql.Selector)) *CallQuery {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q
}

// LimitedCount counts matching rows, stopping at limit.
func (_q *CallQuery) LimitedCount(ctx context.Context, limit int) (int, error) {
	if limit <= 0 {
		return 0, nil
	}
	clone := _q.Clone()
	clone.ctx.Limit = nil
	selector := clone.sqlQuery(ctx).SelectExpr(sql.Raw("1")).Limit(limit)
	query, args := selector.New().Select(sql.Count("*")).FromExpr(sql.ExprFunc(func(builder *sql.Builder) {
		builder.Wrap(func(builder *sql.Builder) {
			builder.Join(selector)
		}).WriteString(" AS ").Ident("limited_count")
	})).Query()
	rows, err := _q.driver.Query(dialect.WithStatement(ctx, &dialect.Statement{
		Kind:   dialect.StatementRead,
		Tables: []string{call.Table},
	}), query, args)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var count int
	if rows.Next() {
		if err := rows.Scan(&count); err != nil {
			return 0, err
		}
	}
	return count, rows.Err()
}

// CallGroupBy is the group-by builder for Call entities.
type CallGroupBy struct {
	query      *CallQuery
	columns    []ent.EntityColumn[entity.Call]
	aggregates []ent.Selection
}

func (_g *CallGroupBy) Aggregate(selections ...ent.Selection) *CallGroupBy {
	_g.aggregates = append(_g.aggregates, selections...)
	return _g
}

func (_g *CallGroupBy) Scan(ctx context.Context, v any) error {
	return _g.selectQuery().Scan(ctx, v)
}

func (_g *CallGroupBy) Rows(ctx context.Context) ([]*ent.Row, error) {
	return _g.selectQuery().Rows(ctx)
}

func (_g *CallGroupBy) selectQuery() *CallSelect {
	selections := make([]ent.Selection, 0, len(_g.columns)+len(_g.aggregates))
	for _, column := range _g.columns {
		selections = append(selections, column)
	}
	selected := _g.query.Select(append(selections, _g.aggregates...)...)
	selected.groups = _g.columns
	return selected
}

// CallSelect is the builder for selecting fields of Call entities.
type CallSelect struct {
	query      *CallQuery
	selections []ent.Selection
	groups     []ent.EntityColumn[entity.Call]
}

func (_s *CallSelect) Aggregate(selections ...ent.Selection) *CallSelect {
	_s.selections = append(_s.selections, selections...)
	return _s
}

func (_s *CallSelect) Row(ctx context.Context) (*ent.Row, error) {
	rows, err := _s.Rows(ctx)
	if err != nil {
		return nil, err
	}
	switch len(rows) {
	case 0:
		return nil, &NotFoundError{call.Label}
	case 1:
		return rows[0], nil
	default:
		return nil, &NotSingularError{call.Label}
	}
}

func (_s *CallSelect) sqlQuery(ctx context.Context) (*sql.Selector, error) {
	root := _s.query.Clone()
	root.ctx.Fields = nil
	for _, selection := range _s.selections {
		if column := selection.Ref(); column.Name != "" && (column.Table == "" || column.Table == call.Table) {
			root.ctx.AppendFieldOnce(column.Name)
		}
	}
	if err := root.prepareQuery(ctx); err != nil {
		return nil, err
	}
	root.modifiers = nil
	selector := root.sqlQuery(ctx)
	if len(_s.selections) > 0 {
		ent.SelectColumns(selector, _s.selections...)
	}
	for _, column := range _s.groups {
		reference := column.Ref()
		if reference.Table == "" || reference.Table == selector.TableName() {
			selector.GroupBy(selector.C(reference.Name))
		} else {
			selector.GroupBy(sql.Dialect(selector.Dialect()).Table(reference.Table).C(reference.Name))
		}
	}
	for _, modifier := range _s.query.modifiers {
		modifier(selector)
	}
	return selector, selector.Err()
}

func (_s *CallSelect) Scan(ctx context.Context, value any) error {
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, value)
}

func (_s *CallSelect) Rows(ctx context.Context) ([]*ent.Row, error) {
	if len(_s.selections) == 0 {
		return nil, errors.New("ent: Rows requires explicit selections")
	}
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	columns, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	if len(columns) != len(_s.selections) {
		return nil, fmt.Errorf("ent: projection column count %d differs from selection count %d", len(columns), len(_s.selections))
	}
	result := make([]*ent.Row, 0)
	for rows.Next() {
		row, destinations := ent.NewRow(_s.selections)
		if err := rows.Scan(destinations...); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return result, nil
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CallSelect) Modify(modifiers ...func(s *sql.Selector)) *CallSelect {
	_s.query.modifiers = append(_s.query.modifiers, modifiers...)
	return _s
}
