// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/callhighlight"
	"fmt"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// CallHighlightInsert is the write representation of a CallHighlight creation.
type CallHighlightInsert struct {
	ID            ent.Option[uuid.UUID]  `json:"id,omitzero"`
	OffsetSeconds float64                `json:"offset_seconds"`
	CallID        uuid.UUID              `json:"call_id"`
	UserID        uuid.UUID              `json:"user_id"`
	CreatedAt     ent.Option[time2.Time] `json:"created_at,omitzero"`
	expressions   map[string]func(*sql.Builder)
}

// CallHighlightPatch is the write representation of a CallHighlight update.
type CallHighlightPatch struct {
	OffsetSeconds    ent.Option[float64] `json:"offset_seconds,omitzero"`
	OffsetSecondsAdd ent.Option[float64] `json:"offset_seconds_add,omitzero"`
	expressions      map[string]func(*sql.Builder)
	clearedEdges     map[string]bool
}

func (i *CallHighlightInsert) set(column string, value any) error {
	switch column {

	case callhighlight.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case callhighlight.FieldOffsetSeconds:
		v, ok := value.(float64)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.OffsetSeconds = v

		delete(i.expressions, column)
		return nil

	case callhighlight.FieldCallID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.CallID = v

		delete(i.expressions, column)
		return nil

	case callhighlight.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.UserID = v

		delete(i.expressions, column)
		return nil

	case callhighlight.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight is not settable", column)}
}

func (i *CallHighlightInsert) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight is not nullable", column)}
}

func (i *CallHighlightInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CallHighlightInsert) setEdge(edge string, id any) error {
	switch edge {

	case callhighlight.EdgeCall:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of CallHighlight", id, edge)}
		}
		return i.set(callhighlight.FieldCallID, value)

	case callhighlight.EdgeUser:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of CallHighlight", id, edge)}
		}
		return i.set(callhighlight.FieldUserID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight is not settable", edge)}
}

func (i *CallHighlightInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight does not accept IDs", edge)}
}

func (i *CallHighlightInsert) callIDs() []uuid.UUID {

	return []uuid.UUID{i.CallID}

}

func (i *CallHighlightInsert) userIDs() []uuid.UUID {

	return []uuid.UUID{i.UserID}

}

func (i *CallHighlightPatch) set(column string, value any) error {
	switch column {

	case callhighlight.FieldOffsetSeconds:
		v, ok := value.(float64)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of CallHighlight", value, column)}
		}
		i.OffsetSeconds = ent.Some(v)

		i.OffsetSecondsAdd = ent.Unset[float64]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight is not settable", column)}
}

func (i *CallHighlightPatch) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight is not nullable", column)}
}

func (i *CallHighlightPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CallHighlightPatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight is not settable", edge)}
}

func (i *CallHighlightPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight does not accept IDs", edge)}
}

func (p *CallHighlightPatch) add(column string, value any) error {
	switch column {

	case callhighlight.FieldOffsetSeconds:
		delta, ok := value.(float64)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.OffsetSecondsAdd.Get(); exists {
			delta += current
		}
		p.OffsetSecondsAdd = ent.Some(delta)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight does not support addition", column)}
}

func (p *CallHighlightPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of CallHighlight does not support append", column)}
}

func (p *CallHighlightPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight does not support removal", edge)}
}

func (p *CallHighlightPatch) clearEdge(edge string) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of CallHighlight cannot be cleared", edge)}
}

func (p *CallHighlightPatch) apply(other CallHighlightPatch) {

	if other.OffsetSeconds.IsSet() {
		p.OffsetSeconds = other.OffsetSeconds
		delete(p.expressions, callhighlight.FieldOffsetSeconds)
	}

	if value, ok := other.OffsetSecondsAdd.Get(); ok {
		if current, exists := p.OffsetSecondsAdd.Get(); exists {
			value += current
		}
		p.OffsetSecondsAdd = ent.Some(value)
	}

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
