// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/callhighlight"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"cameo/internal/ent/user"
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type CallCreate struct {
	config
	mutation    *CallMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *CallCreate) Set[T any](column ent.ColumnOf[entity.Call, T], value T) *CallCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *CallCreate) SetOptional[T any](column ent.ColumnOf[entity.Call, T], value ent.Option[T]) *CallCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CallCreate) SetExpr[T any](column ent.ColumnOf[entity.Call, T], value ent.Expr[T]) *CallCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case call.FieldID:

	case call.FieldStatus:

	case call.FieldTranscriptStatus:

	case call.FieldTitle:

	case call.FieldSummary:

	case call.FieldRecordingKey:

	case call.FieldRecordingBytes:

	case call.FieldFavoritedBy:

	case call.FieldStartedAt:

	case call.FieldEndedAt:

	case call.FieldTranscript:

	case call.FieldCoupleID:

	case call.FieldCallerID:

	case call.FieldCalleeID:

	case call.FieldCreatedAt:

	case call.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *CallCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Call, N, K], id K) *CallCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {
	case call.EdgeCouple:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[call.FieldCoupleID] = struct{}{}
	case call.EdgeCaller:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[call.FieldCallerID] = struct{}{}
	case call.EdgeCallee:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[call.FieldCalleeID] = struct{}{}

	}

	return b
}
func (b *CallCreate) AddIDs[N, K any](edge ent.Relation[entity.Call, N, K], ids ...K) *CallCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CallCreate) Mutation() *CallMutation { return b.mutation }

func (b *CallCreate) Insert() *CallInsert { return b.mutation.insert }

func (b *CallCreate) Save(ctx context.Context) (*Call, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CallCreate) SaveX(ctx context.Context) *Call {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *CallCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CallCreate) defaults() error {

	if b.mutation.insert.ID.IsUnset() && b.mutation.insert.expressions[call.FieldID] == nil {
		if call.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized call.DefaultID")
		}
		b.mutation.insert.ID = ent.Some(call.DefaultID())
	}

	if b.mutation.insert.Status.IsUnset() && b.mutation.insert.expressions[call.FieldStatus] == nil {
		if call.DefaultStatus == nil {
			return fmt.Errorf("ent: uninitialized call.DefaultStatus")
		}
		b.mutation.insert.Status = ent.Some(call.DefaultStatus())
	}

	if b.mutation.insert.TranscriptStatus.IsUnset() && b.mutation.insert.expressions[call.FieldTranscriptStatus] == nil {
		if call.DefaultTranscriptStatus == nil {
			return fmt.Errorf("ent: uninitialized call.DefaultTranscriptStatus")
		}
		b.mutation.insert.TranscriptStatus = ent.Some(call.DefaultTranscriptStatus())
	}

	if b.mutation.insert.RecordingBytes.IsUnset() && b.mutation.insert.expressions[call.FieldRecordingBytes] == nil {

		b.mutation.insert.RecordingBytes = ent.Some(call.DefaultRecordingBytes)
	}

	if b.mutation.insert.FavoritedBy.IsUnset() && b.mutation.insert.expressions[call.FieldFavoritedBy] == nil {

		b.mutation.insert.FavoritedBy = ent.Some(call.DefaultFavoritedBy)
	}

	if b.mutation.insert.CreatedAt.IsUnset() && b.mutation.insert.expressions[call.FieldCreatedAt] == nil {
		if call.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized call.DefaultCreatedAt")
		}
		b.mutation.insert.CreatedAt = ent.Some(call.DefaultCreatedAt())
	}

	if b.mutation.insert.UpdatedAt.IsUnset() && b.mutation.insert.expressions[call.FieldUpdatedAt] == nil {
		if call.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized call.DefaultUpdatedAt")
		}
		b.mutation.insert.UpdatedAt = ent.Some(call.DefaultUpdatedAt())
	}

	return nil
}

func (b *CallCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "Call.id" is not nullable`)}
	}

	if b.mutation.insert.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Call.status" is not nullable`)}
	}

	if b.mutation.insert.expressions[call.FieldStatus] == nil {
		if v, ok := b.mutation.insert.Status.Get(); ok {

			if err := v.Validate(); err != nil {
				return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Call.status": %w`, err)}
			}

		}
	}

	if b.mutation.insert.TranscriptStatus.IsNull() {
		return &ValidationError{Name: "transcript_status", err: errors.New(`ent: field "Call.transcript_status" is not nullable`)}
	}

	if b.mutation.insert.expressions[call.FieldTranscriptStatus] == nil {
		if v, ok := b.mutation.insert.TranscriptStatus.Get(); ok {

			if err := v.Validate(); err != nil {
				return &ValidationError{Name: "transcript_status", err: fmt.Errorf(`ent: validator failed for field "Call.transcript_status": %w`, err)}
			}

		}
	}

	if b.mutation.insert.RecordingBytes.IsNull() {
		return &ValidationError{Name: "recording_bytes", err: errors.New(`ent: field "Call.recording_bytes" is not nullable`)}
	}

	if b.mutation.insert.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Call.favorited_by" is not nullable`)}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[call.FieldCoupleID]; b.fromBuilder && !present {
			return &ValidationError{Name: "couple_id", err: errors.New(`ent: missing required field "Call.couple_id"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[call.FieldCallerID]; b.fromBuilder && !present {
			return &ValidationError{Name: "caller_id", err: errors.New(`ent: missing required field "Call.caller_id"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[call.FieldCalleeID]; b.fromBuilder && !present {
			return &ValidationError{Name: "callee_id", err: errors.New(`ent: missing required field "Call.callee_id"`)}
		}
	}

	if b.mutation.insert.CreatedAt.IsNull() {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: field "Call.created_at" is not nullable`)}
	}

	if b.mutation.insert.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Call.updated_at" is not nullable`)}
	}

	if len(b.mutation.insert.coupleIDs()) == 0 {
		return &ValidationError{Name: "couple", err: errors.New(`ent: missing required edge "Call.couple"`)}
	}

	if len(b.mutation.insert.callerIDs()) == 0 {
		return &ValidationError{Name: "caller", err: errors.New(`ent: missing required edge "Call.caller"`)}
	}

	if len(b.mutation.insert.calleeIDs()) == 0 {
		return &ValidationError{Name: "callee", err: errors.New(`ent: missing required edge "Call.callee"`)}
	}

	return nil
}

func (_c *CallCreate) sqlSave(ctx context.Context) (*Call, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *CallCreate) createSpec() (*Call, *sqlgraph.CreateSpec, error) {
	_node := &Call{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(call.Table, sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = &value
	}

	if value, ok := _c.mutation.insert.Status.Get(); ok {
		_spec.SetField(call.FieldStatus, field.TypeInt8, value)
	}
	if _c.mutation.insert.Status.IsNull() {
		_spec.SetField(call.FieldStatus, field.TypeInt8, nil)
	}

	if value, ok := _c.mutation.insert.TranscriptStatus.Get(); ok {
		_spec.SetField(call.FieldTranscriptStatus, field.TypeInt8, value)
	}
	if _c.mutation.insert.TranscriptStatus.IsNull() {
		_spec.SetField(call.FieldTranscriptStatus, field.TypeInt8, nil)
	}

	if value, ok := _c.mutation.insert.Title.Get(); ok {
		_spec.SetField(call.FieldTitle, field.TypeString, value)
	}
	if _c.mutation.insert.Title.IsNull() {
		_spec.SetField(call.FieldTitle, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.Summary.Get(); ok {
		_spec.SetField(call.FieldSummary, field.TypeString, value)
	}
	if _c.mutation.insert.Summary.IsNull() {
		_spec.SetField(call.FieldSummary, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.RecordingKey.Get(); ok {
		_spec.SetField(call.FieldRecordingKey, field.TypeString, value)
	}
	if _c.mutation.insert.RecordingKey.IsNull() {
		_spec.SetField(call.FieldRecordingKey, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.RecordingBytes.Get(); ok {
		_spec.SetField(call.FieldRecordingBytes, field.TypeInt64, value)
	}
	if _c.mutation.insert.RecordingBytes.IsNull() {
		_spec.SetField(call.FieldRecordingBytes, field.TypeInt64, nil)
	}

	if value, ok := _c.mutation.insert.FavoritedBy.Get(); ok {
		_spec.SetField(call.FieldFavoritedBy, field.TypeArray, value)
	}
	if _c.mutation.insert.FavoritedBy.IsNull() {
		_spec.SetField(call.FieldFavoritedBy, field.TypeArray, nil)
	}

	if value, ok := _c.mutation.insert.StartedAt.Get(); ok {
		_spec.SetField(call.FieldStartedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.StartedAt.IsNull() {
		_spec.SetField(call.FieldStartedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.EndedAt.Get(); ok {
		_spec.SetField(call.FieldEndedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.EndedAt.IsNull() {
		_spec.SetField(call.FieldEndedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.Transcript.Get(); ok {
		_spec.SetField(call.FieldTranscript, field.TypeJSON, value)
	}
	if _c.mutation.insert.Transcript.IsNull() {
		_spec.SetField(call.FieldTranscript, field.TypeJSON, nil)
	}

	if value, ok := _c.mutation.insert.CreatedAt.Get(); ok {
		_spec.SetField(call.FieldCreatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.CreatedAt.IsNull() {
		_spec.SetField(call.FieldCreatedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.UpdatedAt.Get(); ok {
		_spec.SetField(call.FieldUpdatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.UpdatedAt.IsNull() {
		_spec.SetField(call.FieldUpdatedAt, field.TypeTime, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.highlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.HighlightsTable,
			Columns: []string{call.HighlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(callhighlight.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.photosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   call.PhotosTable,
			Columns: []string{call.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.coupleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CoupleTable,
			Columns: []string{call.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.callerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CallerTable,
			Columns: []string{call.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.calleeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   call.CalleeTable,
			Columns: []string{call.CalleeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: call.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(call.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(call.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type CallUpsertOne struct{ create *CallCreate }

func (b *CallCreate) OnConflict(columns ...ent.EntityColumn[entity.Call]) *CallUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CallCreate) OnConflictConstraint(name string) *CallUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CallCreate) OnConflictOptions(options ...sql.ConflictOption) *CallUpsertOne {
	b.conflict = options
	return &CallUpsertOne{create: b}
}

func (u *CallUpsertOne) DoNothing() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CallUpsertOne) DoSelect() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CallUpsertOne) Ignore() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CallUpsertOne) DoUpdate(set func(*CallUpsert)) *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CallUpsert{UpdateSet: update}) }))
	return u
}

func (u *CallUpsertOne) UpdateNewValues() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case call.FieldID:
				update.SetIgnore(column)

			case call.FieldCallerID:
				update.SetIgnore(column)

			case call.FieldCalleeID:
				update.SetIgnore(column)

			case call.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CallUpsertOne) Where(predicates ...ent.Predicate[entity.Call]) *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(call.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CallUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Call]) *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(call.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CallUpsertOne) Save(ctx context.Context) (*Call, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CallCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CallUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CallUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *CallUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *CallUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type CallUpsert struct{ *sql.UpdateSet }

func (u *CallUpsert) Set[T any](column ent.ColumnOf[entity.Call, T], value T) *CallUpsert {
	switch column.Ref().Name {

	case call.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldTranscriptStatus:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldTitle:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldSummary:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldRecordingKey:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldRecordingBytes:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldFavoritedBy:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldStartedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldEndedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldTranscript:

		encoded, err := json.Marshal(value)
		if err != nil {
			u.UpdateSet.AddError(err)
			return u
		}
		u.UpdateSet.Set(column.Ref().Name, json.RawMessage(encoded))

	case call.FieldCoupleID:
		u.UpdateSet.Set(column.Ref().Name, value)

	case call.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CallUpsert) SetExpr[T any](column ent.ColumnOf[entity.Call, T], value ent.Expr[T]) *CallUpsert {
	switch column.Ref().Name {

	case call.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldTranscriptStatus:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldTitle:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldSummary:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldRecordingKey:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldRecordingBytes:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldFavoritedBy:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldStartedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldEndedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldTranscript:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldCoupleID:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case call.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CallUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Call, T]) *CallUpsert {
	switch column.Ref().Name {

	case call.FieldStatus:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldTranscriptStatus:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldTitle:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldSummary:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldRecordingKey:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldRecordingBytes:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldFavoritedBy:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldStartedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldEndedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldTranscript:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldCoupleID:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case call.FieldUpdatedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CallUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Call, T], delta T) *CallUpsert {
	switch column.Ref().Name {

	case call.FieldStatus:
		u.UpdateSet.Add(column.Ref().Name, delta)

	case call.FieldTranscriptStatus:
		u.UpdateSet.Add(column.Ref().Name, delta)

	case call.FieldRecordingBytes:
		u.UpdateSet.Add(column.Ref().Name, delta)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *CallUpsert) Clear[T any](column ent.ColumnOf[entity.Call, T]) *CallUpsert {
	switch column.Ref().Name {

	case call.FieldTitle:
		u.UpdateSet.SetNull(column.Ref().Name)

	case call.FieldSummary:
		u.UpdateSet.SetNull(column.Ref().Name)

	case call.FieldRecordingKey:
		u.UpdateSet.SetNull(column.Ref().Name)

	case call.FieldStartedAt:
		u.UpdateSet.SetNull(column.Ref().Name)

	case call.FieldEndedAt:
		u.UpdateSet.SetNull(column.Ref().Name)

	case call.FieldTranscript:
		u.UpdateSet.SetNull(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Call is not nullable", column.Ref().Name)})
	}
	return u
}

type CallCreateBulk struct {
	config
	err      error
	builders []*CallCreate

	conflict []sql.ConflictOption
}

func (_c *CallCreateBulk) Save(ctx context.Context) ([]*Call, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Call, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *CallCreateBulk) SaveX(ctx context.Context) []*Call {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *CallCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CallCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type CallUpsertBulk struct{ create *CallCreateBulk }

func (b *CallCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Call]) *CallUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CallCreateBulk) OnConflictConstraint(name string) *CallUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CallCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *CallUpsertBulk {
	b.conflict = options
	return &CallUpsertBulk{create: b}
}

func (u *CallUpsertBulk) DoNothing() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CallUpsertBulk) DoSelect() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CallUpsertBulk) Ignore() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CallUpsertBulk) DoUpdate(set func(*CallUpsert)) *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CallUpsert{UpdateSet: update}) }))
	return u
}

func (u *CallUpsertBulk) UpdateNewValues() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case call.FieldID:
				update.SetIgnore(column)

			case call.FieldCallerID:
				update.SetIgnore(column)

			case call.FieldCalleeID:
				update.SetIgnore(column)

			case call.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CallUpsertBulk) Where(predicates ...ent.Predicate[entity.Call]) *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(call.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CallUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Call]) *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(call.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CallUpsertBulk) Save(ctx context.Context) ([]*Call, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CallCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CallUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CallUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
