// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"cameo/internal/ent/user"
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type CoupleUpdate struct {
	config
	mutation  *CoupleMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CoupleUpdate) Set[T any](column ent.ColumnOf[entity.Couple, T], value T) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CoupleUpdate) SetOptional[T any](column ent.ColumnOf[entity.Couple, T], value ent.Option[T]) *CoupleUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CoupleUpdate) SetExpr[T any](column ent.ColumnOf[entity.Couple, T], value ent.Expr[T]) *CoupleUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case couple.FieldDisconnectedAt:

	case couple.FieldRestoredAt:

	case couple.FieldRestoreTransactionID:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Couple is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CoupleUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Couple, N, K], id K) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CoupleUpdate) AddIDs[N, K any](edge ent.Relation[entity.Couple, N, K], ids ...K) *CoupleUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CoupleUpdate) Mutation() *CoupleMutation { return b.mutation }

func (b *CoupleUpdate) Patch() *CouplePatch               { return b.mutation.patch }
func (b *CoupleUpdate) Apply(p CouplePatch) *CoupleUpdate { b.mutation.patch.apply(p); return b }
func (b *CoupleUpdate) Add[T ent.Number](column ent.ColumnOf[entity.Couple, T], delta T) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CoupleUpdate) Append[T any](column ent.ColumnOf[entity.Couple, T], values T) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CoupleUpdate) Clear[T any](column ent.ColumnOf[entity.Couple, T]) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CoupleUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.Couple, N, K], ids ...K) *CoupleUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CoupleUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.Couple, N, K]) *CoupleUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CoupleUpdate) Where(predicates ...ent.Predicate[entity.Couple]) *CoupleUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *CoupleUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *CoupleUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CoupleUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CoupleUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CoupleUpdate) Returning(ctx context.Context) ([]*Couple, error) {
	nodes := make([]*Couple, 0)
	b.returning = &sqlgraph.Returning{Columns: couple.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Couple{config: b.config}
		values, err := _node.scanValues(couple.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(couple.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *CoupleUpdate) defaults() error {

	return nil
}

func (b *CoupleUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoupleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoupleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoupleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(couple.Table, couple.Columns, sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.DisconnectedAt.Get(); ok {
		_spec.SetField(couple.FieldDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.DisconnectedAt.IsNull() {
		_spec.ClearField(couple.FieldDisconnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.RestoredAt.Get(); ok {
		_spec.SetField(couple.FieldRestoredAt, field.TypeTime, value)
	}
	if _u.mutation.patch.RestoredAt.IsNull() {
		_spec.ClearField(couple.FieldRestoredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.RestoreTransactionID.Get(); ok {
		_spec.SetField(couple.FieldRestoreTransactionID, field.TypeString, value)
	}
	if _u.mutation.patch.RestoreTransactionID.IsNull() {
		_spec.ClearField(couple.FieldRestoreTransactionID, field.TypeString)
	}
	if _u.mutation.patch.Members.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Members.Remove; len(nodes) > 0 && !_u.mutation.patch.Members.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.membersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Calls.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Calls.Remove; len(nodes) > 0 && !_u.mutation.patch.Calls.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.callsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Photos.Remove; len(nodes) > 0 && !_u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.photosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{couple.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type CoupleUpdateOne struct {
	config
	mutation *CoupleMutation
	err      error

	fields []string
	old    *Couple

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CoupleUpdateOne) Set[T any](column ent.ColumnOf[entity.Couple, T], value T) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CoupleUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.Couple, T], value ent.Option[T]) *CoupleUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CoupleUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.Couple, T], value ent.Expr[T]) *CoupleUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case couple.FieldDisconnectedAt:

	case couple.FieldRestoredAt:

	case couple.FieldRestoreTransactionID:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Couple is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CoupleUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.Couple, N, K], id K) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CoupleUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.Couple, N, K], ids ...K) *CoupleUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CoupleUpdateOne) Mutation() *CoupleMutation { return b.mutation }

func (b *CoupleUpdateOne) Patch() *CouplePatch                  { return b.mutation.patch }
func (b *CoupleUpdateOne) Apply(p CouplePatch) *CoupleUpdateOne { b.mutation.patch.apply(p); return b }
func (b *CoupleUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.Couple, T], delta T) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CoupleUpdateOne) Append[T any](column ent.ColumnOf[entity.Couple, T], values T) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CoupleUpdateOne) Clear[T any](column ent.ColumnOf[entity.Couple, T]) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CoupleUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.Couple, N, K], ids ...K) *CoupleUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CoupleUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.Couple, N, K]) *CoupleUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CoupleUpdateOne) Where(predicates ...ent.Predicate[entity.Couple]) *CoupleUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *CoupleUpdateOne) Save(ctx context.Context) (*Couple, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CoupleUpdateOne) SaveX(ctx context.Context) *Couple {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CoupleUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CoupleUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// Columns narrows the entity columns returned by the update. The ID is always included.
func (b *CoupleUpdateOne) Columns(columns ...ent.EntityColumn[entity.Couple]) *CoupleUpdateOne {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *CoupleUpdateOne) SaveOld(ctx context.Context) (old *Couple, updated *Couple, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &Couple{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *CoupleUpdateOne) defaults() error {

	return nil
}

func (b *CoupleUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoupleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoupleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoupleUpdateOne) sqlSave(ctx context.Context) (_node *Couple, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(couple.Table, couple.Columns, sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Couple.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, couple.FieldID)
		for _, f := range fields {
			if !couple.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != couple.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.DisconnectedAt.Get(); ok {
		_spec.SetField(couple.FieldDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.DisconnectedAt.IsNull() {
		_spec.ClearField(couple.FieldDisconnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.RestoredAt.Get(); ok {
		_spec.SetField(couple.FieldRestoredAt, field.TypeTime, value)
	}
	if _u.mutation.patch.RestoredAt.IsNull() {
		_spec.ClearField(couple.FieldRestoredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.RestoreTransactionID.Get(); ok {
		_spec.SetField(couple.FieldRestoreTransactionID, field.TypeString, value)
	}
	if _u.mutation.patch.RestoreTransactionID.IsNull() {
		_spec.ClearField(couple.FieldRestoreTransactionID, field.TypeString)
	}
	if _u.mutation.patch.Members.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Members.Remove; len(nodes) > 0 && !_u.mutation.patch.Members.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.membersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.MembersTable,
			Columns: []string{couple.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Calls.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Calls.Remove; len(nodes) > 0 && !_u.mutation.patch.Calls.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.callsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.CallsTable,
			Columns: []string{couple.CallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Photos.Remove; len(nodes) > 0 && !_u.mutation.patch.Photos.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.photosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   couple.PhotosTable,
			Columns: []string{couple.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &Couple{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{couple.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
