// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/couple"
	"fmt"
	"slices"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// CoupleInsert is the write representation of a Couple creation.
type CoupleInsert struct {
	ID                   ent.Option[uuid.UUID]   `json:"id,omitzero"`
	UserIDs              ent.Option[[]uuid.UUID] `json:"user_ids,omitzero"`
	DisconnectedAt       ent.Option[time2.Time]  `json:"disconnected_at,omitzero"`
	RestoredAt           ent.Option[time2.Time]  `json:"restored_at,omitzero"`
	RestoreTransactionID ent.Option[string]      `json:"restore_transaction_id,omitzero"`
	CreatedAt            ent.Option[time2.Time]  `json:"created_at,omitzero"`
	MemberIDs            []uuid.UUID             `json:"member_ids,omitzero"`
	CallIDs              []uuid.UUID             `json:"call_ids,omitzero"`
	PhotoIDs             []uuid.UUID             `json:"photo_ids,omitzero"`
	expressions          map[string]func(*sql.Builder)
}

// CouplePatch is the write representation of a Couple update.
type CouplePatch struct {
	DisconnectedAt       ent.Option[time2.Time]       `json:"disconnected_at,omitzero"`
	RestoredAt           ent.Option[time2.Time]       `json:"restored_at,omitzero"`
	RestoreTransactionID ent.Option[string]           `json:"restore_transaction_id,omitzero"`
	Members              ent.RelationPatch[uuid.UUID] `json:"members,omitzero"`
	Calls                ent.RelationPatch[uuid.UUID] `json:"calls,omitzero"`
	Photos               ent.RelationPatch[uuid.UUID] `json:"photos,omitzero"`
	expressions          map[string]func(*sql.Builder)
	clearedEdges         map[string]bool
}

func (i *CoupleInsert) set(column string, value any) error {
	switch column {

	case couple.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldUserIDs:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.UserIDs = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldDisconnectedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.DisconnectedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoredAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.RestoredAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoreTransactionID:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.RestoreTransactionID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple is not settable", column)}
}

func (i *CoupleInsert) setNull(column string) error {
	switch column {

	case couple.FieldDisconnectedAt:
		i.DisconnectedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoredAt:
		i.RestoredAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoreTransactionID:
		i.RestoreTransactionID = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple is not nullable", column)}
}

func (i *CoupleInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CoupleInsert) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple is not settable", edge)}
}

func (i *CoupleInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	case couple.EdgeMembers:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.MemberIDs = append(i.MemberIDs, value)
		}
		return nil

	case couple.EdgeCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.CallIDs = append(i.CallIDs, value)
		}
		return nil

	case couple.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.PhotoIDs = append(i.PhotoIDs, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple does not accept IDs", edge)}
}

func (i *CoupleInsert) membersIDs() []uuid.UUID {
	return i.MemberIDs
}

func (i *CoupleInsert) callsIDs() []uuid.UUID {
	return i.CallIDs
}

func (i *CoupleInsert) photosIDs() []uuid.UUID {
	return i.PhotoIDs
}

func (i *CouplePatch) set(column string, value any) error {
	switch column {

	case couple.FieldDisconnectedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.DisconnectedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoredAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.RestoredAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoreTransactionID:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Couple", value, column)}
		}
		i.RestoreTransactionID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple is not settable", column)}
}

func (i *CouplePatch) setNull(column string) error {
	switch column {

	case couple.FieldDisconnectedAt:
		i.DisconnectedAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoredAt:
		i.RestoredAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case couple.FieldRestoreTransactionID:
		i.RestoreTransactionID = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple is not nullable", column)}
}

func (i *CouplePatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *CouplePatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple is not settable", edge)}
}

func (i *CouplePatch) addIDs(edge string, ids ...any) error {
	switch edge {

	case couple.EdgeMembers:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.Members.Add = append(i.Members.Add, value)
		}
		return nil

	case couple.EdgeCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.Calls.Add = append(i.Calls.Add, value)
		}
		return nil

	case couple.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Couple", id, edge)}
			}
			i.Photos.Add = append(i.Photos.Add, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple does not accept IDs", edge)}
}

func (i *CouplePatch) membersIDs() []uuid.UUID {
	return i.Members.Add

}

func (i *CouplePatch) callsIDs() []uuid.UUID {
	return i.Calls.Add

}

func (i *CouplePatch) photosIDs() []uuid.UUID {
	return i.Photos.Add

}

func (p *CouplePatch) add(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple does not support addition", column)}
}

func (p *CouplePatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Couple does not support append", column)}
}

func (p *CouplePatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	case couple.EdgeMembers:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Members.Remove = append(p.Members.Remove, value)
			p.Members.Add = slices.DeleteFunc(p.Members.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case couple.EdgeCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Calls.Remove = append(p.Calls.Remove, value)
			p.Calls.Add = slices.DeleteFunc(p.Calls.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case couple.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Photos.Remove = append(p.Photos.Remove, value)
			p.Photos.Add = slices.DeleteFunc(p.Photos.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple does not support removal", edge)}
}

func (p *CouplePatch) clearEdge(edge string) error {
	switch edge {

	case couple.EdgeMembers:
		p.Members.Clear = true
		return nil

	case couple.EdgeCalls:
		p.Calls.Clear = true
		return nil

	case couple.EdgePhotos:
		p.Photos.Clear = true
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Couple cannot be cleared", edge)}
}

func (p *CouplePatch) apply(other CouplePatch) {

	if other.DisconnectedAt.IsSet() {
		p.DisconnectedAt = other.DisconnectedAt
		delete(p.expressions, couple.FieldDisconnectedAt)
	}

	if other.RestoredAt.IsSet() {
		p.RestoredAt = other.RestoredAt
		delete(p.expressions, couple.FieldRestoredAt)
	}

	if other.RestoreTransactionID.IsSet() {
		p.RestoreTransactionID = other.RestoreTransactionID
		delete(p.expressions, couple.FieldRestoreTransactionID)
	}

	p.Members.Add = append(p.Members.Add, other.Members.Add...)
	p.Members.Remove = append(p.Members.Remove, other.Members.Remove...)
	p.Members.Clear = p.Members.Clear || other.Members.Clear

	p.Calls.Add = append(p.Calls.Add, other.Calls.Add...)
	p.Calls.Remove = append(p.Calls.Remove, other.Calls.Remove...)
	p.Calls.Clear = p.Calls.Clear || other.Calls.Clear

	p.Photos.Add = append(p.Photos.Add, other.Photos.Add...)
	p.Photos.Remove = append(p.Photos.Remove, other.Photos.Remove...)
	p.Photos.Clear = p.Photos.Clear || other.Photos.Clear

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
