// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// Couple is the model entity for the Couple schema.
type Couple struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DisconnectedAt holds the value of the "disconnected_at" field.
	DisconnectedAt *time2.Time `json:"disconnected_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time2.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CoupleQuery when eager-loading is set.
	Edges CoupleEdges `json:"edges"`
}

// CoupleEdges holds the relations/edges for other nodes in the graph.
type CoupleEdges struct {
	// Members holds the value of the members edge.
	Members []*User `json:"members,omitempty"`
	// Calls holds the value of the calls edge.
	Calls []*Call `json:"calls,omitempty"`
	// Photos holds the value of the photos edge.
	Photos []*Photo `json:"photos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	counts      map[string]int
}

func (e CoupleEdges) Loaded[N, K any](edge ent.RelationOf[entity.Couple, N, K]) bool {
	switch edge.Ref().Name {
	case "members":
		return e.loadedTypes[0]
	case "calls":
		return e.loadedTypes[1]
	case "photos":
		return e.loadedTypes[2]

	default:
		return false
	}
}

func (e *CoupleEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.Couple, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "members":
		e.loadedTypes[0] = loaded
	case "calls":
		e.loadedTypes[1] = loaded
	case "photos":
		e.loadedTypes[2] = loaded

	}
}

func (e CoupleEdges) Count[N, K any](edge ent.Relation[entity.Couple, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e CoupleEdges) MembersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// CallsOrErr returns the Calls value or an error if the edge
// was not loaded in eager-loading.
func (e CoupleEdges) CallsOrErr() ([]*Call, error) {
	if e.loadedTypes[1] {
		return e.Calls, nil
	}
	return nil, &NotLoadedError{edge: "calls"}
}

// PhotosOrErr returns the Photos value or an error if the edge
// was not loaded in eager-loading.
func (e CoupleEdges) PhotosOrErr() ([]*Photo, error) {
	if e.loadedTypes[2] {
		return e.Photos, nil
	}
	return nil, &NotLoadedError{edge: "photos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Couple) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case couple.FieldDisconnectedAt, couple.FieldCreatedAt:
			values[i] = new(*time2.Time)
		case couple.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Couple fields.
func (_m *Couple) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case couple.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case couple.FieldDisconnectedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field disconnected_at", values[i])
			} else if value != nil && *value != nil {
				_m.DisconnectedAt = *value
			}
		case couple.FieldCreatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil && *value != nil {
				_m.CreatedAt = **value
			}
		}
	}
	return nil
}

// QueryMembers queries the "members" edge of the Couple entity.
func (_m *Couple) QueryMembers() *UserQuery {
	return NewCoupleClient(_m.config).QueryMembers(_m)
}

// QueryCalls queries the "calls" edge of the Couple entity.
func (_m *Couple) QueryCalls() *CallQuery {
	return NewCoupleClient(_m.config).QueryCalls(_m)
}

// QueryPhotos queries the "photos" edge of the Couple entity.
func (_m *Couple) QueryPhotos() *PhotoQuery {
	return NewCoupleClient(_m.config).QueryPhotos(_m)
}

// Update returns a builder for updating this Couple.
// Note that you need to call Couple.Unwrap() before calling this method if this Couple
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Couple) Update() *CoupleUpdateOne {
	return NewCoupleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Couple entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Couple) Unwrap() *Couple {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Couple is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Couple) String() string {
	var builder strings.Builder
	builder.WriteString("Couple(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DisconnectedAt; v != nil {
		builder.WriteString("disconnected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Couples is a parsable slice of Couple.
type Couples []*Couple
