// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

// CoupleDelete is the builder for deleting a Couple entity.
type CoupleDelete struct {
	config

	mutation  *CoupleMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the CoupleDelete builder.
func (_d *CoupleDelete) Where(predicates ...ent.Predicate[entity.Couple]) *CoupleDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CoupleDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *CoupleDelete) Returning(ctx context.Context) ([]*Couple, error) {
	nodes := make([]*Couple, 0)
	b.returning = &sqlgraph.Returning{Columns: couple.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Couple{config: b.config}
		values, err := _node.scanValues(couple.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(couple.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoupleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CoupleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(couple.Table, sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CoupleDeleteOne is the builder for deleting a single Couple entity.
type CoupleDeleteOne struct {
	_d *CoupleDelete
}

// Where appends a list predicates to the CoupleDelete builder.
func (_d *CoupleDeleteOne) Where(predicates ...ent.Predicate[entity.Couple]) *CoupleDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *CoupleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{couple.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoupleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
