// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/device"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/session"
	"cameo/internal/ent/user"
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type DeviceCreate struct {
	config
	mutation    *DeviceMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *DeviceCreate) Set[T any](column ent.ColumnOf[entity.Device, T], value T) *DeviceCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *DeviceCreate) SetOptional[T any](column ent.ColumnOf[entity.Device, T], value ent.Option[T]) *DeviceCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *DeviceCreate) SetExpr[T any](column ent.ColumnOf[entity.Device, T], value ent.Expr[T]) *DeviceCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case device.FieldID:

	case device.FieldPlatform:

	case device.FieldToken:

	case device.FieldUserID:

	case device.FieldSessionID:

	case device.FieldCreatedAt:

	case device.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *DeviceCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Device, N, K], id K) *DeviceCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {
	case device.EdgeUser:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[device.FieldUserID] = struct{}{}
	case device.EdgeSession:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[device.FieldSessionID] = struct{}{}

	}

	return b
}
func (b *DeviceCreate) AddIDs[N, K any](edge ent.Relation[entity.Device, N, K], ids ...K) *DeviceCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *DeviceCreate) Mutation() *DeviceMutation { return b.mutation }

func (b *DeviceCreate) Insert() *DeviceInsert { return b.mutation.insert }

func (b *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *DeviceCreate) SaveX(ctx context.Context) *Device {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *DeviceCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *DeviceCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *DeviceCreate) defaults() error {

	if b.mutation.insert.ID.IsUnset() && b.mutation.insert.expressions[device.FieldID] == nil {
		if device.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized device.DefaultID")
		}
		b.mutation.insert.ID = ent.Some(device.DefaultID())
	}

	if b.mutation.insert.CreatedAt.IsUnset() && b.mutation.insert.expressions[device.FieldCreatedAt] == nil {
		if device.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized device.DefaultCreatedAt")
		}
		b.mutation.insert.CreatedAt = ent.Some(device.DefaultCreatedAt())
	}

	if b.mutation.insert.UpdatedAt.IsUnset() && b.mutation.insert.expressions[device.FieldUpdatedAt] == nil {
		if device.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized device.DefaultUpdatedAt")
		}
		b.mutation.insert.UpdatedAt = ent.Some(device.DefaultUpdatedAt())
	}

	return nil
}

func (b *DeviceCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "Device.id" is not nullable`)}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[device.FieldPlatform]; b.fromBuilder && !present {
			return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Device.platform"`)}
		}
	}

	if b.mutation.insert.expressions[device.FieldPlatform] == nil {
		v := b.mutation.insert.Platform

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Device.platform": %w`, err)}
		}

	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[device.FieldToken]; b.fromBuilder && !present {
			return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Device.token"`)}
		}
	}

	if b.mutation.insert.expressions[device.FieldToken] == nil {
		v := b.mutation.insert.Token

		if err := device.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Device.token": %w`, err)}
		}

	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[device.FieldUserID]; b.fromBuilder && !present {
			return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Device.user_id"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[device.FieldSessionID]; b.fromBuilder && !present {
			return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Device.session_id"`)}
		}
	}

	if b.mutation.insert.CreatedAt.IsNull() {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: field "Device.created_at" is not nullable`)}
	}

	if b.mutation.insert.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Device.updated_at" is not nullable`)}
	}

	if len(b.mutation.insert.userIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Device.user"`)}
	}

	if len(b.mutation.insert.sessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Device.session"`)}
	}

	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec, error) {
	_node := &Device{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = &value
	}

	if _, present := _c.present[device.FieldPlatform]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Platform
		_spec.SetField(device.FieldPlatform, field.TypeInt8, value)
	}

	if _, present := _c.present[device.FieldToken]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Token
		_spec.SetField(device.FieldToken, field.TypeString, value)
	}

	if value, ok := _c.mutation.insert.CreatedAt.Get(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.CreatedAt.IsNull() {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.UpdatedAt.Get(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.UpdatedAt.IsNull() {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.userIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.sessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.SessionTable,
			Columns: []string{device.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: device.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(device.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(device.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type DeviceUpsertOne struct{ create *DeviceCreate }

func (b *DeviceCreate) OnConflict(columns ...ent.EntityColumn[entity.Device]) *DeviceUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *DeviceCreate) OnConflictConstraint(name string) *DeviceUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *DeviceCreate) OnConflictOptions(options ...sql.ConflictOption) *DeviceUpsertOne {
	b.conflict = options
	return &DeviceUpsertOne{create: b}
}

func (u *DeviceUpsertOne) DoNothing() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *DeviceUpsertOne) DoSelect() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *DeviceUpsertOne) Ignore() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *DeviceUpsertOne) DoUpdate(set func(*DeviceUpsert)) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&DeviceUpsert{UpdateSet: update}) }))
	return u
}

func (u *DeviceUpsertOne) UpdateNewValues() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case device.FieldID:
				update.SetIgnore(column)

			case device.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *DeviceUpsertOne) Where(predicates ...ent.Predicate[entity.Device]) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(device.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *DeviceUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Device]) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(device.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *DeviceUpsertOne) Save(ctx context.Context) (*Device, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for DeviceCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *DeviceUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *DeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *DeviceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *DeviceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type DeviceUpsert struct{ *sql.UpdateSet }

func (u *DeviceUpsert) Set[T any](column ent.ColumnOf[entity.Device, T], value T) *DeviceUpsert {
	switch column.Ref().Name {

	case device.FieldPlatform:
		u.UpdateSet.Set(column.Ref().Name, value)

	case device.FieldToken:
		u.UpdateSet.Set(column.Ref().Name, value)

	case device.FieldUserID:
		u.UpdateSet.Set(column.Ref().Name, value)

	case device.FieldSessionID:
		u.UpdateSet.Set(column.Ref().Name, value)

	case device.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device is not settable", column.Ref().Name)})
	}
	return u
}

func (u *DeviceUpsert) SetExpr[T any](column ent.ColumnOf[entity.Device, T], value ent.Expr[T]) *DeviceUpsert {
	switch column.Ref().Name {

	case device.FieldPlatform:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case device.FieldToken:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case device.FieldUserID:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case device.FieldSessionID:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case device.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device is not settable", column.Ref().Name)})
	}
	return u
}

func (u *DeviceUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Device, T]) *DeviceUpsert {
	switch column.Ref().Name {

	case device.FieldPlatform:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case device.FieldToken:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case device.FieldUserID:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case device.FieldSessionID:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case device.FieldUpdatedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device is not settable", column.Ref().Name)})
	}
	return u
}

func (u *DeviceUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Device, T], delta T) *DeviceUpsert {
	switch column.Ref().Name {

	case device.FieldPlatform:
		u.UpdateSet.Add(column.Ref().Name, delta)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *DeviceUpsert) Clear[T any](column ent.ColumnOf[entity.Device, T]) *DeviceUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Device is not nullable", column.Ref().Name)})
	}
	return u
}

type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate

	conflict []sql.ConflictOption
}

func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Device, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *DeviceCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type DeviceUpsertBulk struct{ create *DeviceCreateBulk }

func (b *DeviceCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Device]) *DeviceUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *DeviceCreateBulk) OnConflictConstraint(name string) *DeviceUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *DeviceCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *DeviceUpsertBulk {
	b.conflict = options
	return &DeviceUpsertBulk{create: b}
}

func (u *DeviceUpsertBulk) DoNothing() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *DeviceUpsertBulk) DoSelect() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *DeviceUpsertBulk) Ignore() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *DeviceUpsertBulk) DoUpdate(set func(*DeviceUpsert)) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&DeviceUpsert{UpdateSet: update}) }))
	return u
}

func (u *DeviceUpsertBulk) UpdateNewValues() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case device.FieldID:
				update.SetIgnore(column)

			case device.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *DeviceUpsertBulk) Where(predicates ...ent.Predicate[entity.Device]) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(device.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *DeviceUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Device]) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(device.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *DeviceUpsertBulk) Save(ctx context.Context) ([]*Device, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for DeviceCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *DeviceUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *DeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
