// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/device"
	"cameo/internal/ent/entity"
	device2 "cameo/internal/ent/schema_types/device"
	"cameo/internal/ent/session"
	"cameo/internal/ent/user"
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform device2.Platform `json:"platform,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time2.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time2.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceQuery when eager-loading is set.
	Edges DeviceEdges `json:"edges"`
}

// DeviceEdges holds the relations/edges for other nodes in the graph.
type DeviceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	counts      map[string]int
}

func (e DeviceEdges) Loaded[N, K any](edge ent.RelationOf[entity.Device, N, K]) bool {
	switch edge.Ref().Name {
	case "user":
		return e.loadedTypes[0]
	case "session":
		return e.loadedTypes[1]

	default:
		return false
	}
}

func (e *DeviceEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.Device, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "user":
		e.loadedTypes[0] = loaded
	case "session":
		e.loadedTypes[1] = loaded

	}
}

func (e DeviceEdges) Count[N, K any](edge ent.Relation[entity.Device, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldPlatform:
			values[i] = new(*device2.Platform)
		case device.FieldToken:
			values[i] = new(*string)
		case device.FieldCreatedAt, device.FieldUpdatedAt:
			values[i] = new(*time2.Time)
		case device.FieldID, device.FieldUserID, device.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (_m *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case device.FieldPlatform:

			if value, ok := values[i].(**device2.Platform); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value != nil && *value != nil {
				_m.Platform = **value
			}
		case device.FieldToken:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value != nil && *value != nil {
				_m.Token = **value
			}
		case device.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case device.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case device.FieldCreatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil && *value != nil {
				_m.CreatedAt = **value
			}
		case device.FieldUpdatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil && *value != nil {
				_m.UpdatedAt = **value
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Device entity.
func (_m *Device) QueryUser() *UserQuery {
	return NewDeviceClient(_m.config).QueryUser(_m)
}

// QuerySession queries the "session" edge of the Device entity.
func (_m *Device) QuerySession() *SessionQuery {
	return NewDeviceClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Device) Unwrap() *Device {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
