//go:build linux

package ent

//go:generate sh -c "echo '-- Code generated by ent, DO NOT EDIT.' > ./migrate/schema.sql && go run -mod=mod github.com/neko-sc/ent/cmd/ent schema ./schema --dialect postgres --version 18 >> ./migrate/schema.sql"
