// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	photo2 "cameo/internal/ent/schema_types/photo"
	"cameo/internal/ent/user"
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// Photo is the model entity for the Photo schema.
type Photo struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status photo2.Status `json:"status,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// ThumbnailKey holds the value of the "thumbnail_key" field.
	ThumbnailKey string `json:"thumbnail_key,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Width holds the value of the "width" field.
	Width *int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height *int `json:"height,omitempty"`
	// TakenAt holds the value of the "taken_at" field.
	TakenAt *time2.Time `json:"taken_at,omitempty"`
	// FavoritedBy holds the value of the "favorited_by" field.
	FavoritedBy []uuid.UUID `json:"favorited_by,omitempty"`
	// CoupleID holds the value of the "couple_id" field.
	CoupleID uuid.UUID `json:"couple_id,omitempty"`
	// UploaderID holds the value of the "uploader_id" field.
	UploaderID uuid.UUID `json:"uploader_id,omitempty"`
	// CallID holds the value of the "call_id" field.
	CallID *uuid.UUID `json:"call_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time2.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time2.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PhotoQuery when eager-loading is set.
	Edges PhotoEdges `json:"edges"`
}

// PhotoEdges holds the relations/edges for other nodes in the graph.
type PhotoEdges struct {
	// Couple holds the value of the couple edge.
	Couple *Couple `json:"couple,omitempty"`
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// Call holds the value of the call edge.
	Call *Call `json:"call,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	counts      map[string]int
}

func (e PhotoEdges) Loaded[N, K any](edge ent.RelationOf[entity.Photo, N, K]) bool {
	switch edge.Ref().Name {
	case "couple":
		return e.loadedTypes[0]
	case "uploader":
		return e.loadedTypes[1]
	case "call":
		return e.loadedTypes[2]

	default:
		return false
	}
}

func (e *PhotoEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.Photo, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "couple":
		e.loadedTypes[0] = loaded
	case "uploader":
		e.loadedTypes[1] = loaded
	case "call":
		e.loadedTypes[2] = loaded

	}
}

func (e PhotoEdges) Count[N, K any](edge ent.Relation[entity.Photo, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// CoupleOrErr returns the Couple value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhotoEdges) CoupleOrErr() (*Couple, error) {
	if e.Couple != nil {
		return e.Couple, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: couple.Label}
	}
	return nil, &NotLoadedError{edge: "couple"}
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhotoEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// CallOrErr returns the Call value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhotoEdges) CallOrErr() (*Call, error) {
	if e.Call != nil {
		return e.Call, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: call.Label}
	}
	return nil, &NotLoadedError{edge: "call"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Photo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case photo.FieldCallID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case photo.FieldFavoritedBy:
			values[i] = new(*[]uuid.UUID)
		case photo.FieldWidth, photo.FieldHeight:
			values[i] = new(*int)
		case photo.FieldSizeBytes:
			values[i] = new(*int64)
		case photo.FieldStatus:
			values[i] = new(*photo2.Status)
		case photo.FieldContentType, photo.FieldObjectKey, photo.FieldThumbnailKey:
			values[i] = new(*string)
		case photo.FieldTakenAt, photo.FieldCreatedAt, photo.FieldUpdatedAt:
			values[i] = new(*time2.Time)
		case photo.FieldID, photo.FieldCoupleID, photo.FieldUploaderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Photo fields.
func (_m *Photo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case photo.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case photo.FieldStatus:

			if value, ok := values[i].(**photo2.Status); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value != nil && *value != nil {
				_m.Status = **value
			}
		case photo.FieldContentType:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value != nil && *value != nil {
				_m.ContentType = **value
			}
		case photo.FieldObjectKey:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value != nil && *value != nil {
				_m.ObjectKey = **value
			}
		case photo.FieldThumbnailKey:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_key", values[i])
			} else if value != nil && *value != nil {
				_m.ThumbnailKey = **value
			}
		case photo.FieldSizeBytes:

			if value, ok := values[i].(**int64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value != nil && *value != nil {
				_m.SizeBytes = **value
			}
		case photo.FieldWidth:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value != nil && *value != nil {
				_m.Width = *value
			}
		case photo.FieldHeight:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value != nil && *value != nil {
				_m.Height = *value
			}
		case photo.FieldTakenAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field taken_at", values[i])
			} else if value != nil && *value != nil {
				_m.TakenAt = *value
			}
		case photo.FieldFavoritedBy:

			if value, ok := values[i].(**[]uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field favorited_by", values[i])
			} else if value != nil && *value != nil {
				_m.FavoritedBy = **value
			}
		case photo.FieldCoupleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field couple_id", values[i])
			} else if value != nil {
				_m.CoupleID = *value
			}
		case photo.FieldUploaderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_id", values[i])
			} else if value != nil {
				_m.UploaderID = *value
			}
		case photo.FieldCallID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field call_id", values[i])
			} else if value.Valid {
				_m.CallID = new(uuid.UUID)
				*_m.CallID = *value.S.(*uuid.UUID)
			}
		case photo.FieldCreatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil && *value != nil {
				_m.CreatedAt = **value
			}
		case photo.FieldUpdatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil && *value != nil {
				_m.UpdatedAt = **value
			}
		}
	}
	return nil
}

// QueryCouple queries the "couple" edge of the Photo entity.
func (_m *Photo) QueryCouple() *CoupleQuery {
	return NewPhotoClient(_m.config).QueryCouple(_m)
}

// QueryUploader queries the "uploader" edge of the Photo entity.
func (_m *Photo) QueryUploader() *UserQuery {
	return NewPhotoClient(_m.config).QueryUploader(_m)
}

// QueryCall queries the "call" edge of the Photo entity.
func (_m *Photo) QueryCall() *CallQuery {
	return NewPhotoClient(_m.config).QueryCall(_m)
}

// Update returns a builder for updating this Photo.
// Note that you need to call Photo.Unwrap() before calling this method if this Photo
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Photo) Update() *PhotoUpdateOne {
	return NewPhotoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Photo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Photo) Unwrap() *Photo {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Photo is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Photo) String() string {
	var builder strings.Builder
	builder.WriteString("Photo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("thumbnail_key=")
	builder.WriteString(_m.ThumbnailKey)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TakenAt; v != nil {
		builder.WriteString("taken_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("favorited_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.FavoritedBy))
	builder.WriteString(", ")
	builder.WriteString("couple_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CoupleID))
	builder.WriteString(", ")
	builder.WriteString("uploader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploaderID))
	builder.WriteString(", ")
	if v := _m.CallID; v != nil {
		builder.WriteString("call_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Photos is a parsable slice of Photo.
type Photos []*Photo
