// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"cameo/internal/ent/user"
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type PhotoCreate struct {
	config
	mutation    *PhotoMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *PhotoCreate) Set[T any](column ent.ColumnOf[entity.Photo, T], value T) *PhotoCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *PhotoCreate) SetOptional[T any](column ent.ColumnOf[entity.Photo, T], value ent.Option[T]) *PhotoCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *PhotoCreate) SetExpr[T any](column ent.ColumnOf[entity.Photo, T], value ent.Expr[T]) *PhotoCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case photo.FieldID:

	case photo.FieldStatus:

	case photo.FieldContentType:

	case photo.FieldObjectKey:

	case photo.FieldThumbnailKey:

	case photo.FieldSizeBytes:

	case photo.FieldWidth:

	case photo.FieldHeight:

	case photo.FieldTakenAt:

	case photo.FieldFavoritedBy:

	case photo.FieldCoupleID:

	case photo.FieldUploaderID:

	case photo.FieldCallID:

	case photo.FieldCreatedAt:

	case photo.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *PhotoCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Photo, N, K], id K) *PhotoCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {
	case photo.EdgeCouple:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[photo.FieldCoupleID] = struct{}{}
	case photo.EdgeUploader:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[photo.FieldUploaderID] = struct{}{}
	case photo.EdgeCall:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[photo.FieldCallID] = struct{}{}

	}

	return b
}
func (b *PhotoCreate) AddIDs[N, K any](edge ent.Relation[entity.Photo, N, K], ids ...K) *PhotoCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PhotoCreate) Mutation() *PhotoMutation { return b.mutation }

func (b *PhotoCreate) Insert() *PhotoInsert { return b.mutation.insert }

func (b *PhotoCreate) Save(ctx context.Context) (*Photo, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *PhotoCreate) SaveX(ctx context.Context) *Photo {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *PhotoCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PhotoCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *PhotoCreate) defaults() error {

	if b.mutation.insert.ID.IsUnset() && b.mutation.insert.expressions[photo.FieldID] == nil {
		if photo.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized photo.DefaultID")
		}
		b.mutation.insert.ID = ent.Some(photo.DefaultID())
	}

	if b.mutation.insert.Status.IsUnset() && b.mutation.insert.expressions[photo.FieldStatus] == nil {
		if photo.DefaultStatus == nil {
			return fmt.Errorf("ent: uninitialized photo.DefaultStatus")
		}
		b.mutation.insert.Status = ent.Some(photo.DefaultStatus())
	}

	if b.mutation.insert.FavoritedBy.IsUnset() && b.mutation.insert.expressions[photo.FieldFavoritedBy] == nil {

		b.mutation.insert.FavoritedBy = ent.Some(photo.DefaultFavoritedBy)
	}

	if b.mutation.insert.CreatedAt.IsUnset() && b.mutation.insert.expressions[photo.FieldCreatedAt] == nil {
		if photo.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized photo.DefaultCreatedAt")
		}
		b.mutation.insert.CreatedAt = ent.Some(photo.DefaultCreatedAt())
	}

	if b.mutation.insert.UpdatedAt.IsUnset() && b.mutation.insert.expressions[photo.FieldUpdatedAt] == nil {
		if photo.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized photo.DefaultUpdatedAt")
		}
		b.mutation.insert.UpdatedAt = ent.Some(photo.DefaultUpdatedAt())
	}

	return nil
}

func (b *PhotoCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "Photo.id" is not nullable`)}
	}

	if b.mutation.insert.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Photo.status" is not nullable`)}
	}

	if b.mutation.insert.expressions[photo.FieldStatus] == nil {
		if v, ok := b.mutation.insert.Status.Get(); ok {

			if err := v.Validate(); err != nil {
				return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Photo.status": %w`, err)}
			}

		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldContentType]; b.fromBuilder && !present {
			return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "Photo.content_type"`)}
		}
	}

	if b.mutation.insert.expressions[photo.FieldContentType] == nil {
		v := b.mutation.insert.ContentType

		if err := photo.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Photo.content_type": %w`, err)}
		}

	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldObjectKey]; b.fromBuilder && !present {
			return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "Photo.object_key"`)}
		}
	}

	if b.mutation.insert.expressions[photo.FieldObjectKey] == nil {
		v := b.mutation.insert.ObjectKey

		if err := photo.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "Photo.object_key": %w`, err)}
		}

	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldThumbnailKey]; b.fromBuilder && !present {
			return &ValidationError{Name: "thumbnail_key", err: errors.New(`ent: missing required field "Photo.thumbnail_key"`)}
		}
	}

	if b.mutation.insert.expressions[photo.FieldThumbnailKey] == nil {
		v := b.mutation.insert.ThumbnailKey

		if err := photo.ThumbnailKeyValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_key", err: fmt.Errorf(`ent: validator failed for field "Photo.thumbnail_key": %w`, err)}
		}

	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldSizeBytes]; b.fromBuilder && !present {
			return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Photo.size_bytes"`)}
		}
	}

	if b.mutation.insert.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Photo.favorited_by" is not nullable`)}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldCoupleID]; b.fromBuilder && !present {
			return &ValidationError{Name: "couple_id", err: errors.New(`ent: missing required field "Photo.couple_id"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[photo.FieldUploaderID]; b.fromBuilder && !present {
			return &ValidationError{Name: "uploader_id", err: errors.New(`ent: missing required field "Photo.uploader_id"`)}
		}
	}

	if b.mutation.insert.CreatedAt.IsNull() {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: field "Photo.created_at" is not nullable`)}
	}

	if b.mutation.insert.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Photo.updated_at" is not nullable`)}
	}

	if len(b.mutation.insert.coupleIDs()) == 0 {
		return &ValidationError{Name: "couple", err: errors.New(`ent: missing required edge "Photo.couple"`)}
	}

	if len(b.mutation.insert.uploaderIDs()) == 0 {
		return &ValidationError{Name: "uploader", err: errors.New(`ent: missing required edge "Photo.uploader"`)}
	}

	return nil
}

func (_c *PhotoCreate) sqlSave(ctx context.Context) (*Photo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *PhotoCreate) createSpec() (*Photo, *sqlgraph.CreateSpec, error) {
	_node := &Photo{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(photo.Table, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = &value
	}

	if value, ok := _c.mutation.insert.Status.Get(); ok {
		_spec.SetField(photo.FieldStatus, field.TypeInt8, value)
	}
	if _c.mutation.insert.Status.IsNull() {
		_spec.SetField(photo.FieldStatus, field.TypeInt8, nil)
	}

	if _, present := _c.present[photo.FieldContentType]; !_c.fromBuilder || present {
		value := _c.mutation.insert.ContentType
		_spec.SetField(photo.FieldContentType, field.TypeString, value)
	}

	if _, present := _c.present[photo.FieldObjectKey]; !_c.fromBuilder || present {
		value := _c.mutation.insert.ObjectKey
		_spec.SetField(photo.FieldObjectKey, field.TypeString, value)
	}

	if _, present := _c.present[photo.FieldThumbnailKey]; !_c.fromBuilder || present {
		value := _c.mutation.insert.ThumbnailKey
		_spec.SetField(photo.FieldThumbnailKey, field.TypeString, value)
	}

	if _, present := _c.present[photo.FieldSizeBytes]; !_c.fromBuilder || present {
		value := _c.mutation.insert.SizeBytes
		_spec.SetField(photo.FieldSizeBytes, field.TypeInt64, value)
	}

	if value, ok := _c.mutation.insert.Width.Get(); ok {
		_spec.SetField(photo.FieldWidth, field.TypeInt, value)
	}
	if _c.mutation.insert.Width.IsNull() {
		_spec.SetField(photo.FieldWidth, field.TypeInt, nil)
	}

	if value, ok := _c.mutation.insert.Height.Get(); ok {
		_spec.SetField(photo.FieldHeight, field.TypeInt, value)
	}
	if _c.mutation.insert.Height.IsNull() {
		_spec.SetField(photo.FieldHeight, field.TypeInt, nil)
	}

	if value, ok := _c.mutation.insert.TakenAt.Get(); ok {
		_spec.SetField(photo.FieldTakenAt, field.TypeTime, value)
	}
	if _c.mutation.insert.TakenAt.IsNull() {
		_spec.SetField(photo.FieldTakenAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.FavoritedBy.Get(); ok {
		_spec.SetField(photo.FieldFavoritedBy, field.TypeArray, value)
	}
	if _c.mutation.insert.FavoritedBy.IsNull() {
		_spec.SetField(photo.FieldFavoritedBy, field.TypeArray, nil)
	}

	if value, ok := _c.mutation.insert.CreatedAt.Get(); ok {
		_spec.SetField(photo.FieldCreatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.CreatedAt.IsNull() {
		_spec.SetField(photo.FieldCreatedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.UpdatedAt.Get(); ok {
		_spec.SetField(photo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.UpdatedAt.IsNull() {
		_spec.SetField(photo.FieldUpdatedAt, field.TypeTime, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.coupleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CoupleTable,
			Columns: []string{photo.CoupleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couple.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.uploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.callIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CallTable,
			Columns: []string{photo.CallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: photo.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(photo.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(photo.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type PhotoUpsertOne struct{ create *PhotoCreate }

func (b *PhotoCreate) OnConflict(columns ...ent.EntityColumn[entity.Photo]) *PhotoUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *PhotoCreate) OnConflictConstraint(name string) *PhotoUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *PhotoCreate) OnConflictOptions(options ...sql.ConflictOption) *PhotoUpsertOne {
	b.conflict = options
	return &PhotoUpsertOne{create: b}
}

func (u *PhotoUpsertOne) DoNothing() *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *PhotoUpsertOne) DoSelect() *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *PhotoUpsertOne) Ignore() *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *PhotoUpsertOne) DoUpdate(set func(*PhotoUpsert)) *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&PhotoUpsert{UpdateSet: update}) }))
	return u
}

func (u *PhotoUpsertOne) UpdateNewValues() *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case photo.FieldID:
				update.SetIgnore(column)

			case photo.FieldObjectKey:
				update.SetIgnore(column)

			case photo.FieldThumbnailKey:
				update.SetIgnore(column)

			case photo.FieldCoupleID:
				update.SetIgnore(column)

			case photo.FieldUploaderID:
				update.SetIgnore(column)

			case photo.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *PhotoUpsertOne) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(photo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *PhotoUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Photo]) *PhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(photo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *PhotoUpsertOne) Save(ctx context.Context) (*Photo, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for PhotoCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *PhotoUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *PhotoUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *PhotoUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *PhotoUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type PhotoUpsert struct{ *sql.UpdateSet }

func (u *PhotoUpsert) Set[T any](column ent.ColumnOf[entity.Photo, T], value T) *PhotoUpsert {
	switch column.Ref().Name {

	case photo.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldContentType:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldSizeBytes:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldWidth:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldHeight:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldTakenAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldFavoritedBy:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldCallID:
		u.UpdateSet.Set(column.Ref().Name, value)

	case photo.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *PhotoUpsert) SetExpr[T any](column ent.ColumnOf[entity.Photo, T], value ent.Expr[T]) *PhotoUpsert {
	switch column.Ref().Name {

	case photo.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldContentType:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldSizeBytes:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldWidth:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldHeight:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldTakenAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldFavoritedBy:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldCallID:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case photo.FieldUpdatedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *PhotoUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Photo, T]) *PhotoUpsert {
	switch column.Ref().Name {

	case photo.FieldStatus:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldContentType:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldSizeBytes:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldWidth:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldHeight:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldTakenAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldFavoritedBy:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldCallID:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case photo.FieldUpdatedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *PhotoUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Photo, T], delta T) *PhotoUpsert {
	switch column.Ref().Name {

	case photo.FieldStatus:
		u.UpdateSet.Add(column.Ref().Name, delta)

	case photo.FieldSizeBytes:
		u.UpdateSet.Add(column.Ref().Name, delta)

	case photo.FieldWidth:
		u.UpdateSet.Add(column.Ref().Name, delta)

	case photo.FieldHeight:
		u.UpdateSet.Add(column.Ref().Name, delta)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *PhotoUpsert) Clear[T any](column ent.ColumnOf[entity.Photo, T]) *PhotoUpsert {
	switch column.Ref().Name {

	case photo.FieldWidth:
		u.UpdateSet.SetNull(column.Ref().Name)

	case photo.FieldHeight:
		u.UpdateSet.SetNull(column.Ref().Name)

	case photo.FieldTakenAt:
		u.UpdateSet.SetNull(column.Ref().Name)

	case photo.FieldCallID:
		u.UpdateSet.SetNull(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not nullable", column.Ref().Name)})
	}
	return u
}

type PhotoCreateBulk struct {
	config
	err      error
	builders []*PhotoCreate

	conflict []sql.ConflictOption
}

func (_c *PhotoCreateBulk) Save(ctx context.Context) ([]*Photo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Photo, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *PhotoCreateBulk) SaveX(ctx context.Context) []*Photo {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *PhotoCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PhotoCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type PhotoUpsertBulk struct{ create *PhotoCreateBulk }

func (b *PhotoCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Photo]) *PhotoUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *PhotoCreateBulk) OnConflictConstraint(name string) *PhotoUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *PhotoCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *PhotoUpsertBulk {
	b.conflict = options
	return &PhotoUpsertBulk{create: b}
}

func (u *PhotoUpsertBulk) DoNothing() *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *PhotoUpsertBulk) DoSelect() *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *PhotoUpsertBulk) Ignore() *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *PhotoUpsertBulk) DoUpdate(set func(*PhotoUpsert)) *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&PhotoUpsert{UpdateSet: update}) }))
	return u
}

func (u *PhotoUpsertBulk) UpdateNewValues() *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case photo.FieldID:
				update.SetIgnore(column)

			case photo.FieldObjectKey:
				update.SetIgnore(column)

			case photo.FieldThumbnailKey:
				update.SetIgnore(column)

			case photo.FieldCoupleID:
				update.SetIgnore(column)

			case photo.FieldUploaderID:
				update.SetIgnore(column)

			case photo.FieldCreatedAt:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *PhotoUpsertBulk) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(photo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *PhotoUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Photo]) *PhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(photo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *PhotoUpsertBulk) Save(ctx context.Context) ([]*Photo, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for PhotoCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *PhotoUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *PhotoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
