// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/photo"
	photo2 "cameo/internal/ent/schema_types/photo"
	"fmt"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// PhotoInsert is the write representation of a Photo creation.
type PhotoInsert struct {
	ID           ent.Option[uuid.UUID]     `json:"id,omitzero"`
	Status       ent.Option[photo2.Status] `json:"status,omitzero"`
	ContentType  string                    `json:"content_type"`
	ObjectKey    string                    `json:"object_key"`
	ThumbnailKey string                    `json:"thumbnail_key"`
	SizeBytes    int64                     `json:"size_bytes"`
	Width        ent.Option[int]           `json:"width,omitzero"`
	Height       ent.Option[int]           `json:"height,omitzero"`
	TakenAt      ent.Option[time2.Time]    `json:"taken_at,omitzero"`
	FavoritedBy  ent.Option[[]uuid.UUID]   `json:"favorited_by,omitzero"`
	CoupleID     uuid.UUID                 `json:"couple_id"`
	UploaderID   uuid.UUID                 `json:"uploader_id"`
	CallID       ent.Option[uuid.UUID]     `json:"call_id,omitzero"`
	CreatedAt    ent.Option[time2.Time]    `json:"created_at,omitzero"`
	UpdatedAt    ent.Option[time2.Time]    `json:"updated_at,omitzero"`
	expressions  map[string]func(*sql.Builder)
}

// PhotoPatch is the write representation of a Photo update.
type PhotoPatch struct {
	Status       ent.Option[photo2.Status] `json:"status,omitzero"`
	StatusAdd    ent.Option[photo2.Status] `json:"status_add,omitzero"`
	ContentType  ent.Option[string]        `json:"content_type,omitzero"`
	SizeBytes    ent.Option[int64]         `json:"size_bytes,omitzero"`
	SizeBytesAdd ent.Option[int64]         `json:"size_bytes_add,omitzero"`
	Width        ent.Option[int]           `json:"width,omitzero"`
	WidthAdd     ent.Option[int]           `json:"width_add,omitzero"`
	Height       ent.Option[int]           `json:"height,omitzero"`
	HeightAdd    ent.Option[int]           `json:"height_add,omitzero"`
	TakenAt      ent.Option[time2.Time]    `json:"taken_at,omitzero"`
	FavoritedBy  ent.Option[[]uuid.UUID]   `json:"favorited_by,omitzero"`
	CallID       ent.Option[uuid.UUID]     `json:"call_id,omitzero"`
	UpdatedAt    ent.Option[time2.Time]    `json:"updated_at,omitzero"`
	expressions  map[string]func(*sql.Builder)
	clearedEdges map[string]bool
}

func (i *PhotoInsert) set(column string, value any) error {
	switch column {

	case photo.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldStatus:
		v, ok := value.(photo2.Status)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Status = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldContentType:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.ContentType = v

		delete(i.expressions, column)
		return nil

	case photo.FieldObjectKey:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.ObjectKey = v

		delete(i.expressions, column)
		return nil

	case photo.FieldThumbnailKey:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.ThumbnailKey = v

		delete(i.expressions, column)
		return nil

	case photo.FieldSizeBytes:
		v, ok := value.(int64)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.SizeBytes = v

		delete(i.expressions, column)
		return nil

	case photo.FieldWidth:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Width = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldHeight:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Height = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldTakenAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.TakenAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldFavoritedBy:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.FavoritedBy = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldCoupleID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.CoupleID = v

		delete(i.expressions, column)
		return nil

	case photo.FieldUploaderID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.UploaderID = v

		delete(i.expressions, column)
		return nil

	case photo.FieldCallID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.CallID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo is not settable", column)}
}

func (i *PhotoInsert) setNull(column string) error {
	switch column {

	case photo.FieldWidth:
		i.Width = ent.Null[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldHeight:
		i.Height = ent.Null[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldTakenAt:
		i.TakenAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case photo.FieldCallID:
		i.CallID = ent.Null[uuid.UUID]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo is not nullable", column)}
}

func (i *PhotoInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *PhotoInsert) setEdge(edge string, id any) error {
	switch edge {

	case photo.EdgeCouple:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Photo", id, edge)}
		}
		return i.set(photo.FieldCoupleID, value)

	case photo.EdgeUploader:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Photo", id, edge)}
		}
		return i.set(photo.FieldUploaderID, value)

	case photo.EdgeCall:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Photo", id, edge)}
		}
		return i.set(photo.FieldCallID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo is not settable", edge)}
}

func (i *PhotoInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo does not accept IDs", edge)}
}

func (i *PhotoInsert) coupleIDs() []uuid.UUID {

	return []uuid.UUID{i.CoupleID}

}

func (i *PhotoInsert) uploaderIDs() []uuid.UUID {

	return []uuid.UUID{i.UploaderID}

}

func (i *PhotoInsert) callIDs() []uuid.UUID {

	if id, ok := i.CallID.Get(); ok {
		return []uuid.UUID{id}
	}
	return nil

}

func (i *PhotoPatch) set(column string, value any) error {
	switch column {

	case photo.FieldStatus:
		v, ok := value.(photo2.Status)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Status = ent.Some(v)

		i.StatusAdd = ent.Unset[photo2.Status]()

		delete(i.expressions, column)
		return nil

	case photo.FieldContentType:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.ContentType = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldSizeBytes:
		v, ok := value.(int64)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.SizeBytes = ent.Some(v)

		i.SizeBytesAdd = ent.Unset[int64]()

		delete(i.expressions, column)
		return nil

	case photo.FieldWidth:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Width = ent.Some(v)

		i.WidthAdd = ent.Unset[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldHeight:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.Height = ent.Some(v)

		i.HeightAdd = ent.Unset[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldTakenAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.TakenAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldFavoritedBy:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.FavoritedBy = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldCallID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.CallID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case photo.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Photo", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo is not settable", column)}
}

func (i *PhotoPatch) setNull(column string) error {
	switch column {

	case photo.FieldWidth:
		i.Width = ent.Null[int]()

		i.WidthAdd = ent.Unset[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldHeight:
		i.Height = ent.Null[int]()

		i.HeightAdd = ent.Unset[int]()

		delete(i.expressions, column)
		return nil

	case photo.FieldTakenAt:
		i.TakenAt = ent.Null[time2.Time]()

		delete(i.expressions, column)
		return nil

	case photo.FieldCallID:
		i.CallID = ent.Null[uuid.UUID]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo is not nullable", column)}
}

func (i *PhotoPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *PhotoPatch) setEdge(edge string, id any) error {
	switch edge {

	case photo.EdgeCall:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Photo", id, edge)}
		}
		return i.set(photo.FieldCallID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo is not settable", edge)}
}

func (i *PhotoPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo does not accept IDs", edge)}
}

func (i *PhotoPatch) callIDs() []uuid.UUID {

	if id, ok := i.CallID.Get(); ok {
		return []uuid.UUID{id}
	}
	return nil

}

func (p *PhotoPatch) add(column string, value any) error {
	switch column {

	case photo.FieldStatus:
		delta, ok := value.(photo2.Status)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.StatusAdd.Get(); exists {
			delta += current
		}
		p.StatusAdd = ent.Some(delta)
		return nil

	case photo.FieldSizeBytes:
		delta, ok := value.(int64)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.SizeBytesAdd.Get(); exists {
			delta += current
		}
		p.SizeBytesAdd = ent.Some(delta)
		return nil

	case photo.FieldWidth:
		delta, ok := value.(int)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.WidthAdd.Get(); exists {
			delta += current
		}
		p.WidthAdd = ent.Some(delta)
		return nil

	case photo.FieldHeight:
		delta, ok := value.(int)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.HeightAdd.Get(); exists {
			delta += current
		}
		p.HeightAdd = ent.Some(delta)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo does not support addition", column)}
}

func (p *PhotoPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Photo does not support append", column)}
}

func (p *PhotoPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo does not support removal", edge)}
}

func (p *PhotoPatch) clearEdge(edge string) error {
	switch edge {

	case photo.EdgeCall:

		if p.clearedEdges == nil {
			p.clearedEdges = make(map[string]bool)
		}
		p.clearedEdges[edge] = true
		return p.setNull(photo.FieldCallID)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Photo cannot be cleared", edge)}
}

func (p *PhotoPatch) apply(other PhotoPatch) {

	if other.Status.IsSet() {
		p.Status = other.Status
		delete(p.expressions, photo.FieldStatus)
	}

	if value, ok := other.StatusAdd.Get(); ok {
		if current, exists := p.StatusAdd.Get(); exists {
			value += current
		}
		p.StatusAdd = ent.Some(value)
	}

	if other.ContentType.IsSet() {
		p.ContentType = other.ContentType
		delete(p.expressions, photo.FieldContentType)
	}

	if other.SizeBytes.IsSet() {
		p.SizeBytes = other.SizeBytes
		delete(p.expressions, photo.FieldSizeBytes)
	}

	if value, ok := other.SizeBytesAdd.Get(); ok {
		if current, exists := p.SizeBytesAdd.Get(); exists {
			value += current
		}
		p.SizeBytesAdd = ent.Some(value)
	}

	if other.Width.IsSet() {
		p.Width = other.Width
		delete(p.expressions, photo.FieldWidth)
	}

	if value, ok := other.WidthAdd.Get(); ok {
		if current, exists := p.WidthAdd.Get(); exists {
			value += current
		}
		p.WidthAdd = ent.Some(value)
	}

	if other.Height.IsSet() {
		p.Height = other.Height
		delete(p.expressions, photo.FieldHeight)
	}

	if value, ok := other.HeightAdd.Get(); ok {
		if current, exists := p.HeightAdd.Get(); exists {
			value += current
		}
		p.HeightAdd = ent.Some(value)
	}

	if other.TakenAt.IsSet() {
		p.TakenAt = other.TakenAt
		delete(p.expressions, photo.FieldTakenAt)
	}

	if other.FavoritedBy.IsSet() {
		p.FavoritedBy = other.FavoritedBy
		delete(p.expressions, photo.FieldFavoritedBy)
	}

	if other.CallID.IsSet() {
		p.CallID = other.CallID
		delete(p.expressions, photo.FieldCallID)
	}

	if other.UpdatedAt.IsSet() {
		p.UpdatedAt = other.UpdatedAt
		delete(p.expressions, photo.FieldUpdatedAt)
	}

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
