// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

type PhotoUpdate struct {
	config
	mutation  *PhotoMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *PhotoUpdate) Set[T any](column ent.ColumnOf[entity.Photo, T], value T) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *PhotoUpdate) SetOptional[T any](column ent.ColumnOf[entity.Photo, T], value ent.Option[T]) *PhotoUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *PhotoUpdate) SetExpr[T any](column ent.ColumnOf[entity.Photo, T], value ent.Expr[T]) *PhotoUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case photo.FieldStatus:

	case photo.FieldContentType:

	case photo.FieldSizeBytes:

	case photo.FieldWidth:

	case photo.FieldHeight:

	case photo.FieldTakenAt:

	case photo.FieldFavoritedBy:

	case photo.FieldCallID:

	case photo.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *PhotoUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Photo, N, K], id K) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *PhotoUpdate) AddIDs[N, K any](edge ent.Relation[entity.Photo, N, K], ids ...K) *PhotoUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PhotoUpdate) Mutation() *PhotoMutation { return b.mutation }

func (b *PhotoUpdate) Patch() *PhotoPatch              { return b.mutation.patch }
func (b *PhotoUpdate) Apply(p PhotoPatch) *PhotoUpdate { b.mutation.patch.apply(p); return b }
func (b *PhotoUpdate) Add[T ent.Number](column ent.ColumnOf[entity.Photo, T], delta T) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *PhotoUpdate) Append[T any](column ent.ColumnOf[entity.Photo, T], values T) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *PhotoUpdate) Clear[T any](column ent.ColumnOf[entity.Photo, T]) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *PhotoUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.Photo, N, K], ids ...K) *PhotoUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PhotoUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.Photo, N, K]) *PhotoUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *PhotoUpdate) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *PhotoUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *PhotoUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *PhotoUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PhotoUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *PhotoUpdate) Returning(ctx context.Context) ([]*Photo, error) {
	nodes := make([]*Photo, 0)
	b.returning = &sqlgraph.Returning{Columns: photo.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Photo{config: b.config}
		values, err := _node.scanValues(photo.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(photo.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *PhotoUpdate) defaults() error {

	if b.mutation.patch.UpdatedAt.IsUnset() && b.mutation.patch.expressions[photo.FieldUpdatedAt] == nil {
		if photo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized photo.UpdateDefaultUpdatedAt")
		}
		b.mutation.patch.UpdatedAt = ent.Some(photo.UpdateDefaultUpdatedAt())
	}

	return nil
}

func (b *PhotoUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Photo.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[photo.FieldStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Photo.status": %w`, err)}
		}

	}

	if b.mutation.patch.ContentType.IsNull() {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: field "Photo.content_type" is not nullable`)}
	}

	if v, ok := b.mutation.patch.ContentType.Get(); ok && b.mutation.patch.expressions[photo.FieldContentType] == nil {

		if err := photo.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Photo.content_type": %w`, err)}
		}

	}

	if b.mutation.patch.SizeBytes.IsNull() {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: field "Photo.size_bytes" is not nullable`)}
	}

	if b.mutation.patch.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Photo.favorited_by" is not nullable`)}
	}

	if b.mutation.patch.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Photo.updated_at" is not nullable`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PhotoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PhotoUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PhotoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(photo.Table, photo.Columns, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(photo.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.StatusAdd.Get(); ok {
		_spec.AddField(photo.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.ContentType.Get(); ok {
		_spec.SetField(photo.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.patch.SizeBytes.Get(); ok {
		_spec.SetField(photo.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.SizeBytesAdd.Get(); ok {
		_spec.AddField(photo.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.Width.Get(); ok {
		_spec.SetField(photo.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.patch.WidthAdd.Get(); ok {
		_spec.AddField(photo.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.patch.Width.IsNull() {
		_spec.ClearField(photo.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.patch.Height.Get(); ok {
		_spec.SetField(photo.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.patch.HeightAdd.Get(); ok {
		_spec.AddField(photo.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.patch.Height.IsNull() {
		_spec.ClearField(photo.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.patch.TakenAt.Get(); ok {
		_spec.SetField(photo.FieldTakenAt, field.TypeTime, value)
	}
	if _u.mutation.patch.TakenAt.IsNull() {
		_spec.ClearField(photo.FieldTakenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.FavoritedBy.Get(); ok {
		_spec.SetField(photo.FieldFavoritedBy, field.TypeArray, value)
	}
	if value, ok := _u.mutation.patch.UpdatedAt.Get(); ok {
		_spec.SetField(photo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.CallID.IsNull() || _u.mutation.patch.clearedEdges[photo.EdgeCall] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CallTable,
			Columns: []string{photo.CallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.callIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CallTable,
			Columns: []string{photo.CallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{photo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type PhotoUpdateOne struct {
	config
	mutation *PhotoMutation
	err      error

	fields []string
	old    *Photo

	modifiers []func(*sql.UpdateBuilder)
}

func (b *PhotoUpdateOne) Set[T any](column ent.ColumnOf[entity.Photo, T], value T) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *PhotoUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.Photo, T], value ent.Option[T]) *PhotoUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *PhotoUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.Photo, T], value ent.Expr[T]) *PhotoUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case photo.FieldStatus:

	case photo.FieldContentType:

	case photo.FieldSizeBytes:

	case photo.FieldWidth:

	case photo.FieldHeight:

	case photo.FieldTakenAt:

	case photo.FieldFavoritedBy:

	case photo.FieldCallID:

	case photo.FieldUpdatedAt:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Photo is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *PhotoUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.Photo, N, K], id K) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *PhotoUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.Photo, N, K], ids ...K) *PhotoUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PhotoUpdateOne) Mutation() *PhotoMutation { return b.mutation }

func (b *PhotoUpdateOne) Patch() *PhotoPatch                 { return b.mutation.patch }
func (b *PhotoUpdateOne) Apply(p PhotoPatch) *PhotoUpdateOne { b.mutation.patch.apply(p); return b }
func (b *PhotoUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.Photo, T], delta T) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *PhotoUpdateOne) Append[T any](column ent.ColumnOf[entity.Photo, T], values T) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *PhotoUpdateOne) Clear[T any](column ent.ColumnOf[entity.Photo, T]) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *PhotoUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.Photo, N, K], ids ...K) *PhotoUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PhotoUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.Photo, N, K]) *PhotoUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *PhotoUpdateOne) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *PhotoUpdateOne) Save(ctx context.Context) (*Photo, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *PhotoUpdateOne) SaveX(ctx context.Context) *Photo {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *PhotoUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PhotoUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// Columns narrows the entity columns returned by the update. The ID is always included.
func (b *PhotoUpdateOne) Columns(columns ...ent.EntityColumn[entity.Photo]) *PhotoUpdateOne {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *PhotoUpdateOne) SaveOld(ctx context.Context) (old *Photo, updated *Photo, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &Photo{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *PhotoUpdateOne) defaults() error {

	if b.mutation.patch.UpdatedAt.IsUnset() && b.mutation.patch.expressions[photo.FieldUpdatedAt] == nil {
		if photo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized photo.UpdateDefaultUpdatedAt")
		}
		b.mutation.patch.UpdatedAt = ent.Some(photo.UpdateDefaultUpdatedAt())
	}

	return nil
}

func (b *PhotoUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Photo.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[photo.FieldStatus] == nil {

		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Photo.status": %w`, err)}
		}

	}

	if b.mutation.patch.ContentType.IsNull() {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: field "Photo.content_type" is not nullable`)}
	}

	if v, ok := b.mutation.patch.ContentType.Get(); ok && b.mutation.patch.expressions[photo.FieldContentType] == nil {

		if err := photo.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Photo.content_type": %w`, err)}
		}

	}

	if b.mutation.patch.SizeBytes.IsNull() {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: field "Photo.size_bytes" is not nullable`)}
	}

	if b.mutation.patch.FavoritedBy.IsNull() {
		return &ValidationError{Name: "favorited_by", err: errors.New(`ent: field "Photo.favorited_by" is not nullable`)}
	}

	if b.mutation.patch.UpdatedAt.IsNull() {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: field "Photo.updated_at" is not nullable`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PhotoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PhotoUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PhotoUpdateOne) sqlSave(ctx context.Context) (_node *Photo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(photo.Table, photo.Columns, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Photo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, photo.FieldID)
		for _, f := range fields {
			if !photo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != photo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(photo.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.StatusAdd.Get(); ok {
		_spec.AddField(photo.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.ContentType.Get(); ok {
		_spec.SetField(photo.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.patch.SizeBytes.Get(); ok {
		_spec.SetField(photo.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.SizeBytesAdd.Get(); ok {
		_spec.AddField(photo.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.Width.Get(); ok {
		_spec.SetField(photo.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.patch.WidthAdd.Get(); ok {
		_spec.AddField(photo.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.patch.Width.IsNull() {
		_spec.ClearField(photo.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.patch.Height.Get(); ok {
		_spec.SetField(photo.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.patch.HeightAdd.Get(); ok {
		_spec.AddField(photo.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.patch.Height.IsNull() {
		_spec.ClearField(photo.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.patch.TakenAt.Get(); ok {
		_spec.SetField(photo.FieldTakenAt, field.TypeTime, value)
	}
	if _u.mutation.patch.TakenAt.IsNull() {
		_spec.ClearField(photo.FieldTakenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.patch.FavoritedBy.Get(); ok {
		_spec.SetField(photo.FieldFavoritedBy, field.TypeArray, value)
	}
	if value, ok := _u.mutation.patch.UpdatedAt.Get(); ok {
		_spec.SetField(photo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.patch.CallID.IsNull() || _u.mutation.patch.clearedEdges[photo.EdgeCall] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CallTable,
			Columns: []string{photo.CallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.callIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.CallTable,
			Columns: []string{photo.CallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(call.FieldID, field.TypeUUID),
			},
		}
		seen := make(map[uuid.UUID]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &Photo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{photo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
