// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/call"
	"cameo/internal/ent/couple"
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"cameo/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

// PhotoQuery is the builder for querying Photo entities.
type PhotoQuery struct {
	config
	ctx        *QueryContext
	order      []ent.OrderOption[entity.Photo]
	joins      []func(*sql.Selector)
	withCounts []ent.EdgeCount

	predicates   []ent.Predicate[entity.Photo]
	withCouple   *CoupleQuery
	withUploader *UserQuery
	withCall     *CallQuery
	modifiers    []func(*sql.Selector)

	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PhotoQuery builder.
func (_q *PhotoQuery) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoQuery {
	_q.predicates = append(_q.predicates, predicates...)
	return _q
}

func (_q *PhotoQuery) WhereP(predicates ...func(*sql.Selector)) *PhotoQuery {
	for _, predicate := range predicates {
		_q.predicates = append(_q.predicates, predicate)
	}
	return _q
}

func (_q *PhotoQuery) Join(table string, on ...func(*sql.Selector)) *PhotoQuery {
	return _q.JoinAs(table, "", on...)
}

func (_q *PhotoQuery) JoinAs(table, alias string, on ...func(*sql.Selector)) *PhotoQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.Join(joined).OnP(condition.P())
	})
	return _q
}

func (_q *PhotoQuery) LeftJoin(table string, on ...func(*sql.Selector)) *PhotoQuery {
	return _q.LeftJoinAs(table, "", on...)
}

func (_q *PhotoQuery) LeftJoinAs(table, alias string, on ...func(*sql.Selector)) *PhotoQuery {
	on = append([]func(*sql.Selector){}, on...)
	_q.joins = append(_q.joins, func(selector *sql.Selector) {
		joined := sql.Dialect(selector.Dialect()).Table(table)
		if alias != "" {
			joined.As(alias)
		} else {
			joined.As(table)
		}
		condition := sql.Dialect(selector.Dialect()).Select().From(selector.Table())
		for _, predicate := range on {
			predicate(condition)
		}
		if err := condition.Err(); err != nil {
			selector.AddError(err)
		}
		selector.LeftJoin(joined).OnP(condition.P())
	})
	return _q
}

// WithCount loads the number of neighbors of a non-unique edge into each returned
// Photo, readable with Edges.Count. Only neighbors matching all predicates are
// counted, and a parent with no matching neighbor reports a present count of zero.
// At most one count is kept per edge: a later call for the same edge is ignored.
func (_q *PhotoQuery) WithCount[N, K any](edge ent.Relation[entity.Photo, N, K], predicates ...ent.Predicate[N]) *PhotoQuery {
	for _, requested := range _q.withCounts {
		if requested.Name == edge.Ref().Name {
			return _q
		}
	}
	_q.withCounts = append(_q.withCounts, ent.CountEdge(edge, predicates...))
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PhotoQuery) Limit(limit int) *PhotoQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PhotoQuery) Offset(offset int) *PhotoQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PhotoQuery) Unique(unique bool) *PhotoQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PhotoQuery) Order(o ...ent.OrderOption[entity.Photo]) *PhotoQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// Columns narrows the entity columns loaded by this query, including when it is used
// as an eager-loading query. The ID and any columns required to bind loaded edges are
// always included.
func (_q *PhotoQuery) Columns(columns ...ent.EntityColumn[entity.Photo]) *PhotoQuery {
	if len(columns) == 0 {
		panic("ent: Columns requires at least one column")
	}
	for _, column := range columns {
		_q.ctx.AppendFieldOnce(column.Ref().Name)
	}
	return _q
}

// QueryCouple chains the current query on the "couple" edge.
func (_q *PhotoQuery) QueryCouple() *CoupleQuery {
	query := (&CoupleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(photo.Table, photo.FieldID, selector),
			sqlgraph.To(couple.Table, couple.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, photo.CoupleTable, photo.CoupleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUploader chains the current query on the "uploader" edge.
func (_q *PhotoQuery) QueryUploader() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(photo.Table, photo.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, photo.UploaderTable, photo.UploaderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCall chains the current query on the "call" edge.
func (_q *PhotoQuery) QueryCall() *CallQuery {
	query := (&CallClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(photo.Table, photo.FieldID, selector),
			sqlgraph.To(call.Table, call.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, photo.CallTable, photo.CallColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Photo entity from the query.
// Returns a *NotFoundError when no Photo was found.
func (_q *PhotoQuery) First(ctx context.Context) (*Photo, error) {
	nodes, err := _q.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{photo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PhotoQuery) FirstX(ctx context.Context) *Photo {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Photo ID from the query.
// Returns a *NotFoundError when no Photo ID was found.
func (_q *PhotoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{photo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PhotoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Photo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Photo entity is found.
// Returns a *NotFoundError when no Photo entities are found.
func (_q *PhotoQuery) Only(ctx context.Context) (*Photo, error) {
	nodes, err := _q.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{photo.Label}
	default:
		return nil, &NotSingularError{photo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PhotoQuery) OnlyX(ctx context.Context) *Photo {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Photo ID in the query.
// Returns a *NotSingularError when more than one Photo ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PhotoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{photo.Label}
	default:
		err = &NotSingularError{photo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PhotoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Photos.
func (_q *PhotoQuery) All(ctx context.Context) ([]*Photo, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return _q.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (_q *PhotoQuery) AllX(ctx context.Context) []*Photo {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Photo IDs.
func (_q *PhotoQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	if ids, err = ent.Values(ctx, _q.Select(photo.ID), photo.ID); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PhotoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PhotoQuery) Count(ctx context.Context) (int, error) {
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return _q.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PhotoQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PhotoQuery) Exist(ctx context.Context) (bool, error) {
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PhotoQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PhotoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PhotoQuery) Clone() *PhotoQuery {
	if _q == nil {
		return nil
	}
	cloned := &PhotoQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]ent.OrderOption[entity.Photo]{}, _q.order...),
		predicates: append([]ent.Predicate[entity.Photo]{}, _q.predicates...),
		joins:      append([]func(*sql.Selector){}, _q.joins...),
		withCounts: append([]ent.EdgeCount{}, _q.withCounts...),

		withCouple:   _q.withCouple.Clone(),
		withUploader: _q.withUploader.Clone(),
		withCall:     _q.withCall.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}

	return cloned
}

// WithCouple tells the query-builder to eager-load the nodes that are connected to
// the "couple" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PhotoQuery) WithCouple(opts ...func(*CoupleQuery)) *PhotoQuery {
	query := (&CoupleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCouple = query
	return _q
}

// WithUploader tells the query-builder to eager-load the nodes that are connected to
// the "uploader" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PhotoQuery) WithUploader(opts ...func(*UserQuery)) *PhotoQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUploader = query
	return _q
}

// WithCall tells the query-builder to eager-load the nodes that are connected to
// the "call" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PhotoQuery) WithCall(opts ...func(*CallQuery)) *PhotoQuery {
	query := (&CallClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCall = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It can be combined with typed aggregate selections.
//
// Example:
//
//	var v []struct {
//		Status photo2.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Photo.Query().
//		GroupBy(photo.Status).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PhotoQuery) GroupBy(columns ...ent.EntityColumn[entity.Photo]) *PhotoGroupBy {
	if len(columns) == 0 {
		panic("ent: GroupBy requires at least one column")
	}
	return &PhotoGroupBy{query: _q, columns: append([]ent.EntityColumn[entity.Photo](nil), columns...)}
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status photo2.Status `json:"status,omitempty"`
//	}
//
//	client.Photo.Query().
//		Select(photo.Status).
//		Scan(ctx, &v)
func (_q *PhotoQuery) Select(selections ...ent.Selection) *PhotoSelect {
	return &PhotoSelect{query: _q, selections: append([]ent.Selection(nil), selections...)}
}

// Aggregate returns a PhotoSelect configured with the given aggregations.
func (_q *PhotoQuery) Aggregate(selections ...ent.Selection) *PhotoSelect {
	return _q.Select(selections...)
}

func (_q *PhotoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range _q.ctx.Fields {
		if !photo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PhotoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Photo, error) {
	var (
		nodes       = []*Photo{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withCouple != nil,
			_q.withUploader != nil,
			_q.withCall != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Photo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Photo{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCouple; query != nil {
		if err := _q.loadCouple(ctx, query, nodes, nil,
			func(n *Photo, e *Couple) { n.Edges.Couple = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUploader; query != nil {
		if err := _q.loadUploader(ctx, query, nodes, nil,
			func(n *Photo, e *User) { n.Edges.Uploader = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCall; query != nil {
		if err := _q.loadCall(ctx, query, nodes, nil,
			func(n *Photo, e *Call) { n.Edges.Call = e }); err != nil {
			return nil, err
		}
	}

	if len(_q.withCounts) > 0 {
		ids := make([]any, len(nodes))
		parents := make(map[uuid.UUID][]*Photo, len(nodes))
		for index, node := range nodes {
			ids[index] = node.ID
			parents[node.ID] = append(parents[node.ID], node)
			if node.Edges.counts == nil {
				node.Edges.counts = make(map[string]int)
			}
			for _, edge := range _q.withCounts {
				node.Edges.counts[edge.Name] = 0
			}
		}
		selector := sql.Dialect(_q.driver.Dialect()).Select()

		for _, edge := range _q.withCounts {
			rows, err := sqlgraph.QuerySelector(ctx, _q.driver, edge.CountQuery(selector, ids...))
			if err != nil {
				return nil, err
			}
			for rows.Next() {
				values, err := (*Photo)(nil).scanValues([]string{photo.FieldID})
				if err != nil {
					rows.Close()
					return nil, err
				}
				var count int
				if err := rows.Scan(values[0], &count); err != nil {
					rows.Close()
					return nil, err
				}
				decoded := &Photo{}
				if err := decoded.assignValues([]string{photo.FieldID}, values); err != nil {
					rows.Close()
					return nil, err
				}
				for _, parent := range parents[decoded.ID] {
					parent.Edges.counts[edge.Name] = count
				}
			}
			if err := rows.Err(); err != nil {
				rows.Close()
				return nil, err
			}
			if err := rows.Close(); err != nil {
				return nil, err
			}
		}
	}

	return nodes, nil
}

func (_q *PhotoQuery) loadCouple(ctx context.Context, query *CoupleQuery, nodes []*Photo, init func(*Photo), assign func(*Photo, *Couple)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Photo)
	for i := range nodes {
		fk := nodes[i].CoupleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(couple.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "couple_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PhotoQuery) loadUploader(ctx context.Context, query *UserQuery, nodes []*Photo, init func(*Photo), assign func(*Photo, *User)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Photo)
	for i := range nodes {
		fk := nodes[i].UploaderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "uploader_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PhotoQuery) loadCall(ctx context.Context, query *CallQuery, nodes []*Photo, init func(*Photo), assign func(*Photo, *Call)) error {
	query = query.Clone()

	query.ctx.Limit, query.ctx.Offset = nil, nil

	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Photo)
	for i := range nodes {
		if nodes[i].CallID == nil {
			continue
		}
		fk := *nodes[i].CallID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(call.ID.In(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PhotoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}

	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PhotoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(photo.Table, photo.Columns, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, photo.FieldID)
		for i := range fields {
			if fields[i] != photo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCouple != nil {
			_spec.Node.AddColumnOnce(photo.FieldCoupleID)
		}
		if _q.withUploader != nil {
			_spec.Node.AddColumnOnce(photo.FieldUploaderID)
		}
		if _q.withCall != nil {
			_spec.Node.AddColumnOnce(photo.FieldCallID)
		}
	}
	if predicates := _q.predicates; len(predicates) > 0 || len(_q.joins) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for _, join := range _q.joins {
				join(selector)
			}
			for i := range predicates {
				predicates[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PhotoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(photo.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = photo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, join := range _q.joins {
		join(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	for _, modifier := range _q.modifiers {
		modifier(selector)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *PhotoQuery) ForUpdate(opts ...sql.LockOption) *PhotoQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *PhotoQuery) ForShare(opts ...sql.LockOption) *PhotoQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries. It can be
// chained with the entity terminals (All, Count, ...) or with Select(...) for projections.
func (_q *PhotoQuery) Modify(modifiers ...func(s *sql.Selector)) *PhotoQuery {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q
}

// LimitedCount counts matching rows, stopping at limit.
func (_q *PhotoQuery) LimitedCount(ctx context.Context, limit int) (int, error) {
	if limit <= 0 {
		return 0, nil
	}
	clone := _q.Clone()
	clone.ctx.Limit = nil
	selector := clone.sqlQuery(ctx).SelectExpr(sql.Raw("1")).Limit(limit)
	query, args := selector.New().Select(sql.Count("*")).FromExpr(sql.ExprFunc(func(builder *sql.Builder) {
		builder.Wrap(func(builder *sql.Builder) {
			builder.Join(selector)
		}).WriteString(" AS ").Ident("limited_count")
	})).Query()
	rows, err := _q.driver.Query(dialect.WithStatement(ctx, &dialect.Statement{
		Kind:   dialect.StatementRead,
		Tables: []string{photo.Table},
	}), query, args)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var count int
	if rows.Next() {
		if err := rows.Scan(&count); err != nil {
			return 0, err
		}
	}
	return count, rows.Err()
}

// PhotoGroupBy is the group-by builder for Photo entities.
type PhotoGroupBy struct {
	query      *PhotoQuery
	columns    []ent.EntityColumn[entity.Photo]
	aggregates []ent.Selection
}

func (_g *PhotoGroupBy) Aggregate(selections ...ent.Selection) *PhotoGroupBy {
	_g.aggregates = append(_g.aggregates, selections...)
	return _g
}

func (_g *PhotoGroupBy) Scan(ctx context.Context, v any) error {
	return _g.selectQuery().Scan(ctx, v)
}

func (_g *PhotoGroupBy) Rows(ctx context.Context) ([]*ent.Row, error) {
	return _g.selectQuery().Rows(ctx)
}

func (_g *PhotoGroupBy) selectQuery() *PhotoSelect {
	selections := make([]ent.Selection, 0, len(_g.columns)+len(_g.aggregates))
	for _, column := range _g.columns {
		selections = append(selections, column)
	}
	selected := _g.query.Select(append(selections, _g.aggregates...)...)
	selected.groups = _g.columns
	return selected
}

// PhotoSelect is the builder for selecting fields of Photo entities.
type PhotoSelect struct {
	query      *PhotoQuery
	selections []ent.Selection
	groups     []ent.EntityColumn[entity.Photo]
}

func (_s *PhotoSelect) Aggregate(selections ...ent.Selection) *PhotoSelect {
	_s.selections = append(_s.selections, selections...)
	return _s
}

func (_s *PhotoSelect) Row(ctx context.Context) (*ent.Row, error) {
	rows, err := _s.Rows(ctx)
	if err != nil {
		return nil, err
	}
	switch len(rows) {
	case 0:
		return nil, &NotFoundError{photo.Label}
	case 1:
		return rows[0], nil
	default:
		return nil, &NotSingularError{photo.Label}
	}
}

func (_s *PhotoSelect) sqlQuery(ctx context.Context) (*sql.Selector, error) {
	root := _s.query.Clone()
	root.ctx.Fields = nil
	for _, selection := range _s.selections {
		if column := selection.Ref(); column.Name != "" && (column.Table == "" || column.Table == photo.Table) {
			root.ctx.AppendFieldOnce(column.Name)
		}
	}
	if err := root.prepareQuery(ctx); err != nil {
		return nil, err
	}
	root.modifiers = nil
	selector := root.sqlQuery(ctx)
	if len(_s.selections) > 0 {
		ent.SelectColumns(selector, _s.selections...)
	}
	for _, column := range _s.groups {
		reference := column.Ref()
		if reference.Table == "" || reference.Table == selector.TableName() {
			selector.GroupBy(selector.C(reference.Name))
		} else {
			selector.GroupBy(sql.Dialect(selector.Dialect()).Table(reference.Table).C(reference.Name))
		}
	}
	for _, modifier := range _s.query.modifiers {
		modifier(selector)
	}
	return selector, selector.Err()
}

func (_s *PhotoSelect) Scan(ctx context.Context, value any) error {
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, value)
}

func (_s *PhotoSelect) Rows(ctx context.Context) ([]*ent.Row, error) {
	if len(_s.selections) == 0 {
		return nil, errors.New("ent: Rows requires explicit selections")
	}
	selector, err := _s.sqlQuery(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := sqlgraph.QuerySelector(ctx, _s.query.driver, selector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	columns, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	if len(columns) != len(_s.selections) {
		return nil, fmt.Errorf("ent: projection column count %d differs from selection count %d", len(columns), len(_s.selections))
	}
	result := make([]*ent.Row, 0)
	for rows.Next() {
		row, destinations := ent.NewRow(_s.selections)
		if err := rows.Scan(destinations...); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return result, nil
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *PhotoSelect) Modify(modifiers ...func(s *sql.Selector)) *PhotoSelect {
	_s.query.modifiers = append(_s.query.modifiers, modifiers...)
	return _s
}
