// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/entity"
	"cameo/internal/ent/photo"
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/schema/field"
)

// PhotoDelete is the builder for deleting a Photo entity.
type PhotoDelete struct {
	config

	mutation  *PhotoMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the PhotoDelete builder.
func (_d *PhotoDelete) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PhotoDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *PhotoDelete) Returning(ctx context.Context) ([]*Photo, error) {
	nodes := make([]*Photo, 0)
	b.returning = &sqlgraph.Returning{Columns: photo.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Photo{config: b.config}
		values, err := _node.scanValues(photo.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(photo.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PhotoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PhotoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(photo.Table, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PhotoDeleteOne is the builder for deleting a single Photo entity.
type PhotoDeleteOne struct {
	_d *PhotoDelete
}

// Where appends a list predicates to the PhotoDelete builder.
func (_d *PhotoDeleteOne) Where(predicates ...ent.Predicate[entity.Photo]) *PhotoDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *PhotoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{photo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PhotoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
