// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/session"
	"fmt"
	"slices"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// SessionInsert is the write representation of a Session creation.
type SessionInsert struct {
	ID          ent.Option[uuid.UUID]  `json:"id,omitzero"`
	UserID      uuid.UUID              `json:"user_id"`
	CreatedAt   ent.Option[time2.Time] `json:"created_at,omitzero"`
	UpdatedAt   ent.Option[time2.Time] `json:"updated_at,omitzero"`
	ExpiresAt   ent.Option[time2.Time] `json:"expires_at,omitzero"`
	DeviceIDs   []uuid.UUID            `json:"device_ids,omitzero"`
	expressions map[string]func(*sql.Builder)
}

// SessionPatch is the write representation of a Session update.
type SessionPatch struct {
	UpdatedAt    ent.Option[time2.Time]       `json:"updated_at,omitzero"`
	ExpiresAt    ent.Option[time2.Time]       `json:"expires_at,omitzero"`
	Devices      ent.RelationPatch[uuid.UUID] `json:"devices,omitzero"`
	expressions  map[string]func(*sql.Builder)
	clearedEdges map[string]bool
}

func (i *SessionInsert) set(column string, value any) error {
	switch column {

	case session.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case session.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.UserID = v

		delete(i.expressions, column)
		return nil

	case session.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case session.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case session.FieldExpiresAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.ExpiresAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session is not settable", column)}
}

func (i *SessionInsert) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session is not nullable", column)}
}

func (i *SessionInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *SessionInsert) setEdge(edge string, id any) error {
	switch edge {

	case session.EdgeUser:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Session", id, edge)}
		}
		return i.set(session.FieldUserID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session is not settable", edge)}
}

func (i *SessionInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	case session.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Session", id, edge)}
			}
			i.DeviceIDs = append(i.DeviceIDs, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session does not accept IDs", edge)}
}

func (i *SessionInsert) devicesIDs() []uuid.UUID {
	return i.DeviceIDs
}

func (i *SessionInsert) userIDs() []uuid.UUID {

	return []uuid.UUID{i.UserID}

}

func (i *SessionPatch) set(column string, value any) error {
	switch column {

	case session.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case session.FieldExpiresAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Session", value, column)}
		}
		i.ExpiresAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session is not settable", column)}
}

func (i *SessionPatch) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session is not nullable", column)}
}

func (i *SessionPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *SessionPatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session is not settable", edge)}
}

func (i *SessionPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	case session.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Session", id, edge)}
			}
			i.Devices.Add = append(i.Devices.Add, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session does not accept IDs", edge)}
}

func (i *SessionPatch) devicesIDs() []uuid.UUID {
	return i.Devices.Add

}

func (p *SessionPatch) add(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session does not support addition", column)}
}

func (p *SessionPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Session does not support append", column)}
}

func (p *SessionPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	case session.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Devices.Remove = append(p.Devices.Remove, value)
			p.Devices.Add = slices.DeleteFunc(p.Devices.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session does not support removal", edge)}
}

func (p *SessionPatch) clearEdge(edge string) error {
	switch edge {

	case session.EdgeDevices:
		p.Devices.Clear = true
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Session cannot be cleared", edge)}
}

func (p *SessionPatch) apply(other SessionPatch) {

	if other.UpdatedAt.IsSet() {
		p.UpdatedAt = other.UpdatedAt
		delete(p.expressions, session.FieldUpdatedAt)
	}

	if other.ExpiresAt.IsSet() {
		p.ExpiresAt = other.ExpiresAt
		delete(p.expressions, session.FieldExpiresAt)
	}

	p.Devices.Add = append(p.Devices.Add, other.Devices.Add...)
	p.Devices.Remove = append(p.Devices.Remove, other.Devices.Remove...)
	p.Devices.Clear = p.Devices.Clear || other.Devices.Clear

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
