// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cameo/internal/ent/user"
	"fmt"
	"slices"
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
)

// UserInsert is the write representation of a User creation.
type UserInsert struct {
	ID               ent.Option[uuid.UUID]  `json:"id,omitzero"`
	Phone            string                 `json:"phone"`
	DisplayName      ent.Option[string]     `json:"display_name,omitzero"`
	PairingCode      string                 `json:"pairing_code"`
	CallAlert        ent.Option[bool]       `json:"call_alert,omitzero"`
	HighlightAlert   ent.Option[bool]       `json:"highlight_alert,omitzero"`
	CoupleID         ent.Option[uuid.UUID]  `json:"couple_id,omitzero"`
	CreatedAt        ent.Option[time2.Time] `json:"created_at,omitzero"`
	UpdatedAt        ent.Option[time2.Time] `json:"updated_at,omitzero"`
	SessionIDs       []uuid.UUID            `json:"session_ids,omitzero"`
	DeviceIDs        []uuid.UUID            `json:"device_ids,omitzero"`
	OutgoingCallIDs  []uuid.UUID            `json:"outgoing_call_ids,omitzero"`
	IncomingCallIDs  []uuid.UUID            `json:"incoming_call_ids,omitzero"`
	CallHighlightIDs []uuid.UUID            `json:"call_highlight_ids,omitzero"`
	PhotoIDs         []uuid.UUID            `json:"photo_ids,omitzero"`
	expressions      map[string]func(*sql.Builder)
}

// UserPatch is the write representation of a User update.
type UserPatch struct {
	DisplayName    ent.Option[string]           `json:"display_name,omitzero"`
	PairingCode    ent.Option[string]           `json:"pairing_code,omitzero"`
	CallAlert      ent.Option[bool]             `json:"call_alert,omitzero"`
	HighlightAlert ent.Option[bool]             `json:"highlight_alert,omitzero"`
	CoupleID       ent.Option[uuid.UUID]        `json:"couple_id,omitzero"`
	UpdatedAt      ent.Option[time2.Time]       `json:"updated_at,omitzero"`
	Sessions       ent.RelationPatch[uuid.UUID] `json:"sessions,omitzero"`
	Devices        ent.RelationPatch[uuid.UUID] `json:"devices,omitzero"`
	OutgoingCalls  ent.RelationPatch[uuid.UUID] `json:"outgoing_calls,omitzero"`
	IncomingCalls  ent.RelationPatch[uuid.UUID] `json:"incoming_calls,omitzero"`
	CallHighlights ent.RelationPatch[uuid.UUID] `json:"call_highlights,omitzero"`
	Photos         ent.RelationPatch[uuid.UUID] `json:"photos,omitzero"`
	expressions    map[string]func(*sql.Builder)
	clearedEdges   map[string]bool
}

func (i *UserInsert) set(column string, value any) error {
	switch column {

	case user.FieldID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.ID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.Phone = v

		delete(i.expressions, column)
		return nil

	case user.FieldDisplayName:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.DisplayName = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldPairingCode:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.PairingCode = v

		delete(i.expressions, column)
		return nil

	case user.FieldCallAlert:
		v, ok := value.(bool)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.CallAlert = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldHighlightAlert:
		v, ok := value.(bool)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.HighlightAlert = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldCoupleID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.CoupleID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldCreatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.CreatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User is not settable", column)}
}

func (i *UserInsert) setNull(column string) error {
	switch column {

	case user.FieldDisplayName:
		i.DisplayName = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case user.FieldCoupleID:
		i.CoupleID = ent.Null[uuid.UUID]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User is not nullable", column)}
}

func (i *UserInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *UserInsert) setEdge(edge string, id any) error {
	switch edge {

	case user.EdgeCouple:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
		}
		return i.set(user.FieldCoupleID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User is not settable", edge)}
}

func (i *UserInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	case user.EdgeSessions:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.SessionIDs = append(i.SessionIDs, value)
		}
		return nil

	case user.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.DeviceIDs = append(i.DeviceIDs, value)
		}
		return nil

	case user.EdgeOutgoingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.OutgoingCallIDs = append(i.OutgoingCallIDs, value)
		}
		return nil

	case user.EdgeIncomingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.IncomingCallIDs = append(i.IncomingCallIDs, value)
		}
		return nil

	case user.EdgeCallHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.CallHighlightIDs = append(i.CallHighlightIDs, value)
		}
		return nil

	case user.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.PhotoIDs = append(i.PhotoIDs, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User does not accept IDs", edge)}
}

func (i *UserInsert) sessionsIDs() []uuid.UUID {
	return i.SessionIDs
}

func (i *UserInsert) devicesIDs() []uuid.UUID {
	return i.DeviceIDs
}

func (i *UserInsert) outgoingcallsIDs() []uuid.UUID {
	return i.OutgoingCallIDs
}

func (i *UserInsert) incomingcallsIDs() []uuid.UUID {
	return i.IncomingCallIDs
}

func (i *UserInsert) callhighlightsIDs() []uuid.UUID {
	return i.CallHighlightIDs
}

func (i *UserInsert) photosIDs() []uuid.UUID {
	return i.PhotoIDs
}

func (i *UserInsert) coupleIDs() []uuid.UUID {

	if id, ok := i.CoupleID.Get(); ok {
		return []uuid.UUID{id}
	}
	return nil

}

func (i *UserPatch) set(column string, value any) error {
	switch column {

	case user.FieldDisplayName:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.DisplayName = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldPairingCode:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.PairingCode = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldCallAlert:
		v, ok := value.(bool)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.CallAlert = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldHighlightAlert:
		v, ok := value.(bool)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.HighlightAlert = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldCoupleID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.CoupleID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case user.FieldUpdatedAt:
		v, ok := value.(time2.Time)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of User", value, column)}
		}
		i.UpdatedAt = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User is not settable", column)}
}

func (i *UserPatch) setNull(column string) error {
	switch column {

	case user.FieldDisplayName:
		i.DisplayName = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case user.FieldCoupleID:
		i.CoupleID = ent.Null[uuid.UUID]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User is not nullable", column)}
}

func (i *UserPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *UserPatch) setEdge(edge string, id any) error {
	switch edge {

	case user.EdgeCouple:
		value, ok := id.(uuid.UUID)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
		}
		return i.set(user.FieldCoupleID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User is not settable", edge)}
}

func (i *UserPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	case user.EdgeSessions:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.Sessions.Add = append(i.Sessions.Add, value)
		}
		return nil

	case user.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.Devices.Add = append(i.Devices.Add, value)
		}
		return nil

	case user.EdgeOutgoingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.OutgoingCalls.Add = append(i.OutgoingCalls.Add, value)
		}
		return nil

	case user.EdgeIncomingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.IncomingCalls.Add = append(i.IncomingCalls.Add, value)
		}
		return nil

	case user.EdgeCallHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.CallHighlights.Add = append(i.CallHighlights.Add, value)
		}
		return nil

	case user.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of User", id, edge)}
			}
			i.Photos.Add = append(i.Photos.Add, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User does not accept IDs", edge)}
}

func (i *UserPatch) sessionsIDs() []uuid.UUID {
	return i.Sessions.Add

}

func (i *UserPatch) devicesIDs() []uuid.UUID {
	return i.Devices.Add

}

func (i *UserPatch) outgoingcallsIDs() []uuid.UUID {
	return i.OutgoingCalls.Add

}

func (i *UserPatch) incomingcallsIDs() []uuid.UUID {
	return i.IncomingCalls.Add

}

func (i *UserPatch) callhighlightsIDs() []uuid.UUID {
	return i.CallHighlights.Add

}

func (i *UserPatch) photosIDs() []uuid.UUID {
	return i.Photos.Add

}

func (i *UserPatch) coupleIDs() []uuid.UUID {

	if id, ok := i.CoupleID.Get(); ok {
		return []uuid.UUID{id}
	}
	return nil

}

func (p *UserPatch) add(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User does not support addition", column)}
}

func (p *UserPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of User does not support append", column)}
}

func (p *UserPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	case user.EdgeSessions:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Sessions.Remove = append(p.Sessions.Remove, value)
			p.Sessions.Add = slices.DeleteFunc(p.Sessions.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case user.EdgeDevices:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Devices.Remove = append(p.Devices.Remove, value)
			p.Devices.Add = slices.DeleteFunc(p.Devices.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case user.EdgeOutgoingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.OutgoingCalls.Remove = append(p.OutgoingCalls.Remove, value)
			p.OutgoingCalls.Add = slices.DeleteFunc(p.OutgoingCalls.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case user.EdgeIncomingCalls:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.IncomingCalls.Remove = append(p.IncomingCalls.Remove, value)
			p.IncomingCalls.Add = slices.DeleteFunc(p.IncomingCalls.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case user.EdgeCallHighlights:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.CallHighlights.Remove = append(p.CallHighlights.Remove, value)
			p.CallHighlights.Add = slices.DeleteFunc(p.CallHighlights.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	case user.EdgePhotos:
		for _, id := range ids {
			value, ok := id.(uuid.UUID)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Photos.Remove = append(p.Photos.Remove, value)
			p.Photos.Add = slices.DeleteFunc(p.Photos.Add, func(id uuid.UUID) bool { return id == value })
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User does not support removal", edge)}
}

func (p *UserPatch) clearEdge(edge string) error {
	switch edge {

	case user.EdgeSessions:
		p.Sessions.Clear = true
		return nil

	case user.EdgeDevices:
		p.Devices.Clear = true
		return nil

	case user.EdgeOutgoingCalls:
		p.OutgoingCalls.Clear = true
		return nil

	case user.EdgeIncomingCalls:
		p.IncomingCalls.Clear = true
		return nil

	case user.EdgeCallHighlights:
		p.CallHighlights.Clear = true
		return nil

	case user.EdgePhotos:
		p.Photos.Clear = true
		return nil

	case user.EdgeCouple:

		if p.clearedEdges == nil {
			p.clearedEdges = make(map[string]bool)
		}
		p.clearedEdges[edge] = true
		return p.setNull(user.FieldCoupleID)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of User cannot be cleared", edge)}
}

func (p *UserPatch) apply(other UserPatch) {

	if other.DisplayName.IsSet() {
		p.DisplayName = other.DisplayName
		delete(p.expressions, user.FieldDisplayName)
	}

	if other.PairingCode.IsSet() {
		p.PairingCode = other.PairingCode
		delete(p.expressions, user.FieldPairingCode)
	}

	if other.CallAlert.IsSet() {
		p.CallAlert = other.CallAlert
		delete(p.expressions, user.FieldCallAlert)
	}

	if other.HighlightAlert.IsSet() {
		p.HighlightAlert = other.HighlightAlert
		delete(p.expressions, user.FieldHighlightAlert)
	}

	if other.CoupleID.IsSet() {
		p.CoupleID = other.CoupleID
		delete(p.expressions, user.FieldCoupleID)
	}

	if other.UpdatedAt.IsSet() {
		p.UpdatedAt = other.UpdatedAt
		delete(p.expressions, user.FieldUpdatedAt)
	}

	p.Sessions.Add = append(p.Sessions.Add, other.Sessions.Add...)
	p.Sessions.Remove = append(p.Sessions.Remove, other.Sessions.Remove...)
	p.Sessions.Clear = p.Sessions.Clear || other.Sessions.Clear

	p.Devices.Add = append(p.Devices.Add, other.Devices.Add...)
	p.Devices.Remove = append(p.Devices.Remove, other.Devices.Remove...)
	p.Devices.Clear = p.Devices.Clear || other.Devices.Clear

	p.OutgoingCalls.Add = append(p.OutgoingCalls.Add, other.OutgoingCalls.Add...)
	p.OutgoingCalls.Remove = append(p.OutgoingCalls.Remove, other.OutgoingCalls.Remove...)
	p.OutgoingCalls.Clear = p.OutgoingCalls.Clear || other.OutgoingCalls.Clear

	p.IncomingCalls.Add = append(p.IncomingCalls.Add, other.IncomingCalls.Add...)
	p.IncomingCalls.Remove = append(p.IncomingCalls.Remove, other.IncomingCalls.Remove...)
	p.IncomingCalls.Clear = p.IncomingCalls.Clear || other.IncomingCalls.Clear

	p.CallHighlights.Add = append(p.CallHighlights.Add, other.CallHighlights.Add...)
	p.CallHighlights.Remove = append(p.CallHighlights.Remove, other.CallHighlights.Remove...)
	p.CallHighlights.Clear = p.CallHighlights.Clear || other.CallHighlights.Clear

	p.Photos.Add = append(p.Photos.Add, other.Photos.Add...)
	p.Photos.Remove = append(p.Photos.Remove, other.Photos.Remove...)
	p.Photos.Clear = p.Photos.Clear || other.Photos.Clear

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
