// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in cameo/internal/ent/runtime.go

const (
	Version = "v0.3.2-0.20260921044200-c788970d92d0"            // Version of ent codegen.
	Sum     = "h1:Q8QStcQ9jyVeaYh/LaqzuuhmlNzuf9w6E11P7C9kBfU=" // Sum of ent codegen.
)
